<?php

// Data functions (insert, update, delete, form) for table accidents

// This script and data application were generated by AppGini 22.13
// Download AppGini for free from https://bigprof.com/appgini/download/

function accidents_insert(&$error_message = '') {
	global $Translation;

	// mm: can member insert record?
	$arrPerm = getTablePermissions('accidents');
	if(!$arrPerm['insert']) return false;

	$data = [
		'vehicle_registration_number' => Request::lookup('vehicle_registration_number', ''),
		'closing_km' => Request::lookup('closing_km', ''),
		'drivers_surname' => Request::lookup('drivers_surname', ''),
		'drivers_contact_details' => Request::lookup('drivers_surname'),
		'dealer_name' => Request::lookup('vehicle_registration_number'),
		'model_of_vehicle' => Request::lookup('vehicle_registration_number'),
		'date_of_accident' => Request::dateComponents('date_of_accident', ''),
		'z181_accident_form' => Request::val('z181_accident_form', ''),
		'z181_accident_form_uploaded' => Request::fileUpload('z181_accident_form_uploaded', [
			'maxSize' => 5365760,
			'types' => 'txt|doc|docx|docm|odt|pdf|rtf',
			'noRename' => false,
			'dir' => '',
			'success' => function($name, $selected_id) {
			},
			'failure' => function($selected_id, $fileRemoved) {
				if(!strlen(Request::val('SelectedID'))) return '';

				/* for empty upload fields, when saving a copy of an existing record, copy the original upload field */
				return existing_value('accidents', 'z181_accident_form_uploaded', Request::val('SelectedID'));
			},
		]),
		'copy_of_trip_authority' => Request::fileUpload('copy_of_trip_authority', [
			'maxSize' => 5365760,
			'types' => 'txt|doc|docx|docm|odt|pdf|rtf',
			'noRename' => false,
			'dir' => '',
			'success' => function($name, $selected_id) {
			},
			'failure' => function($selected_id, $fileRemoved) {
				if(!strlen(Request::val('SelectedID'))) return '';

				/* for empty upload fields, when saving a copy of an existing record, copy the original upload field */
				return existing_value('accidents', 'copy_of_trip_authority', Request::val('SelectedID'));
			},
		]),
		'district' => Request::lookup('district', ''),
		'location' => Request::lookup('district'),
		'road_or_street' => Request::val('road_or_street', ''),
		'coordinates' => Request::val('coordinates', ''),
		'deaths' => Request::val('deaths', ''),
		'fatal_amount' => Request::val('fatal_amount', ''),
		'injured' => Request::val('injured', ''),
		'injured_amount' => Request::val('injured_amount', ''),
		'description_of_accident' => Request::val('description_of_accident', ''),
		'insured' => Request::val('insured', ''),
		'upload_photos_damaged_vehicle' => Request::fileUpload('upload_photos_damaged_vehicle', [
			'maxSize' => 8056832,
			'types' => 'jpg|jpeg|gif|png|webp',
			'noRename' => true,
			'dir' => '',
			'success' => function($name, $selected_id) {
				createThumbnail($name, getThumbnailSpecs('accidents', 'upload_photos_damaged_vehicle', 'tv'));
			},
			'failure' => function($selected_id, $fileRemoved) {
				if(!strlen(Request::val('SelectedID'))) return '';

				/* for empty upload fields, when saving a copy of an existing record, copy the original upload field */
				return existing_value('accidents', 'upload_photos_damaged_vehicle', Request::val('SelectedID'));
			},
		]),
		'copy_of_sketch_plan' => Request::fileUpload('copy_of_sketch_plan', [
			'maxSize' => 8056832,
			'types' => 'jpg|jpeg|gif|png|webp',
			'noRename' => false,
			'dir' => '',
			'success' => function($name, $selected_id) {
			},
			'failure' => function($selected_id, $fileRemoved) {
				if(!strlen(Request::val('SelectedID'))) return '';

				/* for empty upload fields, when saving a copy of an existing record, copy the original upload field */
				return existing_value('accidents', 'copy_of_sketch_plan', Request::val('SelectedID'));
			},
		]),
		'accident_report_driver' => Request::fileUpload('accident_report_driver', [
			'maxSize' => 8056832,
			'types' => 'txt|doc|docx|docm|odt|pdf|rtf',
			'noRename' => true,
			'dir' => '',
			'success' => function($name, $selected_id) {
			},
			'failure' => function($selected_id, $fileRemoved) {
				if(!strlen(Request::val('SelectedID'))) return '';

				/* for empty upload fields, when saving a copy of an existing record, copy the original upload field */
				return existing_value('accidents', 'accident_report_driver', Request::val('SelectedID'));
			},
		]),
		'accident_report_supervisior' => Request::fileUpload('accident_report_supervisior', [
			'maxSize' => 8056832,
			'types' => 'txt|doc|docx|docm|odt|pdf|rtf',
			'noRename' => true,
			'dir' => '',
			'success' => function($name, $selected_id) {
			},
			'failure' => function($selected_id, $fileRemoved) {
				if(!strlen(Request::val('SelectedID'))) return '';

				/* for empty upload fields, when saving a copy of an existing record, copy the original upload field */
				return existing_value('accidents', 'accident_report_supervisior', Request::val('SelectedID'));
			},
		]),
		'claims_report_accident_committee' => Request::fileUpload('claims_report_accident_committee', [
			'maxSize' => 8056832,
			'types' => 'txt|doc|docx|docm|odt|pdf|rtf',
			'noRename' => false,
			'dir' => '',
			'success' => function($name, $selected_id) {
			},
			'failure' => function($selected_id, $fileRemoved) {
				if(!strlen(Request::val('SelectedID'))) return '';

				/* for empty upload fields, when saving a copy of an existing record, copy the original upload field */
				return existing_value('accidents', 'claims_report_accident_committee', Request::val('SelectedID'));
			},
		]),
		'insurance_claims_report' => Request::fileUpload('insurance_claims_report', [
			'maxSize' => 8056832,
			'types' => 'txt|doc|docx|docm|odt|pdf|rtf',
			'noRename' => true,
			'dir' => '',
			'success' => function($name, $selected_id) {
			},
			'failure' => function($selected_id, $fileRemoved) {
				if(!strlen(Request::val('SelectedID'))) return '';

				/* for empty upload fields, when saving a copy of an existing record, copy the original upload field */
				return existing_value('accidents', 'insurance_claims_report', Request::val('SelectedID'));
			},
		]),
		'amount_paid' => Request::val('amount_paid', ''),
		'police_officer' => Request::val('police_officer', ''),
		'contact_details' => Request::val('contact_details', ''),
		'case_number' => Request::val('case_number', 'CAS_'),
		'police_report' => Request::fileUpload('police_report', [
			'maxSize' => 8056832,
			'types' => 'txt|doc|docx|docm|odt|pdf|rtf',
			'noRename' => true,
			'dir' => '',
			'success' => function($name, $selected_id) {
			},
			'failure' => function($selected_id, $fileRemoved) {
				if(!strlen(Request::val('SelectedID'))) return '';

				/* for empty upload fields, when saving a copy of an existing record, copy the original upload field */
				return existing_value('accidents', 'police_report', Request::val('SelectedID'));
			},
		]),
		'accident_report_number' => Request::val('accident_report_number', ''),
	];


	// hook: accidents_before_insert
	if(function_exists('accidents_before_insert')) {
		$args = [];
		if(!accidents_before_insert($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$error = '';
	// set empty fields to NULL
	$data = array_map(function($v) { return ($v === '' ? NULL : $v); }, $data);
	insert('accidents', backtick_keys_once($data), $error);
	if($error) {
		$error_message = $error;
		return false;
	}

	$recID = db_insert_id(db_link());

	update_calc_fields('accidents', $recID, calculated_fields()['accidents']);

	// hook: accidents_after_insert
	if(function_exists('accidents_after_insert')) {
		$res = sql("SELECT * FROM `accidents` WHERE `accident_id`='" . makeSafe($recID, false) . "' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) {
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args = [];
		if(!accidents_after_insert($data, getMemberInfo(), $args)) { return $recID; }
	}

	// mm: save ownership data
	set_record_owner('accidents', $recID, getLoggedMemberID());

	// if this record is a copy of another record, copy children if applicable
	if(strlen(Request::val('SelectedID'))) accidents_copy_children($recID, Request::val('SelectedID'));

	return $recID;
}

function accidents_copy_children($destination_id, $source_id) {
	global $Translation;
	$requests = []; // array of curl handlers for launching insert requests
	$eo = ['silentErrors' => true];
	$safe_sid = makeSafe($source_id);

	// launch requests, asynchronously
	curl_batch($requests);
}

function accidents_delete($selected_id, $AllowDeleteOfParents = false, $skipChecks = false) {
	// insure referential integrity ...
	global $Translation;
	$selected_id = makeSafe($selected_id);

	// mm: can member delete record?
	if(!check_record_permission('accidents', $selected_id, 'delete')) {
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: accidents_before_delete
	if(function_exists('accidents_before_delete')) {
		$args = [];
		if(!accidents_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'] . (
				!empty($args['error_message']) ?
					'<div class="text-bold">' . strip_tags($args['error_message']) . '</div>'
					: '' 
			);
	}

	sql("DELETE FROM `accidents` WHERE `accident_id`='{$selected_id}'", $eo);

	// hook: accidents_after_delete
	if(function_exists('accidents_after_delete')) {
		$args = [];
		accidents_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("DELETE FROM `membership_userrecords` WHERE `tableName`='accidents' AND `pkValue`='{$selected_id}'", $eo);
}

function accidents_update(&$selected_id, &$error_message = '') {
	global $Translation;

	// mm: can member edit record?
	if(!check_record_permission('accidents', $selected_id, 'edit')) return false;

	$data = [
		'vehicle_registration_number' => Request::lookup('vehicle_registration_number', ''),
		'closing_km' => Request::lookup('closing_km', ''),
		'drivers_surname' => Request::lookup('drivers_surname', ''),
		'drivers_contact_details' => Request::lookup('drivers_surname'),
		'dealer_name' => Request::lookup('vehicle_registration_number'),
		'model_of_vehicle' => Request::lookup('vehicle_registration_number'),
		'date_of_accident' => Request::dateComponents('date_of_accident', ''),
		'z181_accident_form' => Request::val('z181_accident_form', ''),
		'z181_accident_form_uploaded' => Request::fileUpload('z181_accident_form_uploaded', [
			'maxSize' => 5365760,
			'types' => 'txt|doc|docx|docm|odt|pdf|rtf',
			'noRename' => false,
			'dir' => '',
			'id' => $selected_id,
			'success' => function($name, $selected_id) {
			},
			'removeOnRequest' => true,
			'remove' => function($selected_id) {
				// do nothing: preserve removed files on server.
			},
			'failure' => function($selected_id, $fileRemoved) {
				if($fileRemoved) return '';
				return existing_value('accidents', 'z181_accident_form_uploaded', $selected_id);
			},
		]),
		'copy_of_trip_authority' => Request::fileUpload('copy_of_trip_authority', [
			'maxSize' => 5365760,
			'types' => 'txt|doc|docx|docm|odt|pdf|rtf',
			'noRename' => false,
			'dir' => '',
			'id' => $selected_id,
			'success' => function($name, $selected_id) {
			},
			'removeOnRequest' => true,
			'remove' => function($selected_id) {
				// do nothing: preserve removed files on server.
			},
			'failure' => function($selected_id, $fileRemoved) {
				if($fileRemoved) return '';
				return existing_value('accidents', 'copy_of_trip_authority', $selected_id);
			},
		]),
		'district' => Request::lookup('district', ''),
		'location' => Request::lookup('district'),
		'road_or_street' => Request::val('road_or_street', ''),
		'coordinates' => Request::val('coordinates', ''),
		'deaths' => Request::val('deaths', ''),
		'fatal_amount' => Request::val('fatal_amount', ''),
		'injured' => Request::val('injured', ''),
		'injured_amount' => Request::val('injured_amount', ''),
		'description_of_accident' => Request::val('description_of_accident', ''),
		'insured' => Request::val('insured', ''),
		'upload_photos_damaged_vehicle' => Request::fileUpload('upload_photos_damaged_vehicle', [
			'maxSize' => 8056832,
			'types' => 'jpg|jpeg|gif|png|webp',
			'noRename' => true,
			'dir' => '',
			'id' => $selected_id,
			'success' => function($name, $selected_id) {
				createThumbnail($name, getThumbnailSpecs('accidents', 'upload_photos_damaged_vehicle', 'tv'));
			},
			'removeOnRequest' => true,
			'remove' => function($selected_id) {
				// do nothing: preserve removed files on server.
			},
			'failure' => function($selected_id, $fileRemoved) {
				if($fileRemoved) return '';
				return existing_value('accidents', 'upload_photos_damaged_vehicle', $selected_id);
			},
		]),
		'copy_of_sketch_plan' => Request::fileUpload('copy_of_sketch_plan', [
			'maxSize' => 8056832,
			'types' => 'jpg|jpeg|gif|png|webp',
			'noRename' => false,
			'dir' => '',
			'id' => $selected_id,
			'success' => function($name, $selected_id) {
			},
			'removeOnRequest' => true,
			'remove' => function($selected_id) {
				// do nothing: preserve removed files on server.
			},
			'failure' => function($selected_id, $fileRemoved) {
				if($fileRemoved) return '';
				return existing_value('accidents', 'copy_of_sketch_plan', $selected_id);
			},
		]),
		'accident_report_driver' => Request::fileUpload('accident_report_driver', [
			'maxSize' => 8056832,
			'types' => 'txt|doc|docx|docm|odt|pdf|rtf',
			'noRename' => true,
			'dir' => '',
			'id' => $selected_id,
			'success' => function($name, $selected_id) {
			},
			'removeOnRequest' => true,
			'remove' => function($selected_id) {
				// do nothing: preserve removed files on server.
			},
			'failure' => function($selected_id, $fileRemoved) {
				if($fileRemoved) return '';
				return existing_value('accidents', 'accident_report_driver', $selected_id);
			},
		]),
		'accident_report_supervisior' => Request::fileUpload('accident_report_supervisior', [
			'maxSize' => 8056832,
			'types' => 'txt|doc|docx|docm|odt|pdf|rtf',
			'noRename' => true,
			'dir' => '',
			'id' => $selected_id,
			'success' => function($name, $selected_id) {
			},
			'removeOnRequest' => true,
			'remove' => function($selected_id) {
				// do nothing: preserve removed files on server.
			},
			'failure' => function($selected_id, $fileRemoved) {
				if($fileRemoved) return '';
				return existing_value('accidents', 'accident_report_supervisior', $selected_id);
			},
		]),
		'claims_report_accident_committee' => Request::fileUpload('claims_report_accident_committee', [
			'maxSize' => 8056832,
			'types' => 'txt|doc|docx|docm|odt|pdf|rtf',
			'noRename' => false,
			'dir' => '',
			'id' => $selected_id,
			'success' => function($name, $selected_id) {
			},
			'removeOnRequest' => true,
			'remove' => function($selected_id) {
				// do nothing: preserve removed files on server.
			},
			'failure' => function($selected_id, $fileRemoved) {
				if($fileRemoved) return '';
				return existing_value('accidents', 'claims_report_accident_committee', $selected_id);
			},
		]),
		'insurance_claims_report' => Request::fileUpload('insurance_claims_report', [
			'maxSize' => 8056832,
			'types' => 'txt|doc|docx|docm|odt|pdf|rtf',
			'noRename' => true,
			'dir' => '',
			'id' => $selected_id,
			'success' => function($name, $selected_id) {
			},
			'removeOnRequest' => true,
			'remove' => function($selected_id) {
				// do nothing: preserve removed files on server.
			},
			'failure' => function($selected_id, $fileRemoved) {
				if($fileRemoved) return '';
				return existing_value('accidents', 'insurance_claims_report', $selected_id);
			},
		]),
		'amount_paid' => Request::val('amount_paid', ''),
		'police_officer' => Request::val('police_officer', ''),
		'contact_details' => Request::val('contact_details', ''),
		'case_number' => Request::val('case_number', ''),
		'police_report' => Request::fileUpload('police_report', [
			'maxSize' => 8056832,
			'types' => 'txt|doc|docx|docm|odt|pdf|rtf',
			'noRename' => true,
			'dir' => '',
			'id' => $selected_id,
			'success' => function($name, $selected_id) {
			},
			'removeOnRequest' => true,
			'remove' => function($selected_id) {
				// do nothing: preserve removed files on server.
			},
			'failure' => function($selected_id, $fileRemoved) {
				if($fileRemoved) return '';
				return existing_value('accidents', 'police_report', $selected_id);
			},
		]),
		'accident_report_number' => Request::val('accident_report_number', ''),
	];

	// get existing values
	$old_data = getRecord('accidents', $selected_id);
	if(is_array($old_data)) {
		$old_data = array_map('makeSafe', $old_data);
		$old_data['selectedID'] = makeSafe($selected_id);
	}

	$data['selectedID'] = makeSafe($selected_id);

	// hook: accidents_before_update
	if(function_exists('accidents_before_update')) {
		$args = ['old_data' => $old_data];
		if(!accidents_before_update($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$set = $data; unset($set['selectedID']);
	foreach ($set as $field => $value) {
		$set[$field] = ($value !== '' && $value !== NULL) ? $value : NULL;
	}

	if(!update(
		'accidents', 
		backtick_keys_once($set), 
		['`accident_id`' => $selected_id], 
		$error_message
	)) {
		echo $error_message;
		echo '<a href="accidents_view.php?SelectedID=' . urlencode($selected_id) . "\">{$Translation['< back']}</a>";
		exit;
	}


	$eo = ['silentErrors' => true];

	update_calc_fields('accidents', $data['selectedID'], calculated_fields()['accidents']);

	// hook: accidents_after_update
	if(function_exists('accidents_after_update')) {
		$res = sql("SELECT * FROM `accidents` WHERE `accident_id`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) $data = array_map('makeSafe', $row);

		$data['selectedID'] = $data['accident_id'];
		$args = ['old_data' => $old_data];
		if(!accidents_after_update($data, getMemberInfo(), $args)) return;
	}

	// mm: update ownership data
	sql("UPDATE `membership_userrecords` SET `dateUpdated`='" . time() . "' WHERE `tableName`='accidents' AND `pkValue`='" . makeSafe($selected_id) . "'", $eo);
}

function accidents_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $separateDV = 0, $TemplateDV = '', $TemplateDVP = '') {
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;
	$eo = ['silentErrors' => true];
	$noUploads = null;
	$row = $urow = $jsReadOnly = $jsEditable = $lookups = null;

	$noSaveAsCopy = true;

	// mm: get table permissions
	$arrPerm = getTablePermissions('accidents');
	if(!$arrPerm['insert'] && $selected_id == '')
		// no insert permission and no record selected
		// so show access denied error unless TVDV
		return $separateDV ? $Translation['tableAccessDenied'] : '';
	$AllowInsert = ($arrPerm['insert'] ? true : false);
	// print preview?
	$dvprint = false;
	if(strlen($selected_id) && Request::val('dvprint_x') != '') {
		$dvprint = true;
	}

	$filterer_vehicle_registration_number = Request::val('filterer_vehicle_registration_number');
	$filterer_closing_km = Request::val('filterer_closing_km');
	$filterer_drivers_surname = Request::val('filterer_drivers_surname');
	$filterer_district = Request::val('filterer_district');

	// populate filterers, starting from children to grand-parents
	if($filterer_vehicle_registration_number && !$filterer_drivers_surname) $filterer_drivers_surname = sqlValue("select drivers_name_and_surname from gmt_fleet_register where fleet_asset_id='" . makeSafe($filterer_vehicle_registration_number) . "'");
	if($filterer_closing_km && !$filterer_vehicle_registration_number) $filterer_vehicle_registration_number = sqlValue("select vehicle_registration_number from log_sheet where fuel_log_sheet_id='" . makeSafe($filterer_closing_km) . "'");

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: vehicle_registration_number, filterable by: drivers_surname
	$combo_vehicle_registration_number = new DataCombo;
	// combobox: closing_km, filterable by: vehicle_registration_number
	$combo_closing_km = new DataCombo;
	// combobox: drivers_surname
	$combo_drivers_surname = new DataCombo;
	// combobox: date_of_accident
	$combo_date_of_accident = new DateCombo;
	$combo_date_of_accident->DateFormat = "dmy";
	$combo_date_of_accident->MinYear = defined('accidents.date_of_accident.MinYear') ? constant('accidents.date_of_accident.MinYear') : 1900;
	$combo_date_of_accident->MaxYear = defined('accidents.date_of_accident.MaxYear') ? constant('accidents.date_of_accident.MaxYear') : 2100;
	$combo_date_of_accident->DefaultDate = parseMySQLDate('', '');
	$combo_date_of_accident->MonthNames = $Translation['month names'];
	$combo_date_of_accident->NamePrefix = 'date_of_accident';
	// combobox: z181_accident_form
	$combo_z181_accident_form = new Combo;
	$combo_z181_accident_form->ListType = 2;
	$combo_z181_accident_form->MultipleSeparator = ', ';
	$combo_z181_accident_form->ListBoxHeight = 10;
	$combo_z181_accident_form->RadiosPerLine = 1;
	if(is_file(__DIR__ . '/hooks/accidents.z181_accident_form.csv')) {
		$z181_accident_form_data = addslashes(implode('', @file(__DIR__ . '/hooks/accidents.z181_accident_form.csv')));
		$combo_z181_accident_form->ListItem = array_trim(explode('||', entitiesToUTF8(convertLegacyOptions($z181_accident_form_data))));
		$combo_z181_accident_form->ListData = $combo_z181_accident_form->ListItem;
	} else {
		$combo_z181_accident_form->ListItem = array_trim(explode('||', entitiesToUTF8(convertLegacyOptions("Attached;;Not Attached"))));
		$combo_z181_accident_form->ListData = $combo_z181_accident_form->ListItem;
	}
	$combo_z181_accident_form->SelectName = 'z181_accident_form';
	// combobox: district
	$combo_district = new DataCombo;
	// combobox: deaths
	$combo_deaths = new Combo;
	$combo_deaths->ListType = 2;
	$combo_deaths->MultipleSeparator = ', ';
	$combo_deaths->ListBoxHeight = 10;
	$combo_deaths->RadiosPerLine = 1;
	if(is_file(__DIR__ . '/hooks/accidents.deaths.csv')) {
		$deaths_data = addslashes(implode('', @file(__DIR__ . '/hooks/accidents.deaths.csv')));
		$combo_deaths->ListItem = array_trim(explode('||', entitiesToUTF8(convertLegacyOptions($deaths_data))));
		$combo_deaths->ListData = $combo_deaths->ListItem;
	} else {
		$combo_deaths->ListItem = array_trim(explode('||', entitiesToUTF8(convertLegacyOptions("Yes;;No"))));
		$combo_deaths->ListData = $combo_deaths->ListItem;
	}
	$combo_deaths->SelectName = 'deaths';
	// combobox: injured
	$combo_injured = new Combo;
	$combo_injured->ListType = 0;
	$combo_injured->MultipleSeparator = ', ';
	$combo_injured->ListBoxHeight = 10;
	$combo_injured->RadiosPerLine = 1;
	if(is_file(__DIR__ . '/hooks/accidents.injured.csv')) {
		$injured_data = addslashes(implode('', @file(__DIR__ . '/hooks/accidents.injured.csv')));
		$combo_injured->ListItem = array_trim(explode('||', entitiesToUTF8(convertLegacyOptions($injured_data))));
		$combo_injured->ListData = $combo_injured->ListItem;
	} else {
		$combo_injured->ListItem = array_trim(explode('||', entitiesToUTF8(convertLegacyOptions("Yes;;No"))));
		$combo_injured->ListData = $combo_injured->ListItem;
	}
	$combo_injured->SelectName = 'injured';
	// combobox: insured
	$combo_insured = new Combo;
	$combo_insured->ListType = 0;
	$combo_insured->MultipleSeparator = ', ';
	$combo_insured->ListBoxHeight = 10;
	$combo_insured->RadiosPerLine = 1;
	if(is_file(__DIR__ . '/hooks/accidents.insured.csv')) {
		$insured_data = addslashes(implode('', @file(__DIR__ . '/hooks/accidents.insured.csv')));
		$combo_insured->ListItem = array_trim(explode('||', entitiesToUTF8(convertLegacyOptions($insured_data))));
		$combo_insured->ListData = $combo_insured->ListItem;
	} else {
		$combo_insured->ListItem = array_trim(explode('||', entitiesToUTF8(convertLegacyOptions("Yes;;No"))));
		$combo_insured->ListData = $combo_insured->ListItem;
	}
	$combo_insured->SelectName = 'insured';

	if($selected_id) {
		// mm: check member permissions
		if(!$arrPerm['view']) return $Translation['tableAccessDenied'];

		// mm: who is the owner?
		$ownerGroupID = sqlValue("SELECT `groupID` FROM `membership_userrecords` WHERE `tableName`='accidents' AND `pkValue`='" . makeSafe($selected_id) . "'");
		$ownerMemberID = sqlValue("SELECT LCASE(`memberID`) FROM `membership_userrecords` WHERE `tableName`='accidents' AND `pkValue`='" . makeSafe($selected_id) . "'");

		if($arrPerm['view'] == 1 && getLoggedMemberID() != $ownerMemberID) return $Translation['tableAccessDenied'];
		if($arrPerm['view'] == 2 && getLoggedGroupID() != $ownerGroupID) return $Translation['tableAccessDenied'];

		// can edit?
		$AllowUpdate = 0;
		if(($arrPerm['edit'] == 1 && $ownerMemberID == getLoggedMemberID()) || ($arrPerm['edit'] == 2 && $ownerGroupID == getLoggedGroupID()) || $arrPerm['edit'] == 3) {
			$AllowUpdate = 1;
		}

		$res = sql("SELECT * FROM `accidents` WHERE `accident_id`='" . makeSafe($selected_id) . "'", $eo);
		if(!($row = db_fetch_array($res))) {
			return error_message($Translation['No records found'], 'accidents_view.php', false);
		}
		$combo_vehicle_registration_number->SelectedData = $row['vehicle_registration_number'];
		$combo_closing_km->SelectedData = $row['closing_km'];
		$combo_drivers_surname->SelectedData = $row['drivers_surname'];
		$combo_date_of_accident->DefaultDate = $row['date_of_accident'];
		$combo_z181_accident_form->SelectedData = $row['z181_accident_form'];
		$combo_district->SelectedData = $row['district'];
		$combo_deaths->SelectedData = $row['deaths'];
		$combo_injured->SelectedData = $row['injured'];
		$combo_insured->SelectedData = $row['insured'];
		$urow = $row; /* unsanitized data */
		$row = array_map('safe_html', $row);
	} else {
		$filterField = Request::val('FilterField');
		$filterOperator = Request::val('FilterOperator');
		$filterValue = Request::val('FilterValue');
		$combo_vehicle_registration_number->SelectedData = $filterer_vehicle_registration_number;
		$combo_closing_km->SelectedData = $filterer_closing_km;
		$combo_drivers_surname->SelectedData = $filterer_drivers_surname;
		$combo_z181_accident_form->SelectedText = (isset($filterField[1]) && $filterField[1] == '9' && $filterOperator[1] == '<=>' ? $filterValue[1] : '');
		$combo_district->SelectedData = $filterer_district;
		$combo_deaths->SelectedText = (isset($filterField[1]) && $filterField[1] == '16' && $filterOperator[1] == '<=>' ? $filterValue[1] : '');
		$combo_injured->SelectedText = (isset($filterField[1]) && $filterField[1] == '18' && $filterOperator[1] == '<=>' ? $filterValue[1] : '');
		$combo_insured->SelectedText = (isset($filterField[1]) && $filterField[1] == '21' && $filterOperator[1] == '<=>' ? $filterValue[1] : '');
	}
	$combo_vehicle_registration_number->HTML = '<span id="vehicle_registration_number-container' . $rnd1 . '"></span><input type="hidden" name="vehicle_registration_number" id="vehicle_registration_number' . $rnd1 . '" value="' . html_attr($combo_vehicle_registration_number->SelectedData) . '">';
	$combo_vehicle_registration_number->MatchText = '<span id="vehicle_registration_number-container-readonly' . $rnd1 . '"></span><input type="hidden" name="vehicle_registration_number" id="vehicle_registration_number' . $rnd1 . '" value="' . html_attr($combo_vehicle_registration_number->SelectedData) . '">';
	$combo_closing_km->HTML = '<span id="closing_km-container' . $rnd1 . '"></span><input type="hidden" name="closing_km" id="closing_km' . $rnd1 . '" value="' . html_attr($combo_closing_km->SelectedData) . '">';
	$combo_closing_km->MatchText = '<span id="closing_km-container-readonly' . $rnd1 . '"></span><input type="hidden" name="closing_km" id="closing_km' . $rnd1 . '" value="' . html_attr($combo_closing_km->SelectedData) . '">';
	$combo_drivers_surname->HTML = '<span id="drivers_surname-container' . $rnd1 . '"></span><input type="hidden" name="drivers_surname" id="drivers_surname' . $rnd1 . '" value="' . html_attr($combo_drivers_surname->SelectedData) . '">';
	$combo_drivers_surname->MatchText = '<span id="drivers_surname-container-readonly' . $rnd1 . '"></span><input type="hidden" name="drivers_surname" id="drivers_surname' . $rnd1 . '" value="' . html_attr($combo_drivers_surname->SelectedData) . '">';
	$combo_z181_accident_form->Render();
	$combo_district->HTML = '<span id="district-container' . $rnd1 . '"></span><input type="hidden" name="district" id="district' . $rnd1 . '" value="' . html_attr($combo_district->SelectedData) . '">';
	$combo_district->MatchText = '<span id="district-container-readonly' . $rnd1 . '"></span><input type="hidden" name="district" id="district' . $rnd1 . '" value="' . html_attr($combo_district->SelectedData) . '">';
	$combo_deaths->Render();
	$combo_injured->Render();
	$combo_insured->Render();

	ob_start();
	?>

	<script>
		// initial lookup values
		AppGini.current_vehicle_registration_number__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['vehicle_registration_number'] : htmlspecialchars($filterer_vehicle_registration_number, ENT_QUOTES)); ?>"};
		AppGini.current_closing_km__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['closing_km'] : htmlspecialchars($filterer_closing_km, ENT_QUOTES)); ?>"};
		AppGini.current_drivers_surname__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['drivers_surname'] : htmlspecialchars($filterer_drivers_surname, ENT_QUOTES)); ?>"};
		AppGini.current_district__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['district'] : htmlspecialchars($filterer_district, ENT_QUOTES)); ?>"};

		jQuery(function() {
			setTimeout(function() {
				<?php echo (!$AllowUpdate || $dvprint ? 'if(typeof(vehicle_registration_number_reload__RAND__) == \'function\') vehicle_registration_number_reload__RAND__(AppGini.current_drivers_surname__RAND__.value);' : ''); ?>
				<?php echo (!$AllowUpdate || $dvprint ? 'if(typeof(closing_km_reload__RAND__) == \'function\') closing_km_reload__RAND__(AppGini.current_vehicle_registration_number__RAND__.value);' : ''); ?>
				if(typeof(drivers_surname_reload__RAND__) == 'function') drivers_surname_reload__RAND__();
				if(typeof(district_reload__RAND__) == 'function') district_reload__RAND__();
			}, 50); /* we need to slightly delay client-side execution of the above code to allow AppGini.ajaxCache to work */
		});
		function vehicle_registration_number_reload__RAND__(filterer_drivers_surname) {
		<?php if(($AllowUpdate || ($arrPerm['insert'] && !$selected_id)) && !$dvprint) { ?>

			$j("#vehicle_registration_number-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { filterer_drivers_surname: filterer_drivers_surname, id: AppGini.current_vehicle_registration_number__RAND__.value, t: 'accidents', f: 'vehicle_registration_number' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="vehicle_registration_number"]').val(resp.results[0].id);
							$j('[id=vehicle_registration_number-container-readonly__RAND__]').html('<span class="match-text" id="vehicle_registration_number-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=gmt_fleet_register_view_parent]').hide(); } else { $j('.btn[id=gmt_fleet_register_view_parent]').show(); }

						if(typeof(closing_km_reload__RAND__) == 'function') closing_km_reload__RAND__(AppGini.current_vehicle_registration_number__RAND__.value);

							if(typeof(vehicle_registration_number_update_autofills__RAND__) == 'function') vehicle_registration_number_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { filterer_drivers_surname: filterer_drivers_surname, s: term, p: page, t: 'accidents', f: 'vehicle_registration_number' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_vehicle_registration_number__RAND__.value = e.added.id;
				AppGini.current_vehicle_registration_number__RAND__.text = e.added.text;
				$j('[name="vehicle_registration_number"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=gmt_fleet_register_view_parent]').hide(); } else { $j('.btn[id=gmt_fleet_register_view_parent]').show(); }

						if(typeof(closing_km_reload__RAND__) == 'function') closing_km_reload__RAND__(AppGini.current_vehicle_registration_number__RAND__.value);

				if(typeof(vehicle_registration_number_update_autofills__RAND__) == 'function') vehicle_registration_number_update_autofills__RAND__();
			});

			if(!$j("#vehicle_registration_number-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_vehicle_registration_number__RAND__.value, t: 'accidents', f: 'vehicle_registration_number' },
					success: function(resp) {
						$j('[name="vehicle_registration_number"]').val(resp.results[0].id);
						$j('[id=vehicle_registration_number-container-readonly__RAND__]').html('<span class="match-text" id="vehicle_registration_number-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=gmt_fleet_register_view_parent]').hide(); } else { $j('.btn[id=gmt_fleet_register_view_parent]').show(); }

						if(typeof(vehicle_registration_number_update_autofills__RAND__) == 'function') vehicle_registration_number_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_vehicle_registration_number__RAND__.value, t: 'accidents', f: 'vehicle_registration_number' },
				success: function(resp) {
					$j('[id=vehicle_registration_number-container__RAND__], [id=vehicle_registration_number-container-readonly__RAND__]').html('<span class="match-text" id="vehicle_registration_number-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=gmt_fleet_register_view_parent]').hide(); } else { $j('.btn[id=gmt_fleet_register_view_parent]').show(); }

					if(typeof(vehicle_registration_number_update_autofills__RAND__) == 'function') vehicle_registration_number_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function closing_km_reload__RAND__(filterer_vehicle_registration_number) {
		<?php if(($AllowUpdate || ($arrPerm['insert'] && !$selected_id)) && !$dvprint) { ?>

			$j("#closing_km-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { filterer_vehicle_registration_number: filterer_vehicle_registration_number, id: AppGini.current_closing_km__RAND__.value, t: 'accidents', f: 'closing_km' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="closing_km"]').val(resp.results[0].id);
							$j('[id=closing_km-container-readonly__RAND__]').html('<span class="match-text" id="closing_km-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=log_sheet_view_parent]').hide(); } else { $j('.btn[id=log_sheet_view_parent]').show(); }


							if(typeof(closing_km_update_autofills__RAND__) == 'function') closing_km_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { filterer_vehicle_registration_number: filterer_vehicle_registration_number, s: term, p: page, t: 'accidents', f: 'closing_km' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_closing_km__RAND__.value = e.added.id;
				AppGini.current_closing_km__RAND__.text = e.added.text;
				$j('[name="closing_km"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=log_sheet_view_parent]').hide(); } else { $j('.btn[id=log_sheet_view_parent]').show(); }


				if(typeof(closing_km_update_autofills__RAND__) == 'function') closing_km_update_autofills__RAND__();
			});

			if(!$j("#closing_km-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_closing_km__RAND__.value, t: 'accidents', f: 'closing_km' },
					success: function(resp) {
						$j('[name="closing_km"]').val(resp.results[0].id);
						$j('[id=closing_km-container-readonly__RAND__]').html('<span class="match-text" id="closing_km-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=log_sheet_view_parent]').hide(); } else { $j('.btn[id=log_sheet_view_parent]').show(); }

						if(typeof(closing_km_update_autofills__RAND__) == 'function') closing_km_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_closing_km__RAND__.value, t: 'accidents', f: 'closing_km' },
				success: function(resp) {
					$j('[id=closing_km-container__RAND__], [id=closing_km-container-readonly__RAND__]').html('<span class="match-text" id="closing_km-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=log_sheet_view_parent]').hide(); } else { $j('.btn[id=log_sheet_view_parent]').show(); }

					if(typeof(closing_km_update_autofills__RAND__) == 'function') closing_km_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function drivers_surname_reload__RAND__() {
		<?php if(($AllowUpdate || ($arrPerm['insert'] && !$selected_id)) && !$dvprint) { ?>

			$j("#drivers_surname-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_drivers_surname__RAND__.value, t: 'accidents', f: 'drivers_surname' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="drivers_surname"]').val(resp.results[0].id);
							$j('[id=drivers_surname-container-readonly__RAND__]').html('<span class="match-text" id="drivers_surname-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=driver_view_parent]').hide(); } else { $j('.btn[id=driver_view_parent]').show(); }

						if(typeof(vehicle_registration_number_reload__RAND__) == 'function') vehicle_registration_number_reload__RAND__(AppGini.current_drivers_surname__RAND__.value);

							if(typeof(drivers_surname_update_autofills__RAND__) == 'function') drivers_surname_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'accidents', f: 'drivers_surname' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_drivers_surname__RAND__.value = e.added.id;
				AppGini.current_drivers_surname__RAND__.text = e.added.text;
				$j('[name="drivers_surname"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=driver_view_parent]').hide(); } else { $j('.btn[id=driver_view_parent]').show(); }

						if(typeof(vehicle_registration_number_reload__RAND__) == 'function') vehicle_registration_number_reload__RAND__(AppGini.current_drivers_surname__RAND__.value);

				if(typeof(drivers_surname_update_autofills__RAND__) == 'function') drivers_surname_update_autofills__RAND__();
			});

			if(!$j("#drivers_surname-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_drivers_surname__RAND__.value, t: 'accidents', f: 'drivers_surname' },
					success: function(resp) {
						$j('[name="drivers_surname"]').val(resp.results[0].id);
						$j('[id=drivers_surname-container-readonly__RAND__]').html('<span class="match-text" id="drivers_surname-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=driver_view_parent]').hide(); } else { $j('.btn[id=driver_view_parent]').show(); }

						if(typeof(drivers_surname_update_autofills__RAND__) == 'function') drivers_surname_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_drivers_surname__RAND__.value, t: 'accidents', f: 'drivers_surname' },
				success: function(resp) {
					$j('[id=drivers_surname-container__RAND__], [id=drivers_surname-container-readonly__RAND__]').html('<span class="match-text" id="drivers_surname-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=driver_view_parent]').hide(); } else { $j('.btn[id=driver_view_parent]').show(); }

					if(typeof(drivers_surname_update_autofills__RAND__) == 'function') drivers_surname_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function district_reload__RAND__() {
		<?php if(($AllowUpdate || ($arrPerm['insert'] && !$selected_id)) && !$dvprint) { ?>

			$j("#district-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_district__RAND__.value, t: 'accidents', f: 'district' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="district"]').val(resp.results[0].id);
							$j('[id=district-container-readonly__RAND__]').html('<span class="match-text" id="district-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=districts_view_parent]').hide(); } else { $j('.btn[id=districts_view_parent]').show(); }


							if(typeof(district_update_autofills__RAND__) == 'function') district_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'accidents', f: 'district' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_district__RAND__.value = e.added.id;
				AppGini.current_district__RAND__.text = e.added.text;
				$j('[name="district"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=districts_view_parent]').hide(); } else { $j('.btn[id=districts_view_parent]').show(); }


				if(typeof(district_update_autofills__RAND__) == 'function') district_update_autofills__RAND__();
			});

			if(!$j("#district-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_district__RAND__.value, t: 'accidents', f: 'district' },
					success: function(resp) {
						$j('[name="district"]').val(resp.results[0].id);
						$j('[id=district-container-readonly__RAND__]').html('<span class="match-text" id="district-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=districts_view_parent]').hide(); } else { $j('.btn[id=districts_view_parent]').show(); }

						if(typeof(district_update_autofills__RAND__) == 'function') district_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_district__RAND__.value, t: 'accidents', f: 'district' },
				success: function(resp) {
					$j('[id=district-container__RAND__], [id=district-container-readonly__RAND__]').html('<span class="match-text" id="district-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=districts_view_parent]').hide(); } else { $j('.btn[id=districts_view_parent]').show(); }

					if(typeof(district_update_autofills__RAND__) == 'function') district_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_clean());


	// code for template based detail view forms

	// open the detail view template
	if($dvprint) {
		$template_file = is_file("./{$TemplateDVP}") ? "./{$TemplateDVP}" : './templates/accidents_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	} else {
		$template_file = is_file("./{$TemplateDV}") ? "./{$TemplateDV}" : './templates/accidents_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Accident Details:', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', (Request::val('Embedded') ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($arrPerm['insert'] && !$selected_id) { // allow insert and no record selected?
		if(!$selected_id) $templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return accidents_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return accidents_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if(Request::val('Embedded')) {
		$backAction = 'AppGini.closeParentModal(); return false;';
	} else {
		$backAction = '$j(\'form\').eq(0).attr(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id) {
		if(!Request::val('Embedded')) $templateCode = str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$j(\'form\').eq(0).prop(\'novalidate\', true); document.myform.reset(); return true;" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($AllowUpdate) {
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return accidents_validateData();" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		} else {
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		}
		if(($arrPerm['delete'] == 1 && $ownerMemberID == getLoggedMemberID()) || ($arrPerm['delete'] == 2 && $ownerGroupID == getLoggedGroupID()) || $arrPerm['delete'] == 3) { // allow delete?
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" onclick="return confirm(\'' . $Translation['are you sure?'] . '\');" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		} else {
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);

		// if not in embedded mode and user has insert only but no view/update/delete,
		// remove 'back' button
		if(
			$arrPerm['insert']
			&& !$arrPerm['update'] && !$arrPerm['delete'] && !$arrPerm['view']
			&& !Request::val('Embedded')
		)
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
		elseif($separateDV)
			$templateCode = str_replace(
				'<%%DESELECT_BUTTON%%>', 
				'<button
					type="submit" 
					class="btn btn-default" 
					id="deselect" 
					name="deselect_x" 
					value="1" 
					onclick="' . $backAction . '" 
					title="' . html_attr($Translation['Back']) . '">
						<i class="glyphicon glyphicon-chevron-left"></i> ' .
						$Translation['Back'] .
				'</button>',
				$templateCode
			);
		else
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate) || (!$selected_id && !$AllowInsert)) {
		$jsReadOnly = '';
		$jsReadOnly .= "\tjQuery('#vehicle_registration_number').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#vehicle_registration_number_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#closing_km').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#closing_km_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#drivers_surname').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#drivers_surname_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#date_of_accident').prop('readonly', true);\n";
		$jsReadOnly .= "\tjQuery('#date_of_accidentDay, #date_of_accidentMonth, #date_of_accidentYear').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('input[name=z181_accident_form]').parent().html('<div class=\"form-control-static\">' + jQuery('input[name=z181_accident_form]:checked').next().text() + '</div>')\n";
		$jsReadOnly .= "\tjQuery('#z181_accident_form_uploaded').replaceWith('<div class=\"form-control-static\" id=\"z181_accident_form_uploaded\">' + (jQuery('#z181_accident_form_uploaded').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#z181_accident_form_uploaded, #z181_accident_form_uploaded-edit-link').hide();\n";
		$jsReadOnly .= "\tjQuery('#copy_of_trip_authority').replaceWith('<div class=\"form-control-static\" id=\"copy_of_trip_authority\">' + (jQuery('#copy_of_trip_authority').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#copy_of_trip_authority, #copy_of_trip_authority-edit-link').hide();\n";
		$jsReadOnly .= "\tjQuery('#district').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#district_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#road_or_street').replaceWith('<div class=\"form-control-static\" id=\"road_or_street\">' + (jQuery('#road_or_street').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#coordinates').replaceWith('<div class=\"form-control-static\" id=\"coordinates\">' + (jQuery('#coordinates').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('input[name=deaths]').parent().html('<div class=\"form-control-static\">' + jQuery('input[name=deaths]:checked').next().text() + '</div>')\n";
		$jsReadOnly .= "\tjQuery('#fatal_amount').replaceWith('<div class=\"form-control-static\" id=\"fatal_amount\">' + (jQuery('#fatal_amount').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#injured').replaceWith('<div class=\"form-control-static\" id=\"injured\">' + (jQuery('#injured').val() || '') + '</div>'); jQuery('#injured-multi-selection-help').hide();\n";
		$jsReadOnly .= "\tjQuery('#injured_amount').replaceWith('<div class=\"form-control-static\" id=\"injured_amount\">' + (jQuery('#injured_amount').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#insured').replaceWith('<div class=\"form-control-static\" id=\"insured\">' + (jQuery('#insured').val() || '') + '</div>'); jQuery('#insured-multi-selection-help').hide();\n";
		$jsReadOnly .= "\tjQuery('#upload_photos_damaged_vehicle').replaceWith('<div class=\"form-control-static\" id=\"upload_photos_damaged_vehicle\">' + (jQuery('#upload_photos_damaged_vehicle').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#copy_of_sketch_plan').replaceWith('<div class=\"form-control-static\" id=\"copy_of_sketch_plan\">' + (jQuery('#copy_of_sketch_plan').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#copy_of_sketch_plan, #copy_of_sketch_plan-edit-link').hide();\n";
		$jsReadOnly .= "\tjQuery('#accident_report_driver').replaceWith('<div class=\"form-control-static\" id=\"accident_report_driver\">' + (jQuery('#accident_report_driver').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#accident_report_driver, #accident_report_driver-edit-link').hide();\n";
		$jsReadOnly .= "\tjQuery('#accident_report_supervisior').replaceWith('<div class=\"form-control-static\" id=\"accident_report_supervisior\">' + (jQuery('#accident_report_supervisior').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#accident_report_supervisior, #accident_report_supervisior-edit-link').hide();\n";
		$jsReadOnly .= "\tjQuery('#claims_report_accident_committee').replaceWith('<div class=\"form-control-static\" id=\"claims_report_accident_committee\">' + (jQuery('#claims_report_accident_committee').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#claims_report_accident_committee, #claims_report_accident_committee-edit-link').hide();\n";
		$jsReadOnly .= "\tjQuery('#insurance_claims_report').replaceWith('<div class=\"form-control-static\" id=\"insurance_claims_report\">' + (jQuery('#insurance_claims_report').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#insurance_claims_report, #insurance_claims_report-edit-link').hide();\n";
		$jsReadOnly .= "\tjQuery('#amount_paid').replaceWith('<div class=\"form-control-static\" id=\"amount_paid\">' + (jQuery('#amount_paid').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#police_officer').replaceWith('<div class=\"form-control-static\" id=\"police_officer\">' + (jQuery('#police_officer').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#contact_details').replaceWith('<div class=\"form-control-static\" id=\"contact_details\">' + (jQuery('#contact_details').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#case_number').replaceWith('<div class=\"form-control-static\" id=\"case_number\">' + (jQuery('#case_number').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#police_report').replaceWith('<div class=\"form-control-static\" id=\"police_report\">' + (jQuery('#police_report').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#police_report, #police_report-edit-link').hide();\n";
		$jsReadOnly .= "\tjQuery('#accident_report_number').replaceWith('<div class=\"form-control-static\" id=\"accident_report_number\">' + (jQuery('#accident_report_number').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	} elseif(($AllowInsert && !$selected_id) || ($AllowUpdate && $selected_id)) {
		$jsEditable = "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode = str_replace('<%%COMBO(vehicle_registration_number)%%>', $combo_vehicle_registration_number->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(vehicle_registration_number)%%>', $combo_vehicle_registration_number->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(vehicle_registration_number)%%>', urlencode($combo_vehicle_registration_number->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(closing_km)%%>', $combo_closing_km->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(closing_km)%%>', $combo_closing_km->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(closing_km)%%>', urlencode($combo_closing_km->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(drivers_surname)%%>', $combo_drivers_surname->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(drivers_surname)%%>', $combo_drivers_surname->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(drivers_surname)%%>', urlencode($combo_drivers_surname->MatchText), $templateCode);
	$templateCode = str_replace(
		'<%%COMBO(date_of_accident)%%>', 
		($selected_id && !$arrPerm['edit'] && ($noSaveAsCopy || !$arrPerm['insert']) ? 
			'<div class="form-control-static">' . $combo_date_of_accident->GetHTML(true) . '</div>' : 
			$combo_date_of_accident->GetHTML()
		), $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(date_of_accident)%%>', $combo_date_of_accident->GetHTML(true), $templateCode);
	$templateCode = str_replace('<%%COMBO(z181_accident_form)%%>', $combo_z181_accident_form->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(z181_accident_form)%%>', $combo_z181_accident_form->SelectedData, $templateCode);
	$templateCode = str_replace('<%%COMBO(district)%%>', $combo_district->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(district)%%>', $combo_district->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(district)%%>', urlencode($combo_district->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(deaths)%%>', $combo_deaths->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(deaths)%%>', $combo_deaths->SelectedData, $templateCode);
	$templateCode = str_replace('<%%COMBO(injured)%%>', $combo_injured->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(injured)%%>', $combo_injured->SelectedData, $templateCode);
	$templateCode = str_replace('<%%COMBO(insured)%%>', $combo_insured->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(insured)%%>', $combo_insured->SelectedData, $templateCode);

	/* lookup fields array: 'lookup field name' => ['parent table name', 'lookup field caption'] */
	$lookup_fields = ['vehicle_registration_number' => ['gmt_fleet_register', 'Registration Number:'], 'closing_km' => ['log_sheet', 'Closing KM:'], 'drivers_surname' => ['driver', 'Driver\'s Surname:'], 'district' => ['districts', 'District:'], ];
	foreach($lookup_fields as $luf => $ptfc) {
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if($pt_perm['view'] || $pt_perm['edit']) {
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] /* && !Request::val('Embedded')*/) {
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-default add_new_parent" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus text-success"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(accident_id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(vehicle_registration_number)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(closing_km)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(drivers_surname)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(date_of_accident)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(z181_accident_form)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(z181_accident_form_uploaded)%%>', ($noUploads ? '' : "<div>{$Translation['upload image']}</div>" . '<i class="glyphicon glyphicon-remove text-danger clear-upload hidden"></i> <input type="file" name="z181_accident_form_uploaded" id="z181_accident_form_uploaded" data-filetypes="txt|doc|docx|docm|odt|pdf|rtf" data-maxsize="5365760" accept=".txt,.doc,.docx,.docm,.odt,.pdf,.rtf">'), $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(copy_of_trip_authority)%%>', ($noUploads ? '' : "<div>{$Translation['upload image']}</div>" . '<i class="glyphicon glyphicon-remove text-danger clear-upload hidden"></i> <input type="file" name="copy_of_trip_authority" id="copy_of_trip_authority" data-filetypes="txt|doc|docx|docm|odt|pdf|rtf" data-maxsize="5365760" accept=".txt,.doc,.docx,.docm,.odt,.pdf,.rtf">'), $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(district)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(road_or_street)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(coordinates)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(deaths)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(fatal_amount)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(injured)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(injured_amount)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(description_of_accident)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(insured)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(upload_photos_damaged_vehicle)%%>', ($noUploads ? '' : "<div>{$Translation['upload image']}</div>" . '<i class="glyphicon glyphicon-remove text-danger clear-upload hidden"></i> <input type="file" name="upload_photos_damaged_vehicle" id="upload_photos_damaged_vehicle" data-filetypes="jpg|jpeg|gif|png|webp" data-maxsize="8056832" accept=".jpg,.jpeg,.gif,.png,.webp">'), $templateCode);
	if($AllowUpdate && $row['upload_photos_damaged_vehicle'] != '') {
		$templateCode = str_replace('<%%REMOVEFILE(upload_photos_damaged_vehicle)%%>', '<br><input type="checkbox" name="upload_photos_damaged_vehicle_remove" id="upload_photos_damaged_vehicle_remove" value="1"> <label for="upload_photos_damaged_vehicle_remove" style="color: red; font-weight: bold;">'.$Translation['remove image'].'</label>', $templateCode);
	} else {
		$templateCode = str_replace('<%%REMOVEFILE(upload_photos_damaged_vehicle)%%>', '', $templateCode);
	}
	$templateCode = str_replace('<%%UPLOADFILE(copy_of_sketch_plan)%%>', ($noUploads ? '' : "<div>{$Translation['upload image']}</div>" . '<i class="glyphicon glyphicon-remove text-danger clear-upload hidden"></i> <input type="file" name="copy_of_sketch_plan" id="copy_of_sketch_plan" data-filetypes="jpg|jpeg|gif|png|webp" data-maxsize="8056832" accept=".jpg,.jpeg,.gif,.png,.webp">'), $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(accident_report_driver)%%>', ($noUploads ? '' : "<div>{$Translation['upload image']}</div>" . '<i class="glyphicon glyphicon-remove text-danger clear-upload hidden"></i> <input type="file" name="accident_report_driver" id="accident_report_driver" data-filetypes="txt|doc|docx|docm|odt|pdf|rtf" data-maxsize="8056832" accept=".txt,.doc,.docx,.docm,.odt,.pdf,.rtf">'), $templateCode);
	if($AllowUpdate && $row['accident_report_driver'] != '') {
		$templateCode = str_replace('<%%REMOVEFILE(accident_report_driver)%%>', '<br><input type="checkbox" name="accident_report_driver_remove" id="accident_report_driver_remove" value="1"> <label for="accident_report_driver_remove" style="color: red; font-weight: bold;">'.$Translation['remove image'].'</label>', $templateCode);
	} else {
		$templateCode = str_replace('<%%REMOVEFILE(accident_report_driver)%%>', '', $templateCode);
	}
	$templateCode = str_replace('<%%UPLOADFILE(accident_report_supervisior)%%>', ($noUploads ? '' : "<div>{$Translation['upload image']}</div>" . '<i class="glyphicon glyphicon-remove text-danger clear-upload hidden"></i> <input type="file" name="accident_report_supervisior" id="accident_report_supervisior" data-filetypes="txt|doc|docx|docm|odt|pdf|rtf" data-maxsize="8056832" accept=".txt,.doc,.docx,.docm,.odt,.pdf,.rtf">'), $templateCode);
	if($AllowUpdate && $row['accident_report_supervisior'] != '') {
		$templateCode = str_replace('<%%REMOVEFILE(accident_report_supervisior)%%>', '<br><input type="checkbox" name="accident_report_supervisior_remove" id="accident_report_supervisior_remove" value="1"> <label for="accident_report_supervisior_remove" style="color: red; font-weight: bold;">'.$Translation['remove image'].'</label>', $templateCode);
	} else {
		$templateCode = str_replace('<%%REMOVEFILE(accident_report_supervisior)%%>', '', $templateCode);
	}
	$templateCode = str_replace('<%%UPLOADFILE(claims_report_accident_committee)%%>', ($noUploads ? '' : "<div>{$Translation['upload image']}</div>" . '<i class="glyphicon glyphicon-remove text-danger clear-upload hidden"></i> <input type="file" name="claims_report_accident_committee" id="claims_report_accident_committee" data-filetypes="txt|doc|docx|docm|odt|pdf|rtf" data-maxsize="8056832" accept=".txt,.doc,.docx,.docm,.odt,.pdf,.rtf">'), $templateCode);
	if($AllowUpdate && $row['claims_report_accident_committee'] != '') {
		$templateCode = str_replace('<%%REMOVEFILE(claims_report_accident_committee)%%>', '<br><input type="checkbox" name="claims_report_accident_committee_remove" id="claims_report_accident_committee_remove" value="1"> <label for="claims_report_accident_committee_remove" style="color: red; font-weight: bold;">'.$Translation['remove image'].'</label>', $templateCode);
	} else {
		$templateCode = str_replace('<%%REMOVEFILE(claims_report_accident_committee)%%>', '', $templateCode);
	}
	$templateCode = str_replace('<%%UPLOADFILE(insurance_claims_report)%%>', ($noUploads ? '' : "<div>{$Translation['upload image']}</div>" . '<i class="glyphicon glyphicon-remove text-danger clear-upload hidden"></i> <input type="file" name="insurance_claims_report" id="insurance_claims_report" data-filetypes="txt|doc|docx|docm|odt|pdf|rtf" data-maxsize="8056832" accept=".txt,.doc,.docx,.docm,.odt,.pdf,.rtf">'), $templateCode);
	if($AllowUpdate && $row['insurance_claims_report'] != '') {
		$templateCode = str_replace('<%%REMOVEFILE(insurance_claims_report)%%>', '<br><input type="checkbox" name="insurance_claims_report_remove" id="insurance_claims_report_remove" value="1"> <label for="insurance_claims_report_remove" style="color: red; font-weight: bold;">'.$Translation['remove image'].'</label>', $templateCode);
	} else {
		$templateCode = str_replace('<%%REMOVEFILE(insurance_claims_report)%%>', '', $templateCode);
	}
	$templateCode = str_replace('<%%UPLOADFILE(amount_paid)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(police_officer)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(contact_details)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(case_number)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(police_report)%%>', ($noUploads ? '' : "<div>{$Translation['upload image']}</div>" . '<i class="glyphicon glyphicon-remove text-danger clear-upload hidden"></i> <input type="file" name="police_report" id="police_report" data-filetypes="txt|doc|docx|docm|odt|pdf|rtf" data-maxsize="8056832" accept=".txt,.doc,.docx,.docm,.odt,.pdf,.rtf">'), $templateCode);
	if($AllowUpdate && $row['police_report'] != '') {
		$templateCode = str_replace('<%%REMOVEFILE(police_report)%%>', '<br><input type="checkbox" name="police_report_remove" id="police_report_remove" value="1"> <label for="police_report_remove" style="color: red; font-weight: bold;">'.$Translation['remove image'].'</label>', $templateCode);
	} else {
		$templateCode = str_replace('<%%REMOVEFILE(police_report)%%>', '', $templateCode);
	}
	$templateCode = str_replace('<%%UPLOADFILE(accident_report_number)%%>', '', $templateCode);

	// process values
	if($selected_id) {
		if( $dvprint) $templateCode = str_replace('<%%VALUE(accident_id)%%>', safe_html($urow['accident_id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(accident_id)%%>', html_attr($row['accident_id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(accident_id)%%>', urlencode($urow['accident_id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(vehicle_registration_number)%%>', safe_html($urow['vehicle_registration_number']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(vehicle_registration_number)%%>', html_attr($row['vehicle_registration_number']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(vehicle_registration_number)%%>', urlencode($urow['vehicle_registration_number']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(closing_km)%%>', safe_html($urow['closing_km']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(closing_km)%%>', html_attr($row['closing_km']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(closing_km)%%>', urlencode($urow['closing_km']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(drivers_surname)%%>', safe_html($urow['drivers_surname']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(drivers_surname)%%>', html_attr($row['drivers_surname']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(drivers_surname)%%>', urlencode($urow['drivers_surname']), $templateCode);
		$templateCode = str_replace('<%%VALUE(date_of_accident)%%>', app_datetime($row['date_of_accident']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(date_of_accident)%%>', urlencode(app_datetime($urow['date_of_accident'])), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(z181_accident_form)%%>', safe_html($urow['z181_accident_form']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(z181_accident_form)%%>', html_attr($row['z181_accident_form']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(z181_accident_form)%%>', urlencode($urow['z181_accident_form']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(z181_accident_form_uploaded)%%>', safe_html($urow['z181_accident_form_uploaded']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(z181_accident_form_uploaded)%%>', html_attr($row['z181_accident_form_uploaded']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(z181_accident_form_uploaded)%%>', urlencode($urow['z181_accident_form_uploaded']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(copy_of_trip_authority)%%>', safe_html($urow['copy_of_trip_authority']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(copy_of_trip_authority)%%>', html_attr($row['copy_of_trip_authority']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(copy_of_trip_authority)%%>', urlencode($urow['copy_of_trip_authority']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(district)%%>', safe_html($urow['district']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(district)%%>', html_attr($row['district']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(district)%%>', urlencode($urow['district']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(road_or_street)%%>', safe_html($urow['road_or_street']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(road_or_street)%%>', html_attr($row['road_or_street']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(road_or_street)%%>', urlencode($urow['road_or_street']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(coordinates)%%>', safe_html($urow['coordinates']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(coordinates)%%>', html_attr($row['coordinates']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(coordinates)%%>', urlencode($urow['coordinates']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(deaths)%%>', safe_html($urow['deaths']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(deaths)%%>', html_attr($row['deaths']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(deaths)%%>', urlencode($urow['deaths']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(fatal_amount)%%>', safe_html($urow['fatal_amount']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(fatal_amount)%%>', html_attr($row['fatal_amount']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(fatal_amount)%%>', urlencode($urow['fatal_amount']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(injured)%%>', safe_html($urow['injured']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(injured)%%>', html_attr($row['injured']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(injured)%%>', urlencode($urow['injured']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(injured_amount)%%>', safe_html($urow['injured_amount']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(injured_amount)%%>', html_attr($row['injured_amount']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(injured_amount)%%>', urlencode($urow['injured_amount']), $templateCode);
		if($AllowUpdate || $AllowInsert) {
			$templateCode = str_replace('<%%HTMLAREA(description_of_accident)%%>', '<textarea name="description_of_accident" id="description_of_accident" rows="5">' . safe_html(htmlspecialchars_decode($row['description_of_accident'])) . '</textarea>', $templateCode);
		} else {
			$templateCode = str_replace('<%%HTMLAREA(description_of_accident)%%>', '<div id="description_of_accident" class="form-control-static">' . $row['description_of_accident'] . '</div>', $templateCode);
		}
		$templateCode = str_replace('<%%VALUE(description_of_accident)%%>', nl2br($row['description_of_accident']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(description_of_accident)%%>', urlencode($urow['description_of_accident']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(insured)%%>', safe_html($urow['insured']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(insured)%%>', html_attr($row['insured']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(insured)%%>', urlencode($urow['insured']), $templateCode);
		$row['upload_photos_damaged_vehicle'] = ($row['upload_photos_damaged_vehicle'] != '' ? $row['upload_photos_damaged_vehicle'] : 'blank.gif');
		if( $dvprint) $templateCode = str_replace('<%%VALUE(upload_photos_damaged_vehicle)%%>', safe_html($urow['upload_photos_damaged_vehicle']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(upload_photos_damaged_vehicle)%%>', html_attr($row['upload_photos_damaged_vehicle']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(upload_photos_damaged_vehicle)%%>', urlencode($urow['upload_photos_damaged_vehicle']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(copy_of_sketch_plan)%%>', safe_html($urow['copy_of_sketch_plan']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(copy_of_sketch_plan)%%>', html_attr($row['copy_of_sketch_plan']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(copy_of_sketch_plan)%%>', urlencode($urow['copy_of_sketch_plan']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(accident_report_driver)%%>', safe_html($urow['accident_report_driver']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(accident_report_driver)%%>', html_attr($row['accident_report_driver']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(accident_report_driver)%%>', urlencode($urow['accident_report_driver']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(accident_report_supervisior)%%>', safe_html($urow['accident_report_supervisior']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(accident_report_supervisior)%%>', html_attr($row['accident_report_supervisior']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(accident_report_supervisior)%%>', urlencode($urow['accident_report_supervisior']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(claims_report_accident_committee)%%>', safe_html($urow['claims_report_accident_committee']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(claims_report_accident_committee)%%>', html_attr($row['claims_report_accident_committee']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(claims_report_accident_committee)%%>', urlencode($urow['claims_report_accident_committee']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(insurance_claims_report)%%>', safe_html($urow['insurance_claims_report']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(insurance_claims_report)%%>', html_attr($row['insurance_claims_report']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(insurance_claims_report)%%>', urlencode($urow['insurance_claims_report']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(amount_paid)%%>', safe_html($urow['amount_paid']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(amount_paid)%%>', html_attr($row['amount_paid']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(amount_paid)%%>', urlencode($urow['amount_paid']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(police_officer)%%>', safe_html($urow['police_officer']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(police_officer)%%>', html_attr($row['police_officer']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(police_officer)%%>', urlencode($urow['police_officer']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(contact_details)%%>', safe_html($urow['contact_details']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(contact_details)%%>', html_attr($row['contact_details']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(contact_details)%%>', urlencode($urow['contact_details']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(case_number)%%>', safe_html($urow['case_number']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(case_number)%%>', html_attr($row['case_number']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(case_number)%%>', urlencode($urow['case_number']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(police_report)%%>', safe_html($urow['police_report']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(police_report)%%>', html_attr($row['police_report']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(police_report)%%>', urlencode($urow['police_report']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(accident_report_number)%%>', safe_html($urow['accident_report_number']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(accident_report_number)%%>', html_attr($row['accident_report_number']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(accident_report_number)%%>', urlencode($urow['accident_report_number']), $templateCode);
	} else {
		$templateCode = str_replace('<%%VALUE(accident_id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(accident_id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(vehicle_registration_number)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(vehicle_registration_number)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(closing_km)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(closing_km)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(drivers_surname)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(drivers_surname)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(date_of_accident)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(date_of_accident)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(z181_accident_form)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(z181_accident_form)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(z181_accident_form_uploaded)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(z181_accident_form_uploaded)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(copy_of_trip_authority)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(copy_of_trip_authority)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(district)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(district)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(road_or_street)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(road_or_street)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(coordinates)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(coordinates)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(deaths)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(deaths)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(fatal_amount)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(fatal_amount)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(injured)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(injured)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(injured_amount)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(injured_amount)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%HTMLAREA(description_of_accident)%%>', '<textarea name="description_of_accident" id="description_of_accident" rows="5"></textarea>', $templateCode);
		$templateCode = str_replace('<%%VALUE(insured)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(insured)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(upload_photos_damaged_vehicle)%%>', 'blank.gif', $templateCode);
		$templateCode = str_replace('<%%VALUE(copy_of_sketch_plan)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(copy_of_sketch_plan)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(accident_report_driver)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(accident_report_driver)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(accident_report_supervisior)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(accident_report_supervisior)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(claims_report_accident_committee)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(claims_report_accident_committee)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(insurance_claims_report)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(insurance_claims_report)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(amount_paid)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(amount_paid)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(police_officer)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(police_officer)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(contact_details)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(contact_details)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(case_number)%%>', 'CAS_', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(case_number)%%>', urlencode('CAS_'), $templateCode);
		$templateCode = str_replace('<%%VALUE(police_report)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(police_report)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(accident_report_number)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(accident_report_number)%%>', urlencode(''), $templateCode);
	}

	// process translations
	$templateCode = parseTemplate($templateCode);

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if(Request::val('dvprint_x') == '') {
		$templateCode .= "\n\n<script>\$j(function() {\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption) {
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id) {
			$templateCode.="\n\tif(document.getElementById('z181_accident_form_uploadedEdit')) { document.getElementById('z181_accident_form_uploadedEdit').style.display='inline'; }";
			$templateCode.="\n\tif(document.getElementById('z181_accident_form_uploadedEditLink')) { document.getElementById('z181_accident_form_uploadedEditLink').style.display='none'; }";
			$templateCode.="\n\tif(document.getElementById('copy_of_trip_authorityEdit')) { document.getElementById('copy_of_trip_authorityEdit').style.display='inline'; }";
			$templateCode.="\n\tif(document.getElementById('copy_of_trip_authorityEditLink')) { document.getElementById('copy_of_trip_authorityEditLink').style.display='none'; }";
			$templateCode.="\n\tif(document.getElementById('copy_of_sketch_planEdit')) { document.getElementById('copy_of_sketch_planEdit').style.display='inline'; }";
			$templateCode.="\n\tif(document.getElementById('copy_of_sketch_planEditLink')) { document.getElementById('copy_of_sketch_planEditLink').style.display='none'; }";
			$templateCode.="\n\tif(document.getElementById('accident_report_driverEdit')) { document.getElementById('accident_report_driverEdit').style.display='inline'; }";
			$templateCode.="\n\tif(document.getElementById('accident_report_driverEditLink')) { document.getElementById('accident_report_driverEditLink').style.display='none'; }";
			$templateCode.="\n\tif(document.getElementById('accident_report_supervisiorEdit')) { document.getElementById('accident_report_supervisiorEdit').style.display='inline'; }";
			$templateCode.="\n\tif(document.getElementById('accident_report_supervisiorEditLink')) { document.getElementById('accident_report_supervisiorEditLink').style.display='none'; }";
			$templateCode.="\n\tif(document.getElementById('claims_report_accident_committeeEdit')) { document.getElementById('claims_report_accident_committeeEdit').style.display='inline'; }";
			$templateCode.="\n\tif(document.getElementById('claims_report_accident_committeeEditLink')) { document.getElementById('claims_report_accident_committeeEditLink').style.display='none'; }";
			$templateCode.="\n\tif(document.getElementById('insurance_claims_reportEdit')) { document.getElementById('insurance_claims_reportEdit').style.display='inline'; }";
			$templateCode.="\n\tif(document.getElementById('insurance_claims_reportEditLink')) { document.getElementById('insurance_claims_reportEditLink').style.display='none'; }";
			$templateCode.="\n\tif(document.getElementById('police_reportEdit')) { document.getElementById('police_reportEdit').style.display='inline'; }";
			$templateCode.="\n\tif(document.getElementById('police_reportEditLink')) { document.getElementById('police_reportEditLink').style.display='none'; }";
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';

	$templateCode .= "\tvehicle_registration_number_update_autofills$rnd1 = function() {\n";
	$templateCode .= "\t\t\$j.ajax({\n";
	if($dvprint) {
		$templateCode .= "\t\t\turl: 'accidents_autofill.php?rnd1=$rnd1&mfk=vehicle_registration_number&id=' + encodeURIComponent('".addslashes($row['vehicle_registration_number'])."'),\n";
		$templateCode .= "\t\t\tcontentType: 'application/x-www-form-urlencoded; charset=" . datalist_db_encoding . "',\n";
		$templateCode .= "\t\t\ttype: 'GET'\n";
	} else {
		$templateCode .= "\t\t\turl: 'accidents_autofill.php?rnd1=$rnd1&mfk=vehicle_registration_number&id=' + encodeURIComponent(AppGini.current_vehicle_registration_number{$rnd1}.value),\n";
		$templateCode .= "\t\t\tcontentType: 'application/x-www-form-urlencoded; charset=" . datalist_db_encoding . "',\n";
		$templateCode .= "\t\t\ttype: 'GET',\n";
		$templateCode .= "\t\t\tbeforeSend: function() { \$j('#vehicle_registration_number$rnd1').prop('disabled', true); },\n";
		$templateCode .= "\t\t\tcomplete: function() { " . (($arrPerm['insert'] || (($arrPerm['edit'] == 1 && $ownerMemberID == getLoggedMemberID()) || ($arrPerm['edit'] == 2 && $ownerGroupID == getLoggedGroupID()) || $arrPerm['edit'] == 3)) ? "\$j('#vehicle_registration_number$rnd1').prop('disabled', false); " : "\$j('#vehicle_registration_number$rnd1').prop('disabled', true); ")." \$j(window).resize(); }\n";
	}
	$templateCode .= "\t\t});\n";
	$templateCode .= "\t};\n";
	if(!$dvprint) $templateCode .= "\tif(\$j('#vehicle_registration_number_caption').length) \$j('#vehicle_registration_number_caption').click(function() { vehicle_registration_number_update_autofills$rnd1(); });\n";

	$templateCode .= "\tdrivers_surname_update_autofills$rnd1 = function() {\n";
	$templateCode .= "\t\t\$j.ajax({\n";
	if($dvprint) {
		$templateCode .= "\t\t\turl: 'accidents_autofill.php?rnd1=$rnd1&mfk=drivers_surname&id=' + encodeURIComponent('".addslashes($row['drivers_surname'])."'),\n";
		$templateCode .= "\t\t\tcontentType: 'application/x-www-form-urlencoded; charset=" . datalist_db_encoding . "',\n";
		$templateCode .= "\t\t\ttype: 'GET'\n";
	} else {
		$templateCode .= "\t\t\turl: 'accidents_autofill.php?rnd1=$rnd1&mfk=drivers_surname&id=' + encodeURIComponent(AppGini.current_drivers_surname{$rnd1}.value),\n";
		$templateCode .= "\t\t\tcontentType: 'application/x-www-form-urlencoded; charset=" . datalist_db_encoding . "',\n";
		$templateCode .= "\t\t\ttype: 'GET',\n";
		$templateCode .= "\t\t\tbeforeSend: function() { \$j('#drivers_surname$rnd1').prop('disabled', true); },\n";
		$templateCode .= "\t\t\tcomplete: function() { " . (($arrPerm['insert'] || (($arrPerm['edit'] == 1 && $ownerMemberID == getLoggedMemberID()) || ($arrPerm['edit'] == 2 && $ownerGroupID == getLoggedGroupID()) || $arrPerm['edit'] == 3)) ? "\$j('#drivers_surname$rnd1').prop('disabled', false); " : "\$j('#drivers_surname$rnd1').prop('disabled', true); ")." \$j(window).resize(); }\n";
	}
	$templateCode .= "\t\t});\n";
	$templateCode .= "\t};\n";
	if(!$dvprint) $templateCode .= "\tif(\$j('#drivers_surname_caption').length) \$j('#drivers_surname_caption').click(function() { drivers_surname_update_autofills$rnd1(); });\n";

	$templateCode .= "\tdistrict_update_autofills$rnd1 = function() {\n";
	$templateCode .= "\t\t\$j.ajax({\n";
	if($dvprint) {
		$templateCode .= "\t\t\turl: 'accidents_autofill.php?rnd1=$rnd1&mfk=district&id=' + encodeURIComponent('".addslashes($row['district'])."'),\n";
		$templateCode .= "\t\t\tcontentType: 'application/x-www-form-urlencoded; charset=" . datalist_db_encoding . "',\n";
		$templateCode .= "\t\t\ttype: 'GET'\n";
	} else {
		$templateCode .= "\t\t\turl: 'accidents_autofill.php?rnd1=$rnd1&mfk=district&id=' + encodeURIComponent(AppGini.current_district{$rnd1}.value),\n";
		$templateCode .= "\t\t\tcontentType: 'application/x-www-form-urlencoded; charset=" . datalist_db_encoding . "',\n";
		$templateCode .= "\t\t\ttype: 'GET',\n";
		$templateCode .= "\t\t\tbeforeSend: function() { \$j('#district$rnd1').prop('disabled', true); },\n";
		$templateCode .= "\t\t\tcomplete: function() { " . (($arrPerm['insert'] || (($arrPerm['edit'] == 1 && $ownerMemberID == getLoggedMemberID()) || ($arrPerm['edit'] == 2 && $ownerGroupID == getLoggedGroupID()) || $arrPerm['edit'] == 3)) ? "\$j('#district$rnd1').prop('disabled', false); " : "\$j('#district$rnd1').prop('disabled', true); ")." \$j(window).resize(); }\n";
	}
	$templateCode .= "\t\t});\n";
	$templateCode .= "\t};\n";
	if(!$dvprint) $templateCode .= "\tif(\$j('#district_caption').length) \$j('#district_caption').click(function() { district_update_autofills$rnd1(); });\n";


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields
	$filterField = Request::val('FilterField');
	$filterOperator = Request::val('FilterOperator');
	$filterValue = Request::val('FilterValue');

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('accidents');
	if($selected_id) {
		$jdata = get_joined_record('accidents', $selected_id);
		if($jdata === false) $jdata = get_defaults('accidents');
		$rdata = $row;
	}
	$templateCode .= loadView('accidents-ajax-cache', ['rdata' => $rdata, 'jdata' => $jdata]);

	// hook: accidents_dv
	if(function_exists('accidents_dv')) {
		$args = [];
		accidents_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}