<?php
// This script and data application were generated by AppGini 22.13
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/claim.php');
	include_once(__DIR__ . '/claim_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('claim');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'claim';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`claim`.`claim_id`" => "claim_id",
		"`claim`.`claim_code`" => "claim_code",
		"IF(    CHAR_LENGTH(`claim_status1`.`claim_status`), CONCAT_WS('',   `claim_status1`.`claim_status`), '') /* Claim Status: */" => "claim_status",
		"IF(    CHAR_LENGTH(`claim_category1`.`claim_category`), CONCAT_WS('',   `claim_category1`.`claim_category`), '') /* Claim Category: */" => "claim_category",
		"IF(    CHAR_LENGTH(`cost_centre1`.`cost_centre`), CONCAT_WS('',   `cost_centre1`.`cost_centre`), '') /* Cost Centre */" => "cost_centre",
		"`claim`.`client_identification`" => "client_identification",
		"IF(    CHAR_LENGTH(`departments1`.`department_name`), CONCAT_WS('',   `departments1`.`department_name`), '') /* Department Name: */" => "department_name",
		"IF(    CHAR_LENGTH(`districts1`.`district`), CONCAT_WS('',   `districts1`.`district`), '') /* District: */" => "district",
		"IF(    CHAR_LENGTH(`province1`.`province`), CONCAT_WS('',   `province1`.`province`), '') /* Province Name: */" => "province",
		"IF(    CHAR_LENGTH(`merchant1`.`merchant_name`) || CHAR_LENGTH(`merchant1`.`merchant_code`), CONCAT_WS('',   `merchant1`.`merchant_name`, '     |   and    |   ', `merchant1`.`merchant_code`), '') /* Merchant Name: */" => "merchant_name",
		"IF(    CHAR_LENGTH(`gmt_fleet_register1`.`vehicle_registration_number`) || CHAR_LENGTH(`gmt_fleet_register1`.`chassis_number`), CONCAT_WS('',   `gmt_fleet_register1`.`vehicle_registration_number`, '    |   and    |  ', `gmt_fleet_register1`.`chassis_number`), '') /* Vehicle Registration Number: */" => "vehicle_registration_number",
		"IF(    CHAR_LENGTH(`gmt_fleet_register1`.`model_of_vehicle`) || CHAR_LENGTH(`gmt_fleet_register1`.`vehicle_registration_number`), CONCAT_WS('',   `gmt_fleet_register1`.`model_of_vehicle`, ' |   and    |    ', `gmt_fleet_register1`.`vehicle_registration_number`), '') /* Model: */" => "model",
		"IF(    CHAR_LENGTH(`log_sheet1`.`closing_km`), CONCAT_WS('',   `log_sheet1`.`closing_km`), '') /* Closing km: */" => "closing_km",
		"DATE_FORMAT(`claim`.`pre_authorization_date`, '%D %b %Y %l:%i%p')" => "pre_authorization_date",
		"`claim`.`instruction_note`" => "instruction_note",
		"DATE_FORMAT(`claim`.`invoice_date`, '%D %b %Y %l:%i%p')" => "invoice_date",
		"`claim`.`upload_invoice`" => "upload_invoice",
		"DATE_FORMAT(`claim`.`payment_date`, '%D %b %Y %l:%i%p')" => "payment_date",
		"`claim`.`authorization_number`" => "authorization_number",
		"`claim`.`clearance_number`" => "clearance_number",
		"DATE_FORMAT(`claim`.`vehicle_collected_date`, '%D %b %Y %l:%i%p')" => "vehicle_collected_date",
		"`claim`.`total_claimed`" => "total_claimed",
		"`claim`.`total_authorized`" => "total_authorized",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`claim`.`claim_id`',
		2 => 2,
		3 => '`claim_status1`.`claim_status`',
		4 => '`claim_category1`.`claim_category`',
		5 => '`cost_centre1`.`cost_centre`',
		6 => 6,
		7 => '`departments1`.`department_name`',
		8 => '`districts1`.`district`',
		9 => '`province1`.`province`',
		10 => 10,
		11 => 11,
		12 => 12,
		13 => '`log_sheet1`.`closing_km`',
		14 => '`claim`.`pre_authorization_date`',
		15 => 15,
		16 => '`claim`.`invoice_date`',
		17 => 17,
		18 => '`claim`.`payment_date`',
		19 => 19,
		20 => 20,
		21 => '`claim`.`vehicle_collected_date`',
		22 => '`claim`.`total_claimed`',
		23 => '`claim`.`total_authorized`',
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`claim`.`claim_id`" => "claim_id",
		"`claim`.`claim_code`" => "claim_code",
		"IF(    CHAR_LENGTH(`claim_status1`.`claim_status`), CONCAT_WS('',   `claim_status1`.`claim_status`), '') /* Claim Status: */" => "claim_status",
		"IF(    CHAR_LENGTH(`claim_category1`.`claim_category`), CONCAT_WS('',   `claim_category1`.`claim_category`), '') /* Claim Category: */" => "claim_category",
		"IF(    CHAR_LENGTH(`cost_centre1`.`cost_centre`), CONCAT_WS('',   `cost_centre1`.`cost_centre`), '') /* Cost Centre */" => "cost_centre",
		"`claim`.`client_identification`" => "client_identification",
		"IF(    CHAR_LENGTH(`departments1`.`department_name`), CONCAT_WS('',   `departments1`.`department_name`), '') /* Department Name: */" => "department_name",
		"IF(    CHAR_LENGTH(`districts1`.`district`), CONCAT_WS('',   `districts1`.`district`), '') /* District: */" => "district",
		"IF(    CHAR_LENGTH(`province1`.`province`), CONCAT_WS('',   `province1`.`province`), '') /* Province Name: */" => "province",
		"IF(    CHAR_LENGTH(`merchant1`.`merchant_name`) || CHAR_LENGTH(`merchant1`.`merchant_code`), CONCAT_WS('',   `merchant1`.`merchant_name`, '     |   and    |   ', `merchant1`.`merchant_code`), '') /* Merchant Name: */" => "merchant_name",
		"IF(    CHAR_LENGTH(`gmt_fleet_register1`.`vehicle_registration_number`) || CHAR_LENGTH(`gmt_fleet_register1`.`chassis_number`), CONCAT_WS('',   `gmt_fleet_register1`.`vehicle_registration_number`, '    |   and    |  ', `gmt_fleet_register1`.`chassis_number`), '') /* Vehicle Registration Number: */" => "vehicle_registration_number",
		"IF(    CHAR_LENGTH(`gmt_fleet_register1`.`model_of_vehicle`) || CHAR_LENGTH(`gmt_fleet_register1`.`vehicle_registration_number`), CONCAT_WS('',   `gmt_fleet_register1`.`model_of_vehicle`, ' |   and    |    ', `gmt_fleet_register1`.`vehicle_registration_number`), '') /* Model: */" => "model",
		"IF(    CHAR_LENGTH(`log_sheet1`.`closing_km`), CONCAT_WS('',   `log_sheet1`.`closing_km`), '') /* Closing km: */" => "closing_km",
		"DATE_FORMAT(`claim`.`pre_authorization_date`, '%D %b %Y %l:%i%p')" => "pre_authorization_date",
		"`claim`.`instruction_note`" => "instruction_note",
		"DATE_FORMAT(`claim`.`invoice_date`, '%D %b %Y %l:%i%p')" => "invoice_date",
		"`claim`.`upload_invoice`" => "upload_invoice",
		"DATE_FORMAT(`claim`.`payment_date`, '%D %b %Y %l:%i%p')" => "payment_date",
		"`claim`.`authorization_number`" => "authorization_number",
		"`claim`.`clearance_number`" => "clearance_number",
		"DATE_FORMAT(`claim`.`vehicle_collected_date`, '%D %b %Y %l:%i%p')" => "vehicle_collected_date",
		"`claim`.`total_claimed`" => "total_claimed",
		"`claim`.`total_authorized`" => "total_authorized",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`claim`.`claim_id`" => "Claim ID:",
		"`claim`.`claim_code`" => "Claims Code:",
		"IF(    CHAR_LENGTH(`claim_status1`.`claim_status`), CONCAT_WS('',   `claim_status1`.`claim_status`), '') /* Claim Status: */" => "Claim Status:",
		"IF(    CHAR_LENGTH(`claim_category1`.`claim_category`), CONCAT_WS('',   `claim_category1`.`claim_category`), '') /* Claim Category: */" => "Claim Category:",
		"IF(    CHAR_LENGTH(`cost_centre1`.`cost_centre`), CONCAT_WS('',   `cost_centre1`.`cost_centre`), '') /* Cost Centre */" => "Cost Centre",
		"`claim`.`client_identification`" => "Client Identification:",
		"IF(    CHAR_LENGTH(`departments1`.`department_name`), CONCAT_WS('',   `departments1`.`department_name`), '') /* Department Name: */" => "Department Name:",
		"IF(    CHAR_LENGTH(`districts1`.`district`), CONCAT_WS('',   `districts1`.`district`), '') /* District: */" => "District:",
		"IF(    CHAR_LENGTH(`province1`.`province`), CONCAT_WS('',   `province1`.`province`), '') /* Province Name: */" => "Province Name:",
		"IF(    CHAR_LENGTH(`merchant1`.`merchant_name`) || CHAR_LENGTH(`merchant1`.`merchant_code`), CONCAT_WS('',   `merchant1`.`merchant_name`, '     |   and    |   ', `merchant1`.`merchant_code`), '') /* Merchant Name: */" => "Merchant Name:",
		"IF(    CHAR_LENGTH(`gmt_fleet_register1`.`vehicle_registration_number`) || CHAR_LENGTH(`gmt_fleet_register1`.`chassis_number`), CONCAT_WS('',   `gmt_fleet_register1`.`vehicle_registration_number`, '    |   and    |  ', `gmt_fleet_register1`.`chassis_number`), '') /* Vehicle Registration Number: */" => "Vehicle Registration Number:",
		"IF(    CHAR_LENGTH(`gmt_fleet_register1`.`model_of_vehicle`) || CHAR_LENGTH(`gmt_fleet_register1`.`vehicle_registration_number`), CONCAT_WS('',   `gmt_fleet_register1`.`model_of_vehicle`, ' |   and    |    ', `gmt_fleet_register1`.`vehicle_registration_number`), '') /* Model: */" => "Model:",
		"IF(    CHAR_LENGTH(`log_sheet1`.`closing_km`), CONCAT_WS('',   `log_sheet1`.`closing_km`), '') /* Closing km: */" => "Closing km:",
		"`claim`.`pre_authorization_date`" => "Pre Authorization Date:",
		"`claim`.`instruction_note`" => "Instruction Note:",
		"`claim`.`invoice_date`" => "Invoice Date:",
		"`claim`.`upload_invoice`" => "Documents (Upload Invoice):",
		"`claim`.`payment_date`" => "Payment Date:",
		"`claim`.`authorization_number`" => "Authorization Number:",
		"`claim`.`clearance_number`" => "Clearance Number:",
		"`claim`.`vehicle_collected_date`" => "Vehicle Collected Date:",
		"`claim`.`total_claimed`" => "Total Claimed (R):",
		"`claim`.`total_authorized`" => "Total Authorized (R):",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`claim`.`claim_id`" => "claim_id",
		"`claim`.`claim_code`" => "claim_code",
		"IF(    CHAR_LENGTH(`claim_status1`.`claim_status`), CONCAT_WS('',   `claim_status1`.`claim_status`), '') /* Claim Status: */" => "claim_status",
		"IF(    CHAR_LENGTH(`claim_category1`.`claim_category`), CONCAT_WS('',   `claim_category1`.`claim_category`), '') /* Claim Category: */" => "claim_category",
		"IF(    CHAR_LENGTH(`cost_centre1`.`cost_centre`), CONCAT_WS('',   `cost_centre1`.`cost_centre`), '') /* Cost Centre */" => "cost_centre",
		"`claim`.`client_identification`" => "client_identification",
		"IF(    CHAR_LENGTH(`departments1`.`department_name`), CONCAT_WS('',   `departments1`.`department_name`), '') /* Department Name: */" => "department_name",
		"IF(    CHAR_LENGTH(`districts1`.`district`), CONCAT_WS('',   `districts1`.`district`), '') /* District: */" => "district",
		"IF(    CHAR_LENGTH(`province1`.`province`), CONCAT_WS('',   `province1`.`province`), '') /* Province Name: */" => "province",
		"IF(    CHAR_LENGTH(`merchant1`.`merchant_name`) || CHAR_LENGTH(`merchant1`.`merchant_code`), CONCAT_WS('',   `merchant1`.`merchant_name`, '     |   and    |   ', `merchant1`.`merchant_code`), '') /* Merchant Name: */" => "merchant_name",
		"IF(    CHAR_LENGTH(`gmt_fleet_register1`.`vehicle_registration_number`) || CHAR_LENGTH(`gmt_fleet_register1`.`chassis_number`), CONCAT_WS('',   `gmt_fleet_register1`.`vehicle_registration_number`, '    |   and    |  ', `gmt_fleet_register1`.`chassis_number`), '') /* Vehicle Registration Number: */" => "vehicle_registration_number",
		"IF(    CHAR_LENGTH(`gmt_fleet_register1`.`model_of_vehicle`) || CHAR_LENGTH(`gmt_fleet_register1`.`vehicle_registration_number`), CONCAT_WS('',   `gmt_fleet_register1`.`model_of_vehicle`, ' |   and    |    ', `gmt_fleet_register1`.`vehicle_registration_number`), '') /* Model: */" => "model",
		"IF(    CHAR_LENGTH(`log_sheet1`.`closing_km`), CONCAT_WS('',   `log_sheet1`.`closing_km`), '') /* Closing km: */" => "closing_km",
		"DATE_FORMAT(`claim`.`pre_authorization_date`, '%D %b %Y %l:%i%p')" => "pre_authorization_date",
		"`claim`.`instruction_note`" => "instruction_note",
		"DATE_FORMAT(`claim`.`invoice_date`, '%D %b %Y %l:%i%p')" => "invoice_date",
		"`claim`.`upload_invoice`" => "upload_invoice",
		"DATE_FORMAT(`claim`.`payment_date`, '%D %b %Y %l:%i%p')" => "payment_date",
		"`claim`.`authorization_number`" => "authorization_number",
		"`claim`.`clearance_number`" => "clearance_number",
		"DATE_FORMAT(`claim`.`vehicle_collected_date`, '%D %b %Y %l:%i%p')" => "vehicle_collected_date",
		"`claim`.`total_claimed`" => "total_claimed",
		"`claim`.`total_authorized`" => "total_authorized",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = ['claim_status' => 'Claim Status:', 'claim_category' => 'Claim Category:', 'cost_centre' => 'Cost Centre', 'department_name' => 'Department Name:', 'district' => 'District:', 'province' => 'Province Name:', 'merchant_name' => 'Merchant Name:', 'vehicle_registration_number' => 'Vehicle Registration Number:', 'closing_km' => 'Closing km:', ];

	$x->QueryFrom = "`claim` LEFT JOIN `claim_status` as claim_status1 ON `claim_status1`.`claim_status_id`=`claim`.`claim_status` LEFT JOIN `claim_category` as claim_category1 ON `claim_category1`.`claim_category_id`=`claim`.`claim_category` LEFT JOIN `cost_centre` as cost_centre1 ON `cost_centre1`.`cost_centre_id`=`claim`.`cost_centre` LEFT JOIN `departments` as departments1 ON `departments1`.`department_id`=`claim`.`department_name` LEFT JOIN `districts` as districts1 ON `districts1`.`district_id`=`claim`.`district` LEFT JOIN `province` as province1 ON `province1`.`province_id`=`claim`.`province` LEFT JOIN `merchant` as merchant1 ON `merchant1`.`merchant_id`=`claim`.`merchant_name` LEFT JOIN `gmt_fleet_register` as gmt_fleet_register1 ON `gmt_fleet_register1`.`fleet_asset_id`=`claim`.`vehicle_registration_number` LEFT JOIN `log_sheet` as log_sheet1 ON `log_sheet1`.`fuel_log_sheet_id`=`claim`.`closing_km` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 25;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'claim_view.php';
	$x->RedirectAfterInsert = 'claim_view.php?SelectedID=#ID#';
	$x->TableTitle = 'Claims:';
	$x->TableIcon = 'resources/table_icons/BiologicalHazard_Symbol_Triangle.png';
	$x->PrimaryKey = '`claim`.`claim_id`';

	$x->ColWidth = [150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, ];
	$x->ColCaption = ['Claim ID:', 'Claims Code:', 'Claim Status:', 'Claim Category:', 'Cost Centre', 'Client Identification:', 'Department Name:', 'District:', 'Province Name:', 'Merchant Name:', 'Vehicle Registration Number:', 'Model:', 'Closing km:', 'Pre Authorization Date:', 'Instruction Note:', 'Invoice Date:', 'Documents (Upload Invoice):', 'Payment Date:', 'Authorization Number:', 'Clearance Number:', 'Vehicle Collected Date:', 'Total Claimed (R):', 'Total Authorized (R):', ];
	$x->ColFieldName = ['claim_id', 'claim_code', 'claim_status', 'claim_category', 'cost_centre', 'client_identification', 'department_name', 'district', 'province', 'merchant_name', 'vehicle_registration_number', 'model', 'closing_km', 'pre_authorization_date', 'instruction_note', 'invoice_date', 'upload_invoice', 'payment_date', 'authorization_number', 'clearance_number', 'vehicle_collected_date', 'total_claimed', 'total_authorized', ];
	$x->ColNumber  = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/claim_templateTV.html';
	$x->SelectedTemplate = 'templates/claim_templateTVS.html';
	$x->TemplateDV = 'templates/claim_templateDV.html';
	$x->TemplateDVP = 'templates/claim_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: claim_init
	$render = true;
	if(function_exists('claim_init')) {
		$args = [];
		$render = claim_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: claim_header
	$headerCode = '';
	if(function_exists('claim_header')) {
		$args = [];
		$headerCode = claim_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: claim_footer
	$footerCode = '';
	if(function_exists('claim_footer')) {
		$args = [];
		$footerCode = claim_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
