<?php
	$dbServer = '127.0.0.1';
	$dbUsername = 'root';
	$dbPassword = 'tRagel0pus2022';
	$dbDatabase = 'ldtcsgmtfleet2022new';
	$appURI = 'ldtcsgmtfleet';
	$host = 'localhost';

	$adminConfig = [
		'adminUsername' => "whoami",
		'adminPassword' => "\$2y\$10\$HB2wVj/2BopLTGaVpqz9N.hmQ5mmT6ccnS1RYrRFTa4rm2KRFQg7u",
		'notifyAdminNewMembers' => "0",
		'defaultSignUp' => "1",
		'anonymousGroup' => "anonymous",
		'anonymousMember' => "guest",
		'groupsPerPage' => "50",
		'membersPerPage' => "50",
		'recordsPerPage' => "50",
		'custom1' => "Full Name",
		'custom2' => "Address",
		'custom3' => "City",
		'custom4' => "State",
		'MySQLDateFormat' => "%d/%m/%Y",
		'PHPDateFormat' => "j/n/Y",
		'PHPDateTimeFormat' => "d/m/Y, h:i a",
		'senderName' => "Membership management",
		'senderEmail' => "82080097@dtcs.limpopo.gov.za",
		'approvalSubject' => "Your membership is now approved",
		'approvalMessage' => "Dear member,\r\n\r\nYour membership is now approved by the admin. You can log in to your account here:\r\nhttp://localhost/ldtcsgmtfleet\r\n\r\nRegards,\r\nAdmin",
		'hide_twitter_feed' => "1",
		'maintenance_mode_message' => "<b>Our website is currently down for maintenance</b><br>\r\nWe expect to be back in a couple hours. Thanks for your patience.",
		'mail_function' => "mail",
		'smtp_server' => "",
		'smtp_encryption' => "",
		'smtp_port' => "25",
		'smtp_user' => "",
		'smtp_pass' => "",
		'googleAPIKey' => "",
		'baseUploadPath' => "images",
	];