<?php

// Data functions (insert, update, delete, form) for table inspection_bay

// This script and data application were generated by AppGini 22.13
// Download AppGini for free from https://bigprof.com/appgini/download/

function inspection_bay_insert(&$error_message = '') {
	global $Translation;

	// mm: can member insert record?
	$arrPerm = getTablePermissions('inspection_bay');
	if(!$arrPerm['insert']) return false;

	$data = [
		'inspection_bay_supervisor_name_and_surname' => Request::val('inspection_bay_supervisor_name_and_surname', ''),
		'supervisor_contact_details' => Request::val('supervisor_contact_details', ''),
		'supervisor_email_address' => Request::val('supervisor_email_address', ''),
		'supervisor_signature' => Request::fileUpload('supervisor_signature', [
			'maxSize' => 512000,
			'types' => 'jpg|jpeg|gif|png|webp',
			'noRename' => false,
			'dir' => '',
			'success' => function($name, $selected_id) {
				createThumbnail($name, getThumbnailSpecs('inspection_bay', 'supervisor_signature', 'tv'));
				createThumbnail($name, getThumbnailSpecs('inspection_bay', 'supervisor_signature', 'dv'));
			},
			'failure' => function($selected_id, $fileRemoved) {
				if(!strlen(Request::val('SelectedID'))) return '';

				/* for empty upload fields, when saving a copy of an existing record, copy the original upload field */
				return existing_value('inspection_bay', 'supervisor_signature', Request::val('SelectedID'));
			},
		]),
		'date_of_vehicle_entrance' => mysql_datetime(Request::val('date_of_vehicle_entrance', '')),
		'job_card_number' => Request::lookup('job_card_number', ''),
		'vehicle_registration_number' => Request::lookup('vehicle_registration_number', ''),
		'engine_number' => Request::lookup('vehicle_registration_number'),
		'workshop_name' => Request::lookup('job_card_number'),
		'work_allocation_reference_number' => Request::lookup('work_allocation_reference_number', ''),
		'make_of_vehicle' => Request::lookup('vehicle_registration_number'),
		'inspection_bay_lane_number' => Request::val('inspection_bay_lane_number', ''),
		'inspection_bay_condition' => Request::val('inspection_bay_condition', ''),
		'allocation_feedback' => Request::val('allocation_feedback', ''),
		'verification_of_defects' => Request::val('verification_of_defects', ''),
		'additional_defects' => br2nl(Request::val('additional_defects', '')),
		'additional_defects_record' => Request::fileUpload('additional_defects_record', [
			'maxSize' => 102400,
			'types' => 'txt|doc|docx|docm|odt|pdf|rtf',
			'noRename' => true,
			'dir' => '',
			'success' => function($name, $selected_id) {
			},
			'failure' => function($selected_id, $fileRemoved) {
				if(!strlen(Request::val('SelectedID'))) return '';

				/* for empty upload fields, when saving a copy of an existing record, copy the original upload field */
				return existing_value('inspection_bay', 'additional_defects_record', Request::val('SelectedID'));
			},
		]),
		'repair_requirement_note' => br2nl(Request::val('repair_requirement_note', '')),
		'repair_requirement_report' => Request::fileUpload('repair_requirement_report', [
			'maxSize' => 5242880,
			'types' => 'txt|doc|docx|docm|odt|pdf|rtf',
			'noRename' => true,
			'dir' => '',
			'success' => function($name, $selected_id) {
			},
			'failure' => function($selected_id, $fileRemoved) {
				if(!strlen(Request::val('SelectedID'))) return '';

				/* for empty upload fields, when saving a copy of an existing record, copy the original upload field */
				return existing_value('inspection_bay', 'repair_requirement_report', Request::val('SelectedID'));
			},
		]),
		'date_of_vehicle_exit' => mysql_datetime(Request::val('date_of_vehicle_exit', '')),
	];


	// hook: inspection_bay_before_insert
	if(function_exists('inspection_bay_before_insert')) {
		$args = [];
		if(!inspection_bay_before_insert($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$error = '';
	// set empty fields to NULL
	$data = array_map(function($v) { return ($v === '' ? NULL : $v); }, $data);
	insert('inspection_bay', backtick_keys_once($data), $error);
	if($error) {
		$error_message = $error;
		return false;
	}

	$recID = db_insert_id(db_link());

	update_calc_fields('inspection_bay', $recID, calculated_fields()['inspection_bay']);

	// hook: inspection_bay_after_insert
	if(function_exists('inspection_bay_after_insert')) {
		$res = sql("SELECT * FROM `inspection_bay` WHERE `inspection_bay_id`='" . makeSafe($recID, false) . "' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) {
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args = [];
		if(!inspection_bay_after_insert($data, getMemberInfo(), $args)) { return $recID; }
	}

	// mm: save ownership data
	set_record_owner('inspection_bay', $recID, getLoggedMemberID());

	// if this record is a copy of another record, copy children if applicable
	if(strlen(Request::val('SelectedID'))) inspection_bay_copy_children($recID, Request::val('SelectedID'));

	return $recID;
}

function inspection_bay_copy_children($destination_id, $source_id) {
	global $Translation;
	$requests = []; // array of curl handlers for launching insert requests
	$eo = ['silentErrors' => true];
	$safe_sid = makeSafe($source_id);

	// launch requests, asynchronously
	curl_batch($requests);
}

function inspection_bay_delete($selected_id, $AllowDeleteOfParents = false, $skipChecks = false) {
	// insure referential integrity ...
	global $Translation;
	$selected_id = makeSafe($selected_id);

	// mm: can member delete record?
	if(!check_record_permission('inspection_bay', $selected_id, 'delete')) {
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: inspection_bay_before_delete
	if(function_exists('inspection_bay_before_delete')) {
		$args = [];
		if(!inspection_bay_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'] . (
				!empty($args['error_message']) ?
					'<div class="text-bold">' . strip_tags($args['error_message']) . '</div>'
					: '' 
			);
	}

	// child table: internal_repairs_mechanical
	$res = sql("SELECT `inspection_bay_id` FROM `inspection_bay` WHERE `inspection_bay_id`='{$selected_id}'", $eo);
	$inspection_bay_id = db_fetch_row($res);
	$rires = sql("SELECT COUNT(1) FROM `internal_repairs_mechanical` WHERE `inspection_bay_lane_number`='" . makeSafe($inspection_bay_id[0]) . "'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'internal_repairs_mechanical', $RetMsg);
		return $RetMsg;
	} elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation['confirm delete'];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'internal_repairs_mechanical', $RetMsg);
		$RetMsg = str_replace('<Delete>', '<input type="button" class="btn btn-danger" value="' . html_attr($Translation['yes']) . '" onClick="window.location = \'inspection_bay_view.php?SelectedID=' . urlencode($selected_id) . '&delete_x=1&confirmed=1&csrf_token=' . urlencode(csrf_token(false, true)) . '\';">', $RetMsg);
		$RetMsg = str_replace('<Cancel>', '<input type="button" class="btn btn-success" value="' . html_attr($Translation[ 'no']) . '" onClick="window.location = \'inspection_bay_view.php?SelectedID=' . urlencode($selected_id) . '\';">', $RetMsg);
		return $RetMsg;
	}

	sql("DELETE FROM `inspection_bay` WHERE `inspection_bay_id`='{$selected_id}'", $eo);

	// hook: inspection_bay_after_delete
	if(function_exists('inspection_bay_after_delete')) {
		$args = [];
		inspection_bay_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("DELETE FROM `membership_userrecords` WHERE `tableName`='inspection_bay' AND `pkValue`='{$selected_id}'", $eo);
}

function inspection_bay_update(&$selected_id, &$error_message = '') {
	global $Translation;

	// mm: can member edit record?
	if(!check_record_permission('inspection_bay', $selected_id, 'edit')) return false;

	$data = [
		'inspection_bay_supervisor_name_and_surname' => Request::val('inspection_bay_supervisor_name_and_surname', ''),
		'supervisor_contact_details' => Request::val('supervisor_contact_details', ''),
		'supervisor_email_address' => Request::val('supervisor_email_address', ''),
		'supervisor_signature' => Request::fileUpload('supervisor_signature', [
			'maxSize' => 512000,
			'types' => 'jpg|jpeg|gif|png|webp',
			'noRename' => false,
			'dir' => '',
			'id' => $selected_id,
			'success' => function($name, $selected_id) {
				createThumbnail($name, getThumbnailSpecs('inspection_bay', 'supervisor_signature', 'tv'));
				createThumbnail($name, getThumbnailSpecs('inspection_bay', 'supervisor_signature', 'dv'));
			},
			'removeOnRequest' => true,
			'remove' => function($selected_id) {
				// do nothing: preserve removed files on server.
			},
			'failure' => function($selected_id, $fileRemoved) {
				if($fileRemoved) return '';
				return existing_value('inspection_bay', 'supervisor_signature', $selected_id);
			},
		]),
		'date_of_vehicle_entrance' => mysql_datetime(Request::val('date_of_vehicle_entrance', '')),
		'job_card_number' => Request::lookup('job_card_number', ''),
		'vehicle_registration_number' => Request::lookup('vehicle_registration_number', ''),
		'engine_number' => Request::lookup('vehicle_registration_number'),
		'workshop_name' => Request::lookup('job_card_number'),
		'work_allocation_reference_number' => Request::lookup('work_allocation_reference_number', ''),
		'make_of_vehicle' => Request::lookup('vehicle_registration_number'),
		'inspection_bay_lane_number' => Request::val('inspection_bay_lane_number', ''),
		'inspection_bay_condition' => Request::val('inspection_bay_condition', ''),
		'allocation_feedback' => Request::val('allocation_feedback', ''),
		'verification_of_defects' => Request::val('verification_of_defects', ''),
		'additional_defects' => br2nl(Request::val('additional_defects', '')),
		'additional_defects_record' => Request::fileUpload('additional_defects_record', [
			'maxSize' => 102400,
			'types' => 'txt|doc|docx|docm|odt|pdf|rtf',
			'noRename' => true,
			'dir' => '',
			'id' => $selected_id,
			'success' => function($name, $selected_id) {
			},
			'removeOnRequest' => true,
			'remove' => function($selected_id) {
				// do nothing: preserve removed files on server.
			},
			'failure' => function($selected_id, $fileRemoved) {
				if($fileRemoved) return '';
				return existing_value('inspection_bay', 'additional_defects_record', $selected_id);
			},
		]),
		'repair_requirement_note' => br2nl(Request::val('repair_requirement_note', '')),
		'repair_requirement_report' => Request::fileUpload('repair_requirement_report', [
			'maxSize' => 5242880,
			'types' => 'txt|doc|docx|docm|odt|pdf|rtf',
			'noRename' => true,
			'dir' => '',
			'id' => $selected_id,
			'success' => function($name, $selected_id) {
			},
			'removeOnRequest' => true,
			'remove' => function($selected_id) {
				// do nothing: preserve removed files on server.
			},
			'failure' => function($selected_id, $fileRemoved) {
				if($fileRemoved) return '';
				return existing_value('inspection_bay', 'repair_requirement_report', $selected_id);
			},
		]),
		'date_of_vehicle_exit' => mysql_datetime(Request::val('date_of_vehicle_exit', '')),
	];

	// get existing values
	$old_data = getRecord('inspection_bay', $selected_id);
	if(is_array($old_data)) {
		$old_data = array_map('makeSafe', $old_data);
		$old_data['selectedID'] = makeSafe($selected_id);
	}

	$data['selectedID'] = makeSafe($selected_id);

	// hook: inspection_bay_before_update
	if(function_exists('inspection_bay_before_update')) {
		$args = ['old_data' => $old_data];
		if(!inspection_bay_before_update($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$set = $data; unset($set['selectedID']);
	foreach ($set as $field => $value) {
		$set[$field] = ($value !== '' && $value !== NULL) ? $value : NULL;
	}

	if(!update(
		'inspection_bay', 
		backtick_keys_once($set), 
		['`inspection_bay_id`' => $selected_id], 
		$error_message
	)) {
		echo $error_message;
		echo '<a href="inspection_bay_view.php?SelectedID=' . urlencode($selected_id) . "\">{$Translation['< back']}</a>";
		exit;
	}


	$eo = ['silentErrors' => true];

	update_calc_fields('inspection_bay', $data['selectedID'], calculated_fields()['inspection_bay']);

	// hook: inspection_bay_after_update
	if(function_exists('inspection_bay_after_update')) {
		$res = sql("SELECT * FROM `inspection_bay` WHERE `inspection_bay_id`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) $data = array_map('makeSafe', $row);

		$data['selectedID'] = $data['inspection_bay_id'];
		$args = ['old_data' => $old_data];
		if(!inspection_bay_after_update($data, getMemberInfo(), $args)) return;
	}

	// mm: update ownership data
	sql("UPDATE `membership_userrecords` SET `dateUpdated`='" . time() . "' WHERE `tableName`='inspection_bay' AND `pkValue`='" . makeSafe($selected_id) . "'", $eo);
}

function inspection_bay_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $separateDV = 0, $TemplateDV = '', $TemplateDVP = '') {
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;
	$eo = ['silentErrors' => true];
	$noUploads = null;
	$row = $urow = $jsReadOnly = $jsEditable = $lookups = null;

	$noSaveAsCopy = true;

	// mm: get table permissions
	$arrPerm = getTablePermissions('inspection_bay');
	if(!$arrPerm['insert'] && $selected_id == '')
		// no insert permission and no record selected
		// so show access denied error unless TVDV
		return $separateDV ? $Translation['tableAccessDenied'] : '';
	$AllowInsert = ($arrPerm['insert'] ? true : false);
	// print preview?
	$dvprint = false;
	if(strlen($selected_id) && Request::val('dvprint_x') != '') {
		$dvprint = true;
	}

	$filterer_job_card_number = Request::val('filterer_job_card_number');
	$filterer_vehicle_registration_number = Request::val('filterer_vehicle_registration_number');
	$filterer_work_allocation_reference_number = Request::val('filterer_work_allocation_reference_number');

	// populate filterers, starting from children to grand-parents
	if($filterer_job_card_number && !$filterer_vehicle_registration_number) $filterer_vehicle_registration_number = sqlValue("select vehicle_registration_number from reception where reception_user_id='" . makeSafe($filterer_job_card_number) . "'");
	if($filterer_work_allocation_reference_number && !$filterer_vehicle_registration_number) $filterer_vehicle_registration_number = sqlValue("select vehicle_registration_number from work_allocation where work_allocation_id='" . makeSafe($filterer_work_allocation_reference_number) . "'");

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: job_card_number, filterable by: vehicle_registration_number
	$combo_job_card_number = new DataCombo;
	// combobox: vehicle_registration_number
	$combo_vehicle_registration_number = new DataCombo;
	// combobox: work_allocation_reference_number, filterable by: vehicle_registration_number
	$combo_work_allocation_reference_number = new DataCombo;
	// combobox: inspection_bay_condition
	$combo_inspection_bay_condition = new Combo;
	$combo_inspection_bay_condition->ListType = 0;
	$combo_inspection_bay_condition->MultipleSeparator = ', ';
	$combo_inspection_bay_condition->ListBoxHeight = 10;
	$combo_inspection_bay_condition->RadiosPerLine = 1;
	if(is_file(__DIR__ . '/hooks/inspection_bay.inspection_bay_condition.csv')) {
		$inspection_bay_condition_data = addslashes(implode('', @file(__DIR__ . '/hooks/inspection_bay.inspection_bay_condition.csv')));
		$combo_inspection_bay_condition->ListItem = array_trim(explode('||', entitiesToUTF8(convertLegacyOptions($inspection_bay_condition_data))));
		$combo_inspection_bay_condition->ListData = $combo_inspection_bay_condition->ListItem;
	} else {
		$combo_inspection_bay_condition->ListItem = array_trim(explode('||', entitiesToUTF8(convertLegacyOptions("Excellent;;Good;;Moderate;;Poor;;Need Attention"))));
		$combo_inspection_bay_condition->ListData = $combo_inspection_bay_condition->ListItem;
	}
	$combo_inspection_bay_condition->SelectName = 'inspection_bay_condition';

	if($selected_id) {
		// mm: check member permissions
		if(!$arrPerm['view']) return $Translation['tableAccessDenied'];

		// mm: who is the owner?
		$ownerGroupID = sqlValue("SELECT `groupID` FROM `membership_userrecords` WHERE `tableName`='inspection_bay' AND `pkValue`='" . makeSafe($selected_id) . "'");
		$ownerMemberID = sqlValue("SELECT LCASE(`memberID`) FROM `membership_userrecords` WHERE `tableName`='inspection_bay' AND `pkValue`='" . makeSafe($selected_id) . "'");

		if($arrPerm['view'] == 1 && getLoggedMemberID() != $ownerMemberID) return $Translation['tableAccessDenied'];
		if($arrPerm['view'] == 2 && getLoggedGroupID() != $ownerGroupID) return $Translation['tableAccessDenied'];

		// can edit?
		$AllowUpdate = 0;
		if(($arrPerm['edit'] == 1 && $ownerMemberID == getLoggedMemberID()) || ($arrPerm['edit'] == 2 && $ownerGroupID == getLoggedGroupID()) || $arrPerm['edit'] == 3) {
			$AllowUpdate = 1;
		}

		$res = sql("SELECT * FROM `inspection_bay` WHERE `inspection_bay_id`='" . makeSafe($selected_id) . "'", $eo);
		if(!($row = db_fetch_array($res))) {
			return error_message($Translation['No records found'], 'inspection_bay_view.php', false);
		}
		$combo_job_card_number->SelectedData = $row['job_card_number'];
		$combo_vehicle_registration_number->SelectedData = $row['vehicle_registration_number'];
		$combo_work_allocation_reference_number->SelectedData = $row['work_allocation_reference_number'];
		$combo_inspection_bay_condition->SelectedData = $row['inspection_bay_condition'];
		$urow = $row; /* unsanitized data */
		$row = array_map('safe_html', $row);
	} else {
		$filterField = Request::val('FilterField');
		$filterOperator = Request::val('FilterOperator');
		$filterValue = Request::val('FilterValue');
		$combo_job_card_number->SelectedData = $filterer_job_card_number;
		$combo_vehicle_registration_number->SelectedData = $filterer_vehicle_registration_number;
		$combo_work_allocation_reference_number->SelectedData = $filterer_work_allocation_reference_number;
		$combo_inspection_bay_condition->SelectedText = (isset($filterField[1]) && $filterField[1] == '14' && $filterOperator[1] == '<=>' ? $filterValue[1] : '');
	}
	$combo_job_card_number->HTML = '<span id="job_card_number-container' . $rnd1 . '"></span><input type="hidden" name="job_card_number" id="job_card_number' . $rnd1 . '" value="' . html_attr($combo_job_card_number->SelectedData) . '">';
	$combo_job_card_number->MatchText = '<span id="job_card_number-container-readonly' . $rnd1 . '"></span><input type="hidden" name="job_card_number" id="job_card_number' . $rnd1 . '" value="' . html_attr($combo_job_card_number->SelectedData) . '">';
	$combo_vehicle_registration_number->HTML = '<span id="vehicle_registration_number-container' . $rnd1 . '"></span><input type="hidden" name="vehicle_registration_number" id="vehicle_registration_number' . $rnd1 . '" value="' . html_attr($combo_vehicle_registration_number->SelectedData) . '">';
	$combo_vehicle_registration_number->MatchText = '<span id="vehicle_registration_number-container-readonly' . $rnd1 . '"></span><input type="hidden" name="vehicle_registration_number" id="vehicle_registration_number' . $rnd1 . '" value="' . html_attr($combo_vehicle_registration_number->SelectedData) . '">';
	$combo_work_allocation_reference_number->HTML = '<span id="work_allocation_reference_number-container' . $rnd1 . '"></span><input type="hidden" name="work_allocation_reference_number" id="work_allocation_reference_number' . $rnd1 . '" value="' . html_attr($combo_work_allocation_reference_number->SelectedData) . '">';
	$combo_work_allocation_reference_number->MatchText = '<span id="work_allocation_reference_number-container-readonly' . $rnd1 . '"></span><input type="hidden" name="work_allocation_reference_number" id="work_allocation_reference_number' . $rnd1 . '" value="' . html_attr($combo_work_allocation_reference_number->SelectedData) . '">';
	$combo_inspection_bay_condition->Render();

	ob_start();
	?>

	<script>
		// initial lookup values
		AppGini.current_job_card_number__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['job_card_number'] : htmlspecialchars($filterer_job_card_number, ENT_QUOTES)); ?>"};
		AppGini.current_vehicle_registration_number__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['vehicle_registration_number'] : htmlspecialchars($filterer_vehicle_registration_number, ENT_QUOTES)); ?>"};
		AppGini.current_work_allocation_reference_number__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['work_allocation_reference_number'] : htmlspecialchars($filterer_work_allocation_reference_number, ENT_QUOTES)); ?>"};

		jQuery(function() {
			setTimeout(function() {
				<?php echo (!$AllowUpdate || $dvprint ? 'if(typeof(job_card_number_reload__RAND__) == \'function\') job_card_number_reload__RAND__(AppGini.current_vehicle_registration_number__RAND__.value);' : ''); ?>
				if(typeof(vehicle_registration_number_reload__RAND__) == 'function') vehicle_registration_number_reload__RAND__();
				<?php echo (!$AllowUpdate || $dvprint ? 'if(typeof(work_allocation_reference_number_reload__RAND__) == \'function\') work_allocation_reference_number_reload__RAND__(AppGini.current_vehicle_registration_number__RAND__.value);' : ''); ?>
			}, 50); /* we need to slightly delay client-side execution of the above code to allow AppGini.ajaxCache to work */
		});
		function job_card_number_reload__RAND__(filterer_vehicle_registration_number) {
		<?php if(($AllowUpdate || ($arrPerm['insert'] && !$selected_id)) && !$dvprint) { ?>

			$j("#job_card_number-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { filterer_vehicle_registration_number: filterer_vehicle_registration_number, id: AppGini.current_job_card_number__RAND__.value, t: 'inspection_bay', f: 'job_card_number' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="job_card_number"]').val(resp.results[0].id);
							$j('[id=job_card_number-container-readonly__RAND__]').html('<span class="match-text" id="job_card_number-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=reception_view_parent]').hide(); } else { $j('.btn[id=reception_view_parent]').show(); }


							if(typeof(job_card_number_update_autofills__RAND__) == 'function') job_card_number_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { filterer_vehicle_registration_number: filterer_vehicle_registration_number, s: term, p: page, t: 'inspection_bay', f: 'job_card_number' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_job_card_number__RAND__.value = e.added.id;
				AppGini.current_job_card_number__RAND__.text = e.added.text;
				$j('[name="job_card_number"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=reception_view_parent]').hide(); } else { $j('.btn[id=reception_view_parent]').show(); }


				if(typeof(job_card_number_update_autofills__RAND__) == 'function') job_card_number_update_autofills__RAND__();
			});

			if(!$j("#job_card_number-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_job_card_number__RAND__.value, t: 'inspection_bay', f: 'job_card_number' },
					success: function(resp) {
						$j('[name="job_card_number"]').val(resp.results[0].id);
						$j('[id=job_card_number-container-readonly__RAND__]').html('<span class="match-text" id="job_card_number-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=reception_view_parent]').hide(); } else { $j('.btn[id=reception_view_parent]').show(); }

						if(typeof(job_card_number_update_autofills__RAND__) == 'function') job_card_number_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_job_card_number__RAND__.value, t: 'inspection_bay', f: 'job_card_number' },
				success: function(resp) {
					$j('[id=job_card_number-container__RAND__], [id=job_card_number-container-readonly__RAND__]').html('<span class="match-text" id="job_card_number-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=reception_view_parent]').hide(); } else { $j('.btn[id=reception_view_parent]').show(); }

					if(typeof(job_card_number_update_autofills__RAND__) == 'function') job_card_number_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function vehicle_registration_number_reload__RAND__() {
		<?php if(($AllowUpdate || ($arrPerm['insert'] && !$selected_id)) && !$dvprint) { ?>

			$j("#vehicle_registration_number-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_vehicle_registration_number__RAND__.value, t: 'inspection_bay', f: 'vehicle_registration_number' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="vehicle_registration_number"]').val(resp.results[0].id);
							$j('[id=vehicle_registration_number-container-readonly__RAND__]').html('<span class="match-text" id="vehicle_registration_number-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=gmt_fleet_register_view_parent]').hide(); } else { $j('.btn[id=gmt_fleet_register_view_parent]').show(); }

						if(typeof(job_card_number_reload__RAND__) == 'function') job_card_number_reload__RAND__(AppGini.current_vehicle_registration_number__RAND__.value);
						if(typeof(work_allocation_reference_number_reload__RAND__) == 'function') work_allocation_reference_number_reload__RAND__(AppGini.current_vehicle_registration_number__RAND__.value);

							if(typeof(vehicle_registration_number_update_autofills__RAND__) == 'function') vehicle_registration_number_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'inspection_bay', f: 'vehicle_registration_number' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_vehicle_registration_number__RAND__.value = e.added.id;
				AppGini.current_vehicle_registration_number__RAND__.text = e.added.text;
				$j('[name="vehicle_registration_number"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=gmt_fleet_register_view_parent]').hide(); } else { $j('.btn[id=gmt_fleet_register_view_parent]').show(); }

						if(typeof(job_card_number_reload__RAND__) == 'function') job_card_number_reload__RAND__(AppGini.current_vehicle_registration_number__RAND__.value);
						if(typeof(work_allocation_reference_number_reload__RAND__) == 'function') work_allocation_reference_number_reload__RAND__(AppGini.current_vehicle_registration_number__RAND__.value);

				if(typeof(vehicle_registration_number_update_autofills__RAND__) == 'function') vehicle_registration_number_update_autofills__RAND__();
			});

			if(!$j("#vehicle_registration_number-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_vehicle_registration_number__RAND__.value, t: 'inspection_bay', f: 'vehicle_registration_number' },
					success: function(resp) {
						$j('[name="vehicle_registration_number"]').val(resp.results[0].id);
						$j('[id=vehicle_registration_number-container-readonly__RAND__]').html('<span class="match-text" id="vehicle_registration_number-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=gmt_fleet_register_view_parent]').hide(); } else { $j('.btn[id=gmt_fleet_register_view_parent]').show(); }

						if(typeof(vehicle_registration_number_update_autofills__RAND__) == 'function') vehicle_registration_number_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_vehicle_registration_number__RAND__.value, t: 'inspection_bay', f: 'vehicle_registration_number' },
				success: function(resp) {
					$j('[id=vehicle_registration_number-container__RAND__], [id=vehicle_registration_number-container-readonly__RAND__]').html('<span class="match-text" id="vehicle_registration_number-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=gmt_fleet_register_view_parent]').hide(); } else { $j('.btn[id=gmt_fleet_register_view_parent]').show(); }

					if(typeof(vehicle_registration_number_update_autofills__RAND__) == 'function') vehicle_registration_number_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function work_allocation_reference_number_reload__RAND__(filterer_vehicle_registration_number) {
		<?php if(($AllowUpdate || ($arrPerm['insert'] && !$selected_id)) && !$dvprint) { ?>

			$j("#work_allocation_reference_number-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { filterer_vehicle_registration_number: filterer_vehicle_registration_number, id: AppGini.current_work_allocation_reference_number__RAND__.value, t: 'inspection_bay', f: 'work_allocation_reference_number' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="work_allocation_reference_number"]').val(resp.results[0].id);
							$j('[id=work_allocation_reference_number-container-readonly__RAND__]').html('<span class="match-text" id="work_allocation_reference_number-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=work_allocation_view_parent]').hide(); } else { $j('.btn[id=work_allocation_view_parent]').show(); }


							if(typeof(work_allocation_reference_number_update_autofills__RAND__) == 'function') work_allocation_reference_number_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { filterer_vehicle_registration_number: filterer_vehicle_registration_number, s: term, p: page, t: 'inspection_bay', f: 'work_allocation_reference_number' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_work_allocation_reference_number__RAND__.value = e.added.id;
				AppGini.current_work_allocation_reference_number__RAND__.text = e.added.text;
				$j('[name="work_allocation_reference_number"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=work_allocation_view_parent]').hide(); } else { $j('.btn[id=work_allocation_view_parent]').show(); }


				if(typeof(work_allocation_reference_number_update_autofills__RAND__) == 'function') work_allocation_reference_number_update_autofills__RAND__();
			});

			if(!$j("#work_allocation_reference_number-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_work_allocation_reference_number__RAND__.value, t: 'inspection_bay', f: 'work_allocation_reference_number' },
					success: function(resp) {
						$j('[name="work_allocation_reference_number"]').val(resp.results[0].id);
						$j('[id=work_allocation_reference_number-container-readonly__RAND__]').html('<span class="match-text" id="work_allocation_reference_number-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=work_allocation_view_parent]').hide(); } else { $j('.btn[id=work_allocation_view_parent]').show(); }

						if(typeof(work_allocation_reference_number_update_autofills__RAND__) == 'function') work_allocation_reference_number_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_work_allocation_reference_number__RAND__.value, t: 'inspection_bay', f: 'work_allocation_reference_number' },
				success: function(resp) {
					$j('[id=work_allocation_reference_number-container__RAND__], [id=work_allocation_reference_number-container-readonly__RAND__]').html('<span class="match-text" id="work_allocation_reference_number-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=work_allocation_view_parent]').hide(); } else { $j('.btn[id=work_allocation_view_parent]').show(); }

					if(typeof(work_allocation_reference_number_update_autofills__RAND__) == 'function') work_allocation_reference_number_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_clean());


	// code for template based detail view forms

	// open the detail view template
	if($dvprint) {
		$template_file = is_file("./{$TemplateDVP}") ? "./{$TemplateDVP}" : './templates/inspection_bay_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	} else {
		$template_file = is_file("./{$TemplateDV}") ? "./{$TemplateDV}" : './templates/inspection_bay_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Inspection Bay ID Details:', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', (Request::val('Embedded') ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($arrPerm['insert'] && !$selected_id) { // allow insert and no record selected?
		if(!$selected_id) $templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return inspection_bay_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return inspection_bay_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if(Request::val('Embedded')) {
		$backAction = 'AppGini.closeParentModal(); return false;';
	} else {
		$backAction = '$j(\'form\').eq(0).attr(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id) {
		if(!Request::val('Embedded')) $templateCode = str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$j(\'form\').eq(0).prop(\'novalidate\', true); document.myform.reset(); return true;" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($AllowUpdate) {
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return inspection_bay_validateData();" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		} else {
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		}
		if(($arrPerm['delete'] == 1 && $ownerMemberID == getLoggedMemberID()) || ($arrPerm['delete'] == 2 && $ownerGroupID == getLoggedGroupID()) || $arrPerm['delete'] == 3) { // allow delete?
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" onclick="return confirm(\'' . $Translation['are you sure?'] . '\');" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		} else {
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);

		// if not in embedded mode and user has insert only but no view/update/delete,
		// remove 'back' button
		if(
			$arrPerm['insert']
			&& !$arrPerm['update'] && !$arrPerm['delete'] && !$arrPerm['view']
			&& !Request::val('Embedded')
		)
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
		elseif($separateDV)
			$templateCode = str_replace(
				'<%%DESELECT_BUTTON%%>', 
				'<button
					type="submit" 
					class="btn btn-default" 
					id="deselect" 
					name="deselect_x" 
					value="1" 
					onclick="' . $backAction . '" 
					title="' . html_attr($Translation['Back']) . '">
						<i class="glyphicon glyphicon-chevron-left"></i> ' .
						$Translation['Back'] .
				'</button>',
				$templateCode
			);
		else
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate) || (!$selected_id && !$AllowInsert)) {
		$jsReadOnly = '';
		$jsReadOnly .= "\tjQuery('#inspection_bay_supervisor_name_and_surname').replaceWith('<div class=\"form-control-static\" id=\"inspection_bay_supervisor_name_and_surname\">' + (jQuery('#inspection_bay_supervisor_name_and_surname').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#supervisor_contact_details').replaceWith('<div class=\"form-control-static\" id=\"supervisor_contact_details\">' + (jQuery('#supervisor_contact_details').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#supervisor_email_address').replaceWith('<div class=\"form-control-static\" id=\"supervisor_email_address\">' + (jQuery('#supervisor_email_address').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#supervisor_email_address, #supervisor_email_address-edit-link').hide();\n";
		$jsReadOnly .= "\tjQuery('#supervisor_signature').replaceWith('<div class=\"form-control-static\" id=\"supervisor_signature\">' + (jQuery('#supervisor_signature').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#date_of_vehicle_entrance').parents('.input-group').replaceWith('<div class=\"form-control-static\" id=\"date_of_vehicle_entrance\">' + (jQuery('#date_of_vehicle_entrance').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#job_card_number').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#job_card_number_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#vehicle_registration_number').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#vehicle_registration_number_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#work_allocation_reference_number').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#work_allocation_reference_number_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#inspection_bay_lane_number').replaceWith('<div class=\"form-control-static\" id=\"inspection_bay_lane_number\">' + (jQuery('#inspection_bay_lane_number').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#inspection_bay_condition').replaceWith('<div class=\"form-control-static\" id=\"inspection_bay_condition\">' + (jQuery('#inspection_bay_condition').val() || '') + '</div>'); jQuery('#inspection_bay_condition-multi-selection-help').hide();\n";
		$jsReadOnly .= "\tjQuery('#additional_defects').replaceWith('<div class=\"form-control-static\" id=\"additional_defects\">' + (jQuery('#additional_defects').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#additional_defects_record').replaceWith('<div class=\"form-control-static\" id=\"additional_defects_record\">' + (jQuery('#additional_defects_record').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#additional_defects_record, #additional_defects_record-edit-link').hide();\n";
		$jsReadOnly .= "\tjQuery('#repair_requirement_note').replaceWith('<div class=\"form-control-static\" id=\"repair_requirement_note\">' + (jQuery('#repair_requirement_note').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#repair_requirement_report').replaceWith('<div class=\"form-control-static\" id=\"repair_requirement_report\">' + (jQuery('#repair_requirement_report').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#repair_requirement_report, #repair_requirement_report-edit-link').hide();\n";
		$jsReadOnly .= "\tjQuery('#date_of_vehicle_exit').parents('.input-group').replaceWith('<div class=\"form-control-static\" id=\"date_of_vehicle_exit\">' + (jQuery('#date_of_vehicle_exit').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	} elseif(($AllowInsert && !$selected_id) || ($AllowUpdate && $selected_id)) {
		$jsEditable = "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
		$locale = isset($Translation['datetimepicker locale']) ? ", locale: '{$Translation['datetimepicker locale']}'" : '';
		$jsEditable .= "\tjQuery('#date_of_vehicle_entrance').addClass('always_shown').parents('.input-group').datetimepicker({ toolbarPlacement: 'top', sideBySide: true, showClear: true, showTodayButton: true, showClose: true, icons: { close: 'glyphicon glyphicon-ok' }, format: AppGini.datetimeFormat('dt') {$locale} });";
		$locale = isset($Translation['datetimepicker locale']) ? ", locale: '{$Translation['datetimepicker locale']}'" : '';
		$jsEditable .= "\tjQuery('#date_of_vehicle_exit').addClass('always_shown').parents('.input-group').datetimepicker({ toolbarPlacement: 'top', sideBySide: true, showClear: true, showTodayButton: true, showClose: true, icons: { close: 'glyphicon glyphicon-ok' }, format: AppGini.datetimeFormat('dt') {$locale} });";
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode = str_replace('<%%COMBO(job_card_number)%%>', $combo_job_card_number->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(job_card_number)%%>', $combo_job_card_number->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(job_card_number)%%>', urlencode($combo_job_card_number->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(vehicle_registration_number)%%>', $combo_vehicle_registration_number->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(vehicle_registration_number)%%>', $combo_vehicle_registration_number->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(vehicle_registration_number)%%>', urlencode($combo_vehicle_registration_number->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(work_allocation_reference_number)%%>', $combo_work_allocation_reference_number->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(work_allocation_reference_number)%%>', $combo_work_allocation_reference_number->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(work_allocation_reference_number)%%>', urlencode($combo_work_allocation_reference_number->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(inspection_bay_condition)%%>', $combo_inspection_bay_condition->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(inspection_bay_condition)%%>', $combo_inspection_bay_condition->SelectedData, $templateCode);

	/* lookup fields array: 'lookup field name' => ['parent table name', 'lookup field caption'] */
	$lookup_fields = ['job_card_number' => ['reception', 'Job Card Number:'], 'vehicle_registration_number' => ['gmt_fleet_register', 'Registration Number:'], 'work_allocation_reference_number' => ['work_allocation', 'Work Allocation Reference Number:'], ];
	foreach($lookup_fields as $luf => $ptfc) {
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if($pt_perm['view'] || $pt_perm['edit']) {
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] /* && !Request::val('Embedded')*/) {
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-default add_new_parent" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus text-success"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(inspection_bay_id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(inspection_bay_supervisor_name_and_surname)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(supervisor_contact_details)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(supervisor_email_address)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(supervisor_signature)%%>', ($noUploads ? '' : "<div>{$Translation['upload image']}</div>" . '<i class="glyphicon glyphicon-remove text-danger clear-upload hidden"></i> <input type="file" name="supervisor_signature" id="supervisor_signature" data-filetypes="jpg|jpeg|gif|png|webp" data-maxsize="512000" accept=".jpg,.jpeg,.gif,.png,.webp">'), $templateCode);
	if($AllowUpdate && $row['supervisor_signature'] != '') {
		$templateCode = str_replace('<%%REMOVEFILE(supervisor_signature)%%>', '<br><input type="checkbox" name="supervisor_signature_remove" id="supervisor_signature_remove" value="1"> <label for="supervisor_signature_remove" style="color: red; font-weight: bold;">'.$Translation['remove image'].'</label>', $templateCode);
	} else {
		$templateCode = str_replace('<%%REMOVEFILE(supervisor_signature)%%>', '', $templateCode);
	}
	$templateCode = str_replace('<%%UPLOADFILE(date_of_vehicle_entrance)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(job_card_number)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(vehicle_registration_number)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(work_allocation_reference_number)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(inspection_bay_lane_number)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(inspection_bay_condition)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(allocation_feedback)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(verification_of_defects)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(additional_defects)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(additional_defects_record)%%>', ($noUploads ? '' : "<div>{$Translation['upload image']}</div>" . '<i class="glyphicon glyphicon-remove text-danger clear-upload hidden"></i> <input type="file" name="additional_defects_record" id="additional_defects_record" data-filetypes="txt|doc|docx|docm|odt|pdf|rtf" data-maxsize="102400" accept=".txt,.doc,.docx,.docm,.odt,.pdf,.rtf">'), $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(repair_requirement_note)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(repair_requirement_report)%%>', ($noUploads ? '' : "<div>{$Translation['upload image']}</div>" . '<i class="glyphicon glyphicon-remove text-danger clear-upload hidden"></i> <input type="file" name="repair_requirement_report" id="repair_requirement_report" data-filetypes="txt|doc|docx|docm|odt|pdf|rtf" data-maxsize="5242880" accept=".txt,.doc,.docx,.docm,.odt,.pdf,.rtf">'), $templateCode);
	if($AllowUpdate && $row['repair_requirement_report'] != '') {
		$templateCode = str_replace('<%%REMOVEFILE(repair_requirement_report)%%>', '<br><input type="checkbox" name="repair_requirement_report_remove" id="repair_requirement_report_remove" value="1"> <label for="repair_requirement_report_remove" style="color: red; font-weight: bold;">'.$Translation['remove image'].'</label>', $templateCode);
	} else {
		$templateCode = str_replace('<%%REMOVEFILE(repair_requirement_report)%%>', '', $templateCode);
	}
	$templateCode = str_replace('<%%UPLOADFILE(date_of_vehicle_exit)%%>', '', $templateCode);

	// process values
	if($selected_id) {
		if( $dvprint) $templateCode = str_replace('<%%VALUE(inspection_bay_id)%%>', safe_html($urow['inspection_bay_id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(inspection_bay_id)%%>', html_attr($row['inspection_bay_id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(inspection_bay_id)%%>', urlencode($urow['inspection_bay_id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(inspection_bay_supervisor_name_and_surname)%%>', safe_html($urow['inspection_bay_supervisor_name_and_surname']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(inspection_bay_supervisor_name_and_surname)%%>', html_attr($row['inspection_bay_supervisor_name_and_surname']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(inspection_bay_supervisor_name_and_surname)%%>', urlencode($urow['inspection_bay_supervisor_name_and_surname']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(supervisor_contact_details)%%>', safe_html($urow['supervisor_contact_details']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(supervisor_contact_details)%%>', html_attr($row['supervisor_contact_details']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(supervisor_contact_details)%%>', urlencode($urow['supervisor_contact_details']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(supervisor_email_address)%%>', safe_html($urow['supervisor_email_address']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(supervisor_email_address)%%>', html_attr($row['supervisor_email_address']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(supervisor_email_address)%%>', urlencode($urow['supervisor_email_address']), $templateCode);
		$row['supervisor_signature'] = ($row['supervisor_signature'] != '' ? $row['supervisor_signature'] : 'blank.gif');
		if( $dvprint) $templateCode = str_replace('<%%VALUE(supervisor_signature)%%>', safe_html($urow['supervisor_signature']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(supervisor_signature)%%>', html_attr($row['supervisor_signature']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(supervisor_signature)%%>', urlencode($urow['supervisor_signature']), $templateCode);
		$templateCode = str_replace('<%%VALUE(date_of_vehicle_entrance)%%>', app_datetime($row['date_of_vehicle_entrance'], 'dt'), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(date_of_vehicle_entrance)%%>', urlencode(app_datetime($urow['date_of_vehicle_entrance'], 'dt')), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(job_card_number)%%>', safe_html($urow['job_card_number']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(job_card_number)%%>', html_attr($row['job_card_number']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(job_card_number)%%>', urlencode($urow['job_card_number']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(vehicle_registration_number)%%>', safe_html($urow['vehicle_registration_number']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(vehicle_registration_number)%%>', html_attr($row['vehicle_registration_number']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(vehicle_registration_number)%%>', urlencode($urow['vehicle_registration_number']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(work_allocation_reference_number)%%>', safe_html($urow['work_allocation_reference_number']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(work_allocation_reference_number)%%>', html_attr($row['work_allocation_reference_number']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(work_allocation_reference_number)%%>', urlencode($urow['work_allocation_reference_number']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(inspection_bay_lane_number)%%>', safe_html($urow['inspection_bay_lane_number']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(inspection_bay_lane_number)%%>', html_attr($row['inspection_bay_lane_number']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(inspection_bay_lane_number)%%>', urlencode($urow['inspection_bay_lane_number']), $templateCode);
		if($AllowUpdate || $AllowInsert) {
			$templateCode = str_replace('<%%HTMLAREA(inspection_bay_condition)%%>', '<textarea name="inspection_bay_condition" id="inspection_bay_condition" rows="5">' . safe_html(htmlspecialchars_decode($row['inspection_bay_condition'])) . '</textarea>', $templateCode);
		} else {
			$templateCode = str_replace('<%%HTMLAREA(inspection_bay_condition)%%>', '<div id="inspection_bay_condition" class="form-control-static">' . $row['inspection_bay_condition'] . '</div>', $templateCode);
		}
		$templateCode = str_replace('<%%VALUE(inspection_bay_condition)%%>', nl2br($row['inspection_bay_condition']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(inspection_bay_condition)%%>', urlencode($urow['inspection_bay_condition']), $templateCode);
		if($AllowUpdate || $AllowInsert) {
			$templateCode = str_replace('<%%HTMLAREA(allocation_feedback)%%>', '<textarea name="allocation_feedback" id="allocation_feedback" rows="5">' . safe_html(htmlspecialchars_decode($row['allocation_feedback'])) . '</textarea>', $templateCode);
		} else {
			$templateCode = str_replace('<%%HTMLAREA(allocation_feedback)%%>', '<div id="allocation_feedback" class="form-control-static">' . $row['allocation_feedback'] . '</div>', $templateCode);
		}
		$templateCode = str_replace('<%%VALUE(allocation_feedback)%%>', nl2br($row['allocation_feedback']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(allocation_feedback)%%>', urlencode($urow['allocation_feedback']), $templateCode);
		if($AllowUpdate || $AllowInsert) {
			$templateCode = str_replace('<%%HTMLAREA(verification_of_defects)%%>', '<textarea name="verification_of_defects" id="verification_of_defects" rows="5">' . safe_html(htmlspecialchars_decode($row['verification_of_defects'])) . '</textarea>', $templateCode);
		} else {
			$templateCode = str_replace('<%%HTMLAREA(verification_of_defects)%%>', '<div id="verification_of_defects" class="form-control-static">' . $row['verification_of_defects'] . '</div>', $templateCode);
		}
		$templateCode = str_replace('<%%VALUE(verification_of_defects)%%>', nl2br($row['verification_of_defects']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(verification_of_defects)%%>', urlencode($urow['verification_of_defects']), $templateCode);
		if($dvprint || (!$AllowUpdate && !$AllowInsert)) {
			$templateCode = str_replace('<%%VALUE(additional_defects)%%>', safe_html($urow['additional_defects']), $templateCode);
		} else {
			$templateCode = str_replace('<%%VALUE(additional_defects)%%>', safe_html($urow['additional_defects'], true), $templateCode);
		}
		$templateCode = str_replace('<%%URLVALUE(additional_defects)%%>', urlencode($urow['additional_defects']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(additional_defects_record)%%>', safe_html($urow['additional_defects_record']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(additional_defects_record)%%>', html_attr($row['additional_defects_record']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(additional_defects_record)%%>', urlencode($urow['additional_defects_record']), $templateCode);
		if($dvprint || (!$AllowUpdate && !$AllowInsert)) {
			$templateCode = str_replace('<%%VALUE(repair_requirement_note)%%>', safe_html($urow['repair_requirement_note']), $templateCode);
		} else {
			$templateCode = str_replace('<%%VALUE(repair_requirement_note)%%>', safe_html($urow['repair_requirement_note'], true), $templateCode);
		}
		$templateCode = str_replace('<%%URLVALUE(repair_requirement_note)%%>', urlencode($urow['repair_requirement_note']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(repair_requirement_report)%%>', safe_html($urow['repair_requirement_report']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(repair_requirement_report)%%>', html_attr($row['repair_requirement_report']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(repair_requirement_report)%%>', urlencode($urow['repair_requirement_report']), $templateCode);
		$templateCode = str_replace('<%%VALUE(date_of_vehicle_exit)%%>', app_datetime($row['date_of_vehicle_exit'], 'dt'), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(date_of_vehicle_exit)%%>', urlencode(app_datetime($urow['date_of_vehicle_exit'], 'dt')), $templateCode);
	} else {
		$templateCode = str_replace('<%%VALUE(inspection_bay_id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(inspection_bay_id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(inspection_bay_supervisor_name_and_surname)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(inspection_bay_supervisor_name_and_surname)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(supervisor_contact_details)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(supervisor_contact_details)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(supervisor_email_address)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(supervisor_email_address)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(supervisor_signature)%%>', 'blank.gif', $templateCode);
		$templateCode = str_replace('<%%VALUE(date_of_vehicle_entrance)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(date_of_vehicle_entrance)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(job_card_number)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(job_card_number)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(vehicle_registration_number)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(vehicle_registration_number)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(work_allocation_reference_number)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(work_allocation_reference_number)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(inspection_bay_lane_number)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(inspection_bay_lane_number)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%HTMLAREA(inspection_bay_condition)%%>', '<textarea name="inspection_bay_condition" id="inspection_bay_condition" rows="5"></textarea>', $templateCode);
		$templateCode = str_replace('<%%HTMLAREA(allocation_feedback)%%>', '<textarea name="allocation_feedback" id="allocation_feedback" rows="5"></textarea>', $templateCode);
		$templateCode = str_replace('<%%HTMLAREA(verification_of_defects)%%>', '<textarea name="verification_of_defects" id="verification_of_defects" rows="5"></textarea>', $templateCode);
		$templateCode = str_replace('<%%VALUE(additional_defects)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(additional_defects)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(additional_defects_record)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(additional_defects_record)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(repair_requirement_note)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(repair_requirement_note)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(repair_requirement_report)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(repair_requirement_report)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(date_of_vehicle_exit)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(date_of_vehicle_exit)%%>', urlencode(''), $templateCode);
	}

	// process translations
	$templateCode = parseTemplate($templateCode);

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if(Request::val('dvprint_x') == '') {
		$templateCode .= "\n\n<script>\$j(function() {\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption) {
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id) {
			$templateCode.="\n\tif(document.getElementById('supervisor_email_addressEdit')) { document.getElementById('supervisor_email_addressEdit').style.display='inline'; }";
			$templateCode.="\n\tif(document.getElementById('supervisor_email_addressEditLink')) { document.getElementById('supervisor_email_addressEditLink').style.display='none'; }";
			$templateCode.="\n\tif(document.getElementById('additional_defects_recordEdit')) { document.getElementById('additional_defects_recordEdit').style.display='inline'; }";
			$templateCode.="\n\tif(document.getElementById('additional_defects_recordEditLink')) { document.getElementById('additional_defects_recordEditLink').style.display='none'; }";
			$templateCode.="\n\tif(document.getElementById('repair_requirement_reportEdit')) { document.getElementById('repair_requirement_reportEdit').style.display='inline'; }";
			$templateCode.="\n\tif(document.getElementById('repair_requirement_reportEditLink')) { document.getElementById('repair_requirement_reportEditLink').style.display='none'; }";
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';

	$templateCode .= "\tjob_card_number_update_autofills$rnd1 = function() {\n";
	$templateCode .= "\t\t\$j.ajax({\n";
	if($dvprint) {
		$templateCode .= "\t\t\turl: 'inspection_bay_autofill.php?rnd1=$rnd1&mfk=job_card_number&id=' + encodeURIComponent('".addslashes($row['job_card_number'])."'),\n";
		$templateCode .= "\t\t\tcontentType: 'application/x-www-form-urlencoded; charset=" . datalist_db_encoding . "',\n";
		$templateCode .= "\t\t\ttype: 'GET'\n";
	} else {
		$templateCode .= "\t\t\turl: 'inspection_bay_autofill.php?rnd1=$rnd1&mfk=job_card_number&id=' + encodeURIComponent(AppGini.current_job_card_number{$rnd1}.value),\n";
		$templateCode .= "\t\t\tcontentType: 'application/x-www-form-urlencoded; charset=" . datalist_db_encoding . "',\n";
		$templateCode .= "\t\t\ttype: 'GET',\n";
		$templateCode .= "\t\t\tbeforeSend: function() { \$j('#job_card_number$rnd1').prop('disabled', true); },\n";
		$templateCode .= "\t\t\tcomplete: function() { " . (($arrPerm['insert'] || (($arrPerm['edit'] == 1 && $ownerMemberID == getLoggedMemberID()) || ($arrPerm['edit'] == 2 && $ownerGroupID == getLoggedGroupID()) || $arrPerm['edit'] == 3)) ? "\$j('#job_card_number$rnd1').prop('disabled', false); " : "\$j('#job_card_number$rnd1').prop('disabled', true); ")." \$j(window).resize(); }\n";
	}
	$templateCode .= "\t\t});\n";
	$templateCode .= "\t};\n";
	if(!$dvprint) $templateCode .= "\tif(\$j('#job_card_number_caption').length) \$j('#job_card_number_caption').click(function() { job_card_number_update_autofills$rnd1(); });\n";

	$templateCode .= "\tvehicle_registration_number_update_autofills$rnd1 = function() {\n";
	$templateCode .= "\t\t\$j.ajax({\n";
	if($dvprint) {
		$templateCode .= "\t\t\turl: 'inspection_bay_autofill.php?rnd1=$rnd1&mfk=vehicle_registration_number&id=' + encodeURIComponent('".addslashes($row['vehicle_registration_number'])."'),\n";
		$templateCode .= "\t\t\tcontentType: 'application/x-www-form-urlencoded; charset=" . datalist_db_encoding . "',\n";
		$templateCode .= "\t\t\ttype: 'GET'\n";
	} else {
		$templateCode .= "\t\t\turl: 'inspection_bay_autofill.php?rnd1=$rnd1&mfk=vehicle_registration_number&id=' + encodeURIComponent(AppGini.current_vehicle_registration_number{$rnd1}.value),\n";
		$templateCode .= "\t\t\tcontentType: 'application/x-www-form-urlencoded; charset=" . datalist_db_encoding . "',\n";
		$templateCode .= "\t\t\ttype: 'GET',\n";
		$templateCode .= "\t\t\tbeforeSend: function() { \$j('#vehicle_registration_number$rnd1').prop('disabled', true); },\n";
		$templateCode .= "\t\t\tcomplete: function() { " . (($arrPerm['insert'] || (($arrPerm['edit'] == 1 && $ownerMemberID == getLoggedMemberID()) || ($arrPerm['edit'] == 2 && $ownerGroupID == getLoggedGroupID()) || $arrPerm['edit'] == 3)) ? "\$j('#vehicle_registration_number$rnd1').prop('disabled', false); " : "\$j('#vehicle_registration_number$rnd1').prop('disabled', true); ")." \$j(window).resize(); }\n";
	}
	$templateCode .= "\t\t});\n";
	$templateCode .= "\t};\n";
	if(!$dvprint) $templateCode .= "\tif(\$j('#vehicle_registration_number_caption').length) \$j('#vehicle_registration_number_caption').click(function() { vehicle_registration_number_update_autofills$rnd1(); });\n";


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields
	$filterField = Request::val('FilterField');
	$filterOperator = Request::val('FilterOperator');
	$filterValue = Request::val('FilterValue');

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('inspection_bay');
	if($selected_id) {
		$jdata = get_joined_record('inspection_bay', $selected_id);
		if($jdata === false) $jdata = get_defaults('inspection_bay');
		$rdata = $row;
	}
	$templateCode .= loadView('inspection_bay-ajax-cache', ['rdata' => $rdata, 'jdata' => $jdata]);

	// hook: inspection_bay_dv
	if(function_exists('inspection_bay_dv')) {
		$args = [];
		inspection_bay_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}