<?php
// This script and data application were generated by AppGini 22.13
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/manufacturer.php');
	include_once(__DIR__ . '/manufacturer_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('manufacturer');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'manufacturer';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`manufacturer`.`manufacturer_id`" => "manufacturer_id",
		"IF(    CHAR_LENGTH(`manufacturer_type1`.`manufacturer_type`), CONCAT_WS('',   `manufacturer_type1`.`manufacturer_type`), '') /* Manufacturer Type: */" => "manufacturer_type",
		"`manufacturer`.`manufacturer_name`" => "manufacturer_name",
		"`manufacturer`.`contact_person`" => "contact_person",
		"`manufacturer`.`contact_details`" => "contact_details",
		"`manufacturer`.`contact_email`" => "contact_email",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`manufacturer`.`manufacturer_id`',
		2 => '`manufacturer_type1`.`manufacturer_type`',
		3 => 3,
		4 => 4,
		5 => 5,
		6 => 6,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`manufacturer`.`manufacturer_id`" => "manufacturer_id",
		"IF(    CHAR_LENGTH(`manufacturer_type1`.`manufacturer_type`), CONCAT_WS('',   `manufacturer_type1`.`manufacturer_type`), '') /* Manufacturer Type: */" => "manufacturer_type",
		"`manufacturer`.`manufacturer_name`" => "manufacturer_name",
		"`manufacturer`.`contact_person`" => "contact_person",
		"`manufacturer`.`contact_details`" => "contact_details",
		"`manufacturer`.`contact_email`" => "contact_email",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`manufacturer`.`manufacturer_id`" => "Manufacturer ID:",
		"IF(    CHAR_LENGTH(`manufacturer_type1`.`manufacturer_type`), CONCAT_WS('',   `manufacturer_type1`.`manufacturer_type`), '') /* Manufacturer Type: */" => "Manufacturer Type:",
		"`manufacturer`.`manufacturer_name`" => "Manufacturer Name:",
		"`manufacturer`.`contact_person`" => "Contact Person:",
		"`manufacturer`.`contact_details`" => "Contact Details:",
		"`manufacturer`.`contact_email`" => "Contact e-Mail:",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`manufacturer`.`manufacturer_id`" => "manufacturer_id",
		"IF(    CHAR_LENGTH(`manufacturer_type1`.`manufacturer_type`), CONCAT_WS('',   `manufacturer_type1`.`manufacturer_type`), '') /* Manufacturer Type: */" => "manufacturer_type",
		"`manufacturer`.`manufacturer_name`" => "manufacturer_name",
		"`manufacturer`.`contact_person`" => "contact_person",
		"`manufacturer`.`contact_details`" => "contact_details",
		"`manufacturer`.`contact_email`" => "contact_email",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = ['manufacturer_type' => 'Manufacturer Type:', ];

	$x->QueryFrom = "`manufacturer` LEFT JOIN `manufacturer_type` as manufacturer_type1 ON `manufacturer_type1`.`manufacturer_type_id`=`manufacturer`.`manufacturer_type` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 25;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'manufacturer_view.php';
	$x->RedirectAfterInsert = 'manufacturer_view.php?SelectedID=#ID#';
	$x->TableTitle = 'Manufacturer:';
	$x->TableIcon = 'resources/table_icons/worm-gear-icon.png';
	$x->PrimaryKey = '`manufacturer`.`manufacturer_id`';

	$x->ColWidth = [150, 150, 150, 150, 150, 150, ];
	$x->ColCaption = ['Manufacturer ID:', 'Manufacturer Type:', 'Manufacturer Name:', 'Contact Person:', 'Contact Details:', 'Contact e-Mail:', ];
	$x->ColFieldName = ['manufacturer_id', 'manufacturer_type', 'manufacturer_name', 'contact_person', 'contact_details', 'contact_email', ];
	$x->ColNumber  = [1, 2, 3, 4, 5, 6, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/manufacturer_templateTV.html';
	$x->SelectedTemplate = 'templates/manufacturer_templateTVS.html';
	$x->TemplateDV = 'templates/manufacturer_templateDV.html';
	$x->TemplateDVP = 'templates/manufacturer_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: manufacturer_init
	$render = true;
	if(function_exists('manufacturer_init')) {
		$args = [];
		$render = manufacturer_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: manufacturer_header
	$headerCode = '';
	if(function_exists('manufacturer_header')) {
		$args = [];
		$headerCode = manufacturer_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: manufacturer_footer
	$footerCode = '';
	if(function_exists('manufacturer_footer')) {
		$args = [];
		$footerCode = manufacturer_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
