<?php

// Data functions (insert, update, delete, form) for table manufacturer

// This script and data application were generated by AppGini 22.13
// Download AppGini for free from https://bigprof.com/appgini/download/

function manufacturer_insert(&$error_message = '') {
	global $Translation;

	// mm: can member insert record?
	$arrPerm = getTablePermissions('manufacturer');
	if(!$arrPerm['insert']) return false;

	$data = [
		'manufacturer_type' => Request::lookup('manufacturer_type', ''),
		'manufacturer_name' => Request::val('manufacturer_name', ''),
		'contact_person' => Request::val('contact_person', ''),
		'contact_details' => Request::val('contact_details', ''),
		'contact_email' => Request::val('contact_email', ''),
	];


	// hook: manufacturer_before_insert
	if(function_exists('manufacturer_before_insert')) {
		$args = [];
		if(!manufacturer_before_insert($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$error = '';
	// set empty fields to NULL
	$data = array_map(function($v) { return ($v === '' ? NULL : $v); }, $data);
	insert('manufacturer', backtick_keys_once($data), $error);
	if($error) {
		$error_message = $error;
		return false;
	}

	$recID = db_insert_id(db_link());

	update_calc_fields('manufacturer', $recID, calculated_fields()['manufacturer']);

	// hook: manufacturer_after_insert
	if(function_exists('manufacturer_after_insert')) {
		$res = sql("SELECT * FROM `manufacturer` WHERE `manufacturer_id`='" . makeSafe($recID, false) . "' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) {
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args = [];
		if(!manufacturer_after_insert($data, getMemberInfo(), $args)) { return $recID; }
	}

	// mm: save ownership data
	set_record_owner('manufacturer', $recID, getLoggedMemberID());

	// if this record is a copy of another record, copy children if applicable
	if(strlen(Request::val('SelectedID'))) manufacturer_copy_children($recID, Request::val('SelectedID'));

	return $recID;
}

function manufacturer_copy_children($destination_id, $source_id) {
	global $Translation;
	$requests = []; // array of curl handlers for launching insert requests
	$eo = ['silentErrors' => true];
	$safe_sid = makeSafe($source_id);

	// launch requests, asynchronously
	curl_batch($requests);
}

function manufacturer_delete($selected_id, $AllowDeleteOfParents = false, $skipChecks = false) {
	// insure referential integrity ...
	global $Translation;
	$selected_id = makeSafe($selected_id);

	// mm: can member delete record?
	if(!check_record_permission('manufacturer', $selected_id, 'delete')) {
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: manufacturer_before_delete
	if(function_exists('manufacturer_before_delete')) {
		$args = [];
		if(!manufacturer_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'] . (
				!empty($args['error_message']) ?
					'<div class="text-bold">' . strip_tags($args['error_message']) . '</div>'
					: '' 
			);
	}

	// child table: purchase_orders
	$res = sql("SELECT `manufacturer_id` FROM `manufacturer` WHERE `manufacturer_id`='{$selected_id}'", $eo);
	$manufacturer_id = db_fetch_row($res);
	$rires = sql("SELECT COUNT(1) FROM `purchase_orders` WHERE `manufacturer`='" . makeSafe($manufacturer_id[0]) . "'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'purchase_orders', $RetMsg);
		return $RetMsg;
	} elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation['confirm delete'];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'purchase_orders', $RetMsg);
		$RetMsg = str_replace('<Delete>', '<input type="button" class="btn btn-danger" value="' . html_attr($Translation['yes']) . '" onClick="window.location = \'manufacturer_view.php?SelectedID=' . urlencode($selected_id) . '&delete_x=1&confirmed=1&csrf_token=' . urlencode(csrf_token(false, true)) . '\';">', $RetMsg);
		$RetMsg = str_replace('<Cancel>', '<input type="button" class="btn btn-success" value="' . html_attr($Translation[ 'no']) . '" onClick="window.location = \'manufacturer_view.php?SelectedID=' . urlencode($selected_id) . '\';">', $RetMsg);
		return $RetMsg;
	}

	// child table: purchase_orders
	$res = sql("SELECT `manufacturer_id` FROM `manufacturer` WHERE `manufacturer_id`='{$selected_id}'", $eo);
	$manufacturer_id = db_fetch_row($res);
	$rires = sql("SELECT COUNT(1) FROM `purchase_orders` WHERE `part_manufacturer_name_1`='" . makeSafe($manufacturer_id[0]) . "'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'purchase_orders', $RetMsg);
		return $RetMsg;
	} elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation['confirm delete'];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'purchase_orders', $RetMsg);
		$RetMsg = str_replace('<Delete>', '<input type="button" class="btn btn-danger" value="' . html_attr($Translation['yes']) . '" onClick="window.location = \'manufacturer_view.php?SelectedID=' . urlencode($selected_id) . '&delete_x=1&confirmed=1&csrf_token=' . urlencode(csrf_token(false, true)) . '\';">', $RetMsg);
		$RetMsg = str_replace('<Cancel>', '<input type="button" class="btn btn-success" value="' . html_attr($Translation[ 'no']) . '" onClick="window.location = \'manufacturer_view.php?SelectedID=' . urlencode($selected_id) . '\';">', $RetMsg);
		return $RetMsg;
	}

	// child table: purchase_orders
	$res = sql("SELECT `manufacturer_id` FROM `manufacturer` WHERE `manufacturer_id`='{$selected_id}'", $eo);
	$manufacturer_id = db_fetch_row($res);
	$rires = sql("SELECT COUNT(1) FROM `purchase_orders` WHERE `part_manufacturer_name_2`='" . makeSafe($manufacturer_id[0]) . "'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'purchase_orders', $RetMsg);
		return $RetMsg;
	} elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation['confirm delete'];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'purchase_orders', $RetMsg);
		$RetMsg = str_replace('<Delete>', '<input type="button" class="btn btn-danger" value="' . html_attr($Translation['yes']) . '" onClick="window.location = \'manufacturer_view.php?SelectedID=' . urlencode($selected_id) . '&delete_x=1&confirmed=1&csrf_token=' . urlencode(csrf_token(false, true)) . '\';">', $RetMsg);
		$RetMsg = str_replace('<Cancel>', '<input type="button" class="btn btn-success" value="' . html_attr($Translation[ 'no']) . '" onClick="window.location = \'manufacturer_view.php?SelectedID=' . urlencode($selected_id) . '\';">', $RetMsg);
		return $RetMsg;
	}

	// child table: purchase_orders
	$res = sql("SELECT `manufacturer_id` FROM `manufacturer` WHERE `manufacturer_id`='{$selected_id}'", $eo);
	$manufacturer_id = db_fetch_row($res);
	$rires = sql("SELECT COUNT(1) FROM `purchase_orders` WHERE `part_manufacturer_name_3`='" . makeSafe($manufacturer_id[0]) . "'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'purchase_orders', $RetMsg);
		return $RetMsg;
	} elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation['confirm delete'];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'purchase_orders', $RetMsg);
		$RetMsg = str_replace('<Delete>', '<input type="button" class="btn btn-danger" value="' . html_attr($Translation['yes']) . '" onClick="window.location = \'manufacturer_view.php?SelectedID=' . urlencode($selected_id) . '&delete_x=1&confirmed=1&csrf_token=' . urlencode(csrf_token(false, true)) . '\';">', $RetMsg);
		$RetMsg = str_replace('<Cancel>', '<input type="button" class="btn btn-success" value="' . html_attr($Translation[ 'no']) . '" onClick="window.location = \'manufacturer_view.php?SelectedID=' . urlencode($selected_id) . '\';">', $RetMsg);
		return $RetMsg;
	}

	// child table: purchase_orders
	$res = sql("SELECT `manufacturer_id` FROM `manufacturer` WHERE `manufacturer_id`='{$selected_id}'", $eo);
	$manufacturer_id = db_fetch_row($res);
	$rires = sql("SELECT COUNT(1) FROM `purchase_orders` WHERE `part_manufacturer_name_4`='" . makeSafe($manufacturer_id[0]) . "'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'purchase_orders', $RetMsg);
		return $RetMsg;
	} elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation['confirm delete'];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'purchase_orders', $RetMsg);
		$RetMsg = str_replace('<Delete>', '<input type="button" class="btn btn-danger" value="' . html_attr($Translation['yes']) . '" onClick="window.location = \'manufacturer_view.php?SelectedID=' . urlencode($selected_id) . '&delete_x=1&confirmed=1&csrf_token=' . urlencode(csrf_token(false, true)) . '\';">', $RetMsg);
		$RetMsg = str_replace('<Cancel>', '<input type="button" class="btn btn-success" value="' . html_attr($Translation[ 'no']) . '" onClick="window.location = \'manufacturer_view.php?SelectedID=' . urlencode($selected_id) . '\';">', $RetMsg);
		return $RetMsg;
	}

	// child table: purchase_orders
	$res = sql("SELECT `manufacturer_id` FROM `manufacturer` WHERE `manufacturer_id`='{$selected_id}'", $eo);
	$manufacturer_id = db_fetch_row($res);
	$rires = sql("SELECT COUNT(1) FROM `purchase_orders` WHERE `part_manufacturer_name_5`='" . makeSafe($manufacturer_id[0]) . "'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'purchase_orders', $RetMsg);
		return $RetMsg;
	} elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation['confirm delete'];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'purchase_orders', $RetMsg);
		$RetMsg = str_replace('<Delete>', '<input type="button" class="btn btn-danger" value="' . html_attr($Translation['yes']) . '" onClick="window.location = \'manufacturer_view.php?SelectedID=' . urlencode($selected_id) . '&delete_x=1&confirmed=1&csrf_token=' . urlencode(csrf_token(false, true)) . '\';">', $RetMsg);
		$RetMsg = str_replace('<Cancel>', '<input type="button" class="btn btn-success" value="' . html_attr($Translation[ 'no']) . '" onClick="window.location = \'manufacturer_view.php?SelectedID=' . urlencode($selected_id) . '\';">', $RetMsg);
		return $RetMsg;
	}

	// child table: purchase_orders
	$res = sql("SELECT `manufacturer_id` FROM `manufacturer` WHERE `manufacturer_id`='{$selected_id}'", $eo);
	$manufacturer_id = db_fetch_row($res);
	$rires = sql("SELECT COUNT(1) FROM `purchase_orders` WHERE `part_manufacturer_name_6`='" . makeSafe($manufacturer_id[0]) . "'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'purchase_orders', $RetMsg);
		return $RetMsg;
	} elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation['confirm delete'];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'purchase_orders', $RetMsg);
		$RetMsg = str_replace('<Delete>', '<input type="button" class="btn btn-danger" value="' . html_attr($Translation['yes']) . '" onClick="window.location = \'manufacturer_view.php?SelectedID=' . urlencode($selected_id) . '&delete_x=1&confirmed=1&csrf_token=' . urlencode(csrf_token(false, true)) . '\';">', $RetMsg);
		$RetMsg = str_replace('<Cancel>', '<input type="button" class="btn btn-success" value="' . html_attr($Translation[ 'no']) . '" onClick="window.location = \'manufacturer_view.php?SelectedID=' . urlencode($selected_id) . '\';">', $RetMsg);
		return $RetMsg;
	}

	// child table: purchase_orders
	$res = sql("SELECT `manufacturer_id` FROM `manufacturer` WHERE `manufacturer_id`='{$selected_id}'", $eo);
	$manufacturer_id = db_fetch_row($res);
	$rires = sql("SELECT COUNT(1) FROM `purchase_orders` WHERE `part_manufacturer_name_7`='" . makeSafe($manufacturer_id[0]) . "'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'purchase_orders', $RetMsg);
		return $RetMsg;
	} elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation['confirm delete'];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'purchase_orders', $RetMsg);
		$RetMsg = str_replace('<Delete>', '<input type="button" class="btn btn-danger" value="' . html_attr($Translation['yes']) . '" onClick="window.location = \'manufacturer_view.php?SelectedID=' . urlencode($selected_id) . '&delete_x=1&confirmed=1&csrf_token=' . urlencode(csrf_token(false, true)) . '\';">', $RetMsg);
		$RetMsg = str_replace('<Cancel>', '<input type="button" class="btn btn-success" value="' . html_attr($Translation[ 'no']) . '" onClick="window.location = \'manufacturer_view.php?SelectedID=' . urlencode($selected_id) . '\';">', $RetMsg);
		return $RetMsg;
	}

	// child table: purchase_orders
	$res = sql("SELECT `manufacturer_id` FROM `manufacturer` WHERE `manufacturer_id`='{$selected_id}'", $eo);
	$manufacturer_id = db_fetch_row($res);
	$rires = sql("SELECT COUNT(1) FROM `purchase_orders` WHERE `part_manufacturer_name_8`='" . makeSafe($manufacturer_id[0]) . "'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'purchase_orders', $RetMsg);
		return $RetMsg;
	} elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation['confirm delete'];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'purchase_orders', $RetMsg);
		$RetMsg = str_replace('<Delete>', '<input type="button" class="btn btn-danger" value="' . html_attr($Translation['yes']) . '" onClick="window.location = \'manufacturer_view.php?SelectedID=' . urlencode($selected_id) . '&delete_x=1&confirmed=1&csrf_token=' . urlencode(csrf_token(false, true)) . '\';">', $RetMsg);
		$RetMsg = str_replace('<Cancel>', '<input type="button" class="btn btn-success" value="' . html_attr($Translation[ 'no']) . '" onClick="window.location = \'manufacturer_view.php?SelectedID=' . urlencode($selected_id) . '\';">', $RetMsg);
		return $RetMsg;
	}

	// child table: parts
	$res = sql("SELECT `manufacturer_id` FROM `manufacturer` WHERE `manufacturer_id`='{$selected_id}'", $eo);
	$manufacturer_id = db_fetch_row($res);
	$rires = sql("SELECT COUNT(1) FROM `parts` WHERE `manufacturer`='" . makeSafe($manufacturer_id[0]) . "'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'parts', $RetMsg);
		return $RetMsg;
	} elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation['confirm delete'];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'parts', $RetMsg);
		$RetMsg = str_replace('<Delete>', '<input type="button" class="btn btn-danger" value="' . html_attr($Translation['yes']) . '" onClick="window.location = \'manufacturer_view.php?SelectedID=' . urlencode($selected_id) . '&delete_x=1&confirmed=1&csrf_token=' . urlencode(csrf_token(false, true)) . '\';">', $RetMsg);
		$RetMsg = str_replace('<Cancel>', '<input type="button" class="btn btn-success" value="' . html_attr($Translation[ 'no']) . '" onClick="window.location = \'manufacturer_view.php?SelectedID=' . urlencode($selected_id) . '\';">', $RetMsg);
		return $RetMsg;
	}

	// child table: breakdown_services
	$res = sql("SELECT `manufacturer_id` FROM `manufacturer` WHERE `manufacturer_id`='{$selected_id}'", $eo);
	$manufacturer_id = db_fetch_row($res);
	$rires = sql("SELECT COUNT(1) FROM `breakdown_services` WHERE `part_manufacturer_name`='" . makeSafe($manufacturer_id[0]) . "'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'breakdown_services', $RetMsg);
		return $RetMsg;
	} elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation['confirm delete'];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'breakdown_services', $RetMsg);
		$RetMsg = str_replace('<Delete>', '<input type="button" class="btn btn-danger" value="' . html_attr($Translation['yes']) . '" onClick="window.location = \'manufacturer_view.php?SelectedID=' . urlencode($selected_id) . '&delete_x=1&confirmed=1&csrf_token=' . urlencode(csrf_token(false, true)) . '\';">', $RetMsg);
		$RetMsg = str_replace('<Cancel>', '<input type="button" class="btn btn-success" value="' . html_attr($Translation[ 'no']) . '" onClick="window.location = \'manufacturer_view.php?SelectedID=' . urlencode($selected_id) . '\';">', $RetMsg);
		return $RetMsg;
	}

	// child table: breakdown_services
	$res = sql("SELECT `manufacturer_id` FROM `manufacturer` WHERE `manufacturer_id`='{$selected_id}'", $eo);
	$manufacturer_id = db_fetch_row($res);
	$rires = sql("SELECT COUNT(1) FROM `breakdown_services` WHERE `part_manufacturer_name_1`='" . makeSafe($manufacturer_id[0]) . "'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'breakdown_services', $RetMsg);
		return $RetMsg;
	} elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation['confirm delete'];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'breakdown_services', $RetMsg);
		$RetMsg = str_replace('<Delete>', '<input type="button" class="btn btn-danger" value="' . html_attr($Translation['yes']) . '" onClick="window.location = \'manufacturer_view.php?SelectedID=' . urlencode($selected_id) . '&delete_x=1&confirmed=1&csrf_token=' . urlencode(csrf_token(false, true)) . '\';">', $RetMsg);
		$RetMsg = str_replace('<Cancel>', '<input type="button" class="btn btn-success" value="' . html_attr($Translation[ 'no']) . '" onClick="window.location = \'manufacturer_view.php?SelectedID=' . urlencode($selected_id) . '\';">', $RetMsg);
		return $RetMsg;
	}

	sql("DELETE FROM `manufacturer` WHERE `manufacturer_id`='{$selected_id}'", $eo);

	// hook: manufacturer_after_delete
	if(function_exists('manufacturer_after_delete')) {
		$args = [];
		manufacturer_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("DELETE FROM `membership_userrecords` WHERE `tableName`='manufacturer' AND `pkValue`='{$selected_id}'", $eo);
}

function manufacturer_update(&$selected_id, &$error_message = '') {
	global $Translation;

	// mm: can member edit record?
	if(!check_record_permission('manufacturer', $selected_id, 'edit')) return false;

	$data = [
		'manufacturer_type' => Request::lookup('manufacturer_type', ''),
		'manufacturer_name' => Request::val('manufacturer_name', ''),
		'contact_person' => Request::val('contact_person', ''),
		'contact_details' => Request::val('contact_details', ''),
		'contact_email' => Request::val('contact_email', ''),
	];

	// get existing values
	$old_data = getRecord('manufacturer', $selected_id);
	if(is_array($old_data)) {
		$old_data = array_map('makeSafe', $old_data);
		$old_data['selectedID'] = makeSafe($selected_id);
	}

	$data['selectedID'] = makeSafe($selected_id);

	// hook: manufacturer_before_update
	if(function_exists('manufacturer_before_update')) {
		$args = ['old_data' => $old_data];
		if(!manufacturer_before_update($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$set = $data; unset($set['selectedID']);
	foreach ($set as $field => $value) {
		$set[$field] = ($value !== '' && $value !== NULL) ? $value : NULL;
	}

	if(!update(
		'manufacturer', 
		backtick_keys_once($set), 
		['`manufacturer_id`' => $selected_id], 
		$error_message
	)) {
		echo $error_message;
		echo '<a href="manufacturer_view.php?SelectedID=' . urlencode($selected_id) . "\">{$Translation['< back']}</a>";
		exit;
	}


	$eo = ['silentErrors' => true];

	update_calc_fields('manufacturer', $data['selectedID'], calculated_fields()['manufacturer']);

	// hook: manufacturer_after_update
	if(function_exists('manufacturer_after_update')) {
		$res = sql("SELECT * FROM `manufacturer` WHERE `manufacturer_id`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) $data = array_map('makeSafe', $row);

		$data['selectedID'] = $data['manufacturer_id'];
		$args = ['old_data' => $old_data];
		if(!manufacturer_after_update($data, getMemberInfo(), $args)) return;
	}

	// mm: update ownership data
	sql("UPDATE `membership_userrecords` SET `dateUpdated`='" . time() . "' WHERE `tableName`='manufacturer' AND `pkValue`='" . makeSafe($selected_id) . "'", $eo);
}

function manufacturer_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $separateDV = 0, $TemplateDV = '', $TemplateDVP = '') {
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;
	$eo = ['silentErrors' => true];
	$noUploads = null;
	$row = $urow = $jsReadOnly = $jsEditable = $lookups = null;

	$noSaveAsCopy = true;

	// mm: get table permissions
	$arrPerm = getTablePermissions('manufacturer');
	if(!$arrPerm['insert'] && $selected_id == '')
		// no insert permission and no record selected
		// so show access denied error unless TVDV
		return $separateDV ? $Translation['tableAccessDenied'] : '';
	$AllowInsert = ($arrPerm['insert'] ? true : false);
	// print preview?
	$dvprint = false;
	if(strlen($selected_id) && Request::val('dvprint_x') != '') {
		$dvprint = true;
	}

	$filterer_manufacturer_type = Request::val('filterer_manufacturer_type');

	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: manufacturer_type
	$combo_manufacturer_type = new DataCombo;

	if($selected_id) {
		// mm: check member permissions
		if(!$arrPerm['view']) return $Translation['tableAccessDenied'];

		// mm: who is the owner?
		$ownerGroupID = sqlValue("SELECT `groupID` FROM `membership_userrecords` WHERE `tableName`='manufacturer' AND `pkValue`='" . makeSafe($selected_id) . "'");
		$ownerMemberID = sqlValue("SELECT LCASE(`memberID`) FROM `membership_userrecords` WHERE `tableName`='manufacturer' AND `pkValue`='" . makeSafe($selected_id) . "'");

		if($arrPerm['view'] == 1 && getLoggedMemberID() != $ownerMemberID) return $Translation['tableAccessDenied'];
		if($arrPerm['view'] == 2 && getLoggedGroupID() != $ownerGroupID) return $Translation['tableAccessDenied'];

		// can edit?
		$AllowUpdate = 0;
		if(($arrPerm['edit'] == 1 && $ownerMemberID == getLoggedMemberID()) || ($arrPerm['edit'] == 2 && $ownerGroupID == getLoggedGroupID()) || $arrPerm['edit'] == 3) {
			$AllowUpdate = 1;
		}

		$res = sql("SELECT * FROM `manufacturer` WHERE `manufacturer_id`='" . makeSafe($selected_id) . "'", $eo);
		if(!($row = db_fetch_array($res))) {
			return error_message($Translation['No records found'], 'manufacturer_view.php', false);
		}
		$combo_manufacturer_type->SelectedData = $row['manufacturer_type'];
		$urow = $row; /* unsanitized data */
		$row = array_map('safe_html', $row);
	} else {
		$filterField = Request::val('FilterField');
		$filterOperator = Request::val('FilterOperator');
		$filterValue = Request::val('FilterValue');
		$combo_manufacturer_type->SelectedData = $filterer_manufacturer_type;
	}
	$combo_manufacturer_type->HTML = '<span id="manufacturer_type-container' . $rnd1 . '"></span><input type="hidden" name="manufacturer_type" id="manufacturer_type' . $rnd1 . '" value="' . html_attr($combo_manufacturer_type->SelectedData) . '">';
	$combo_manufacturer_type->MatchText = '<span id="manufacturer_type-container-readonly' . $rnd1 . '"></span><input type="hidden" name="manufacturer_type" id="manufacturer_type' . $rnd1 . '" value="' . html_attr($combo_manufacturer_type->SelectedData) . '">';

	ob_start();
	?>

	<script>
		// initial lookup values
		AppGini.current_manufacturer_type__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['manufacturer_type'] : htmlspecialchars($filterer_manufacturer_type, ENT_QUOTES)); ?>"};

		jQuery(function() {
			setTimeout(function() {
				if(typeof(manufacturer_type_reload__RAND__) == 'function') manufacturer_type_reload__RAND__();
			}, 50); /* we need to slightly delay client-side execution of the above code to allow AppGini.ajaxCache to work */
		});
		function manufacturer_type_reload__RAND__() {
		<?php if(($AllowUpdate || ($arrPerm['insert'] && !$selected_id)) && !$dvprint) { ?>

			$j("#manufacturer_type-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_manufacturer_type__RAND__.value, t: 'manufacturer', f: 'manufacturer_type' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="manufacturer_type"]').val(resp.results[0].id);
							$j('[id=manufacturer_type-container-readonly__RAND__]').html('<span class="match-text" id="manufacturer_type-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=manufacturer_type_view_parent]').hide(); } else { $j('.btn[id=manufacturer_type_view_parent]').show(); }


							if(typeof(manufacturer_type_update_autofills__RAND__) == 'function') manufacturer_type_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'manufacturer', f: 'manufacturer_type' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_manufacturer_type__RAND__.value = e.added.id;
				AppGini.current_manufacturer_type__RAND__.text = e.added.text;
				$j('[name="manufacturer_type"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=manufacturer_type_view_parent]').hide(); } else { $j('.btn[id=manufacturer_type_view_parent]').show(); }


				if(typeof(manufacturer_type_update_autofills__RAND__) == 'function') manufacturer_type_update_autofills__RAND__();
			});

			if(!$j("#manufacturer_type-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_manufacturer_type__RAND__.value, t: 'manufacturer', f: 'manufacturer_type' },
					success: function(resp) {
						$j('[name="manufacturer_type"]').val(resp.results[0].id);
						$j('[id=manufacturer_type-container-readonly__RAND__]').html('<span class="match-text" id="manufacturer_type-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=manufacturer_type_view_parent]').hide(); } else { $j('.btn[id=manufacturer_type_view_parent]').show(); }

						if(typeof(manufacturer_type_update_autofills__RAND__) == 'function') manufacturer_type_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_manufacturer_type__RAND__.value, t: 'manufacturer', f: 'manufacturer_type' },
				success: function(resp) {
					$j('[id=manufacturer_type-container__RAND__], [id=manufacturer_type-container-readonly__RAND__]').html('<span class="match-text" id="manufacturer_type-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=manufacturer_type_view_parent]').hide(); } else { $j('.btn[id=manufacturer_type_view_parent]').show(); }

					if(typeof(manufacturer_type_update_autofills__RAND__) == 'function') manufacturer_type_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_clean());


	// code for template based detail view forms

	// open the detail view template
	if($dvprint) {
		$template_file = is_file("./{$TemplateDVP}") ? "./{$TemplateDVP}" : './templates/manufacturer_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	} else {
		$template_file = is_file("./{$TemplateDV}") ? "./{$TemplateDV}" : './templates/manufacturer_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Manufacturer Details:', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', (Request::val('Embedded') ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($arrPerm['insert'] && !$selected_id) { // allow insert and no record selected?
		if(!$selected_id) $templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return manufacturer_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return manufacturer_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if(Request::val('Embedded')) {
		$backAction = 'AppGini.closeParentModal(); return false;';
	} else {
		$backAction = '$j(\'form\').eq(0).attr(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id) {
		if(!Request::val('Embedded')) $templateCode = str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$j(\'form\').eq(0).prop(\'novalidate\', true); document.myform.reset(); return true;" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($AllowUpdate) {
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return manufacturer_validateData();" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		} else {
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		}
		if(($arrPerm['delete'] == 1 && $ownerMemberID == getLoggedMemberID()) || ($arrPerm['delete'] == 2 && $ownerGroupID == getLoggedGroupID()) || $arrPerm['delete'] == 3) { // allow delete?
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" onclick="return confirm(\'' . $Translation['are you sure?'] . '\');" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		} else {
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);

		// if not in embedded mode and user has insert only but no view/update/delete,
		// remove 'back' button
		if(
			$arrPerm['insert']
			&& !$arrPerm['update'] && !$arrPerm['delete'] && !$arrPerm['view']
			&& !Request::val('Embedded')
		)
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
		elseif($separateDV)
			$templateCode = str_replace(
				'<%%DESELECT_BUTTON%%>', 
				'<button
					type="submit" 
					class="btn btn-default" 
					id="deselect" 
					name="deselect_x" 
					value="1" 
					onclick="' . $backAction . '" 
					title="' . html_attr($Translation['Back']) . '">
						<i class="glyphicon glyphicon-chevron-left"></i> ' .
						$Translation['Back'] .
				'</button>',
				$templateCode
			);
		else
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate) || (!$selected_id && !$AllowInsert)) {
		$jsReadOnly = '';
		$jsReadOnly .= "\tjQuery('#manufacturer_type').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#manufacturer_type_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#manufacturer_name').replaceWith('<div class=\"form-control-static\" id=\"manufacturer_name\">' + (jQuery('#manufacturer_name').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#contact_person').replaceWith('<div class=\"form-control-static\" id=\"contact_person\">' + (jQuery('#contact_person').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#contact_details').replaceWith('<div class=\"form-control-static\" id=\"contact_details\">' + (jQuery('#contact_details').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#contact_email').replaceWith('<div class=\"form-control-static\" id=\"contact_email\">' + (jQuery('#contact_email').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#contact_email, #contact_email-edit-link').hide();\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	} elseif(($AllowInsert && !$selected_id) || ($AllowUpdate && $selected_id)) {
		$jsEditable = "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode = str_replace('<%%COMBO(manufacturer_type)%%>', $combo_manufacturer_type->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(manufacturer_type)%%>', $combo_manufacturer_type->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(manufacturer_type)%%>', urlencode($combo_manufacturer_type->MatchText), $templateCode);

	/* lookup fields array: 'lookup field name' => ['parent table name', 'lookup field caption'] */
	$lookup_fields = ['manufacturer_type' => ['manufacturer_type', 'Manufacturer Type:'], ];
	foreach($lookup_fields as $luf => $ptfc) {
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if($pt_perm['view'] || $pt_perm['edit']) {
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] /* && !Request::val('Embedded')*/) {
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-default add_new_parent" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus text-success"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(manufacturer_id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(manufacturer_type)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(manufacturer_name)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(contact_person)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(contact_details)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(contact_email)%%>', '', $templateCode);

	// process values
	if($selected_id) {
		if( $dvprint) $templateCode = str_replace('<%%VALUE(manufacturer_id)%%>', safe_html($urow['manufacturer_id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(manufacturer_id)%%>', html_attr($row['manufacturer_id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(manufacturer_id)%%>', urlencode($urow['manufacturer_id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(manufacturer_type)%%>', safe_html($urow['manufacturer_type']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(manufacturer_type)%%>', html_attr($row['manufacturer_type']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(manufacturer_type)%%>', urlencode($urow['manufacturer_type']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(manufacturer_name)%%>', safe_html($urow['manufacturer_name']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(manufacturer_name)%%>', html_attr($row['manufacturer_name']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(manufacturer_name)%%>', urlencode($urow['manufacturer_name']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(contact_person)%%>', safe_html($urow['contact_person']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(contact_person)%%>', html_attr($row['contact_person']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(contact_person)%%>', urlencode($urow['contact_person']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(contact_details)%%>', safe_html($urow['contact_details']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(contact_details)%%>', html_attr($row['contact_details']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(contact_details)%%>', urlencode($urow['contact_details']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(contact_email)%%>', safe_html($urow['contact_email']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(contact_email)%%>', html_attr($row['contact_email']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(contact_email)%%>', urlencode($urow['contact_email']), $templateCode);
	} else {
		$templateCode = str_replace('<%%VALUE(manufacturer_id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(manufacturer_id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(manufacturer_type)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(manufacturer_type)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(manufacturer_name)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(manufacturer_name)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(contact_person)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(contact_person)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(contact_details)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(contact_details)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(contact_email)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(contact_email)%%>', urlencode(''), $templateCode);
	}

	// process translations
	$templateCode = parseTemplate($templateCode);

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if(Request::val('dvprint_x') == '') {
		$templateCode .= "\n\n<script>\$j(function() {\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption) {
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id) {
			$templateCode.="\n\tif(document.getElementById('contact_emailEdit')) { document.getElementById('contact_emailEdit').style.display='inline'; }";
			$templateCode.="\n\tif(document.getElementById('contact_emailEditLink')) { document.getElementById('contact_emailEditLink').style.display='none'; }";
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields
	$filterField = Request::val('FilterField');
	$filterOperator = Request::val('FilterOperator');
	$filterValue = Request::val('FilterValue');

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('manufacturer');
	if($selected_id) {
		$jdata = get_joined_record('manufacturer', $selected_id);
		if($jdata === false) $jdata = get_defaults('manufacturer');
		$rdata = $row;
	}
	$templateCode .= loadView('manufacturer-ajax-cache', ['rdata' => $rdata, 'jdata' => $jdata]);

	// hook: manufacturer_dv
	if(function_exists('manufacturer_dv')) {
		$args = [];
		manufacturer_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}