<?php
// This script and data application were generated by AppGini 22.13
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/modification_to_vehicle.php');
	include_once(__DIR__ . '/modification_to_vehicle_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('modification_to_vehicle');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'modification_to_vehicle';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`modification_to_vehicle`.`modification_id`" => "modification_id",
		"IF(    CHAR_LENGTH(`body_type1`.`type_of_vehicle`), CONCAT_WS('',   `body_type1`.`type_of_vehicle`), '') /* Type of Vehicle: */" => "type_of_vehicle",
		"`modification_to_vehicle`.`directorate`" => "directorate",
		"`modification_to_vehicle`.`head_office`" => "head_office",
		"IF(    CHAR_LENGTH(`districts1`.`district`), CONCAT_WS('',   `districts1`.`district`), '') /* District: */" => "district",
		"IF(    CHAR_LENGTH(`districts1`.`station`), CONCAT_WS('',   `districts1`.`station`, '   |  and   |   '), '') /* Station: */" => "location",
		"IF(    CHAR_LENGTH(`driver1`.`drivers_name_and_surname`) || CHAR_LENGTH(`driver1`.`drivers_email_address`), CONCAT_WS('',   `driver1`.`drivers_name_and_surname`, '   |  and   |  ', `driver1`.`drivers_email_address`), '') /* Driver\'s Name & Surname: */" => "drivers_name_and_surname",
		"IF(    CHAR_LENGTH(`driver1`.`drivers_persal_number`), CONCAT_WS('',   `driver1`.`drivers_persal_number`), '') /* Driver\'s Persal Number: */" => "drivers_persal_number",
		"IF(    CHAR_LENGTH(`driver1`.`drivers_contact_details`) || CHAR_LENGTH(`driver1`.`drivers_email_address`), CONCAT_WS('',   `driver1`.`drivers_contact_details`, '    |   and    | ', `driver1`.`drivers_email_address`), '') /* Driver\'s Contact Details: */" => "drivers_contact_details",
		"`modification_to_vehicle`.`driver_rank`" => "driver_rank",
		"`modification_to_vehicle`.`driver_signature`" => "driver_signature",
		"IF(    CHAR_LENGTH(`gmt_fleet_register1`.`vehicle_registration_number`) || CHAR_LENGTH(`gmt_fleet_register1`.`chassis_number`), CONCAT_WS('',   `gmt_fleet_register1`.`vehicle_registration_number`, '   |  and  |   ', `gmt_fleet_register1`.`chassis_number`), '') /* Registration Number: */" => "vehicle_registration_number",
		"IF(    CHAR_LENGTH(`dealer1`.`make_of_vehicle`) || CHAR_LENGTH(`gmt_fleet_register1`.`model_of_vehicle`), CONCAT_WS('',   `dealer1`.`make_of_vehicle`, '   ', '   |  and  |   ', `gmt_fleet_register1`.`model_of_vehicle`), '') /* Make of Vehicle: */" => "make_of_vehicle",
		"IF(    CHAR_LENGTH(`gmt_fleet_register1`.`model_of_vehicle`) || CHAR_LENGTH(`gmt_fleet_register1`.`chassis_number`), CONCAT_WS('',   `gmt_fleet_register1`.`model_of_vehicle`, '   |  and  |   ', `gmt_fleet_register1`.`chassis_number`), '') /* Model of Vehicle: */" => "model_of_vehicle",
		"IF(    CHAR_LENGTH(`log_sheet1`.`closing_km`), CONCAT_WS('',   `log_sheet1`.`closing_km`), '') /* Closing KM: */" => "closing_km",
		"IF(    CHAR_LENGTH(`service1`.`job_card_number`), CONCAT_WS('',   `service1`.`job_card_number`), '') /* Job Card Number: */" => "job_card_number",
		"`modification_to_vehicle`.`objective`" => "objective",
		"`modification_to_vehicle`.`fuel_gauge_amount`" => "fuel_gauge_amount",
		"`modification_to_vehicle`.`keys_ignition`" => "keys_ignition",
		"`modification_to_vehicle`.`petrol_cap_with_keys`" => "petrol_cap_with_keys",
		"`modification_to_vehicle`.`padlock_with_keys`" => "padlock_with_keys",
		"`modification_to_vehicle`.`tyre_r_f`" => "tyre_r_f",
		"`modification_to_vehicle`.`tyre_r_f_1`" => "tyre_r_f_1",
		"`modification_to_vehicle`.`tyre_r_r`" => "tyre_r_r",
		"`modification_to_vehicle`.`tyre_r_r_1`" => "tyre_r_r_1",
		"`modification_to_vehicle`.`tyre_l_f`" => "tyre_l_f",
		"`modification_to_vehicle`.`tyre_l_f_1`" => "tyre_l_f_1",
		"`modification_to_vehicle`.`tyer_l_r`" => "tyer_l_r",
		"`modification_to_vehicle`.`tyer_l_r_1`" => "tyer_l_r_1",
		"`modification_to_vehicle`.`tyre_spare`" => "tyre_spare",
		"`modification_to_vehicle`.`tyre_spare_1`" => "tyre_spare_1",
		"`modification_to_vehicle`.`wheel_cups`" => "wheel_cups",
		"`modification_to_vehicle`.`other`" => "other",
		"`modification_to_vehicle`.`battery`" => "battery",
		"`modification_to_vehicle`.`battery_voltage`" => "battery_voltage",
		"`modification_to_vehicle`.`wheel_spanner`" => "wheel_spanner",
		"`modification_to_vehicle`.`jack_with_handle`" => "jack_with_handle",
		"`modification_to_vehicle`.`radio_dvd_combination`" => "radio_dvd_combination",
		"`modification_to_vehicle`.`petrol_card`" => "petrol_card",
		"`modification_to_vehicle`.`valid_license_disc`" => "valid_license_disc",
		"if(`modification_to_vehicle`.`valid_license_disc_date`,date_format(`modification_to_vehicle`.`valid_license_disc_date`,'%d/%m/%Y'),'')" => "valid_license_disc_date",
		"`modification_to_vehicle`.`fire_extinguisher`" => "fire_extinguisher",
		"`modification_to_vehicle`.`warning_signs_traingle`" => "warning_signs_traingle",
		"if(`modification_to_vehicle`.`date_checked_in`,date_format(`modification_to_vehicle`.`date_checked_in`,'%d/%m/%Y %H:%i'),'')" => "date_checked_in",
		"`modification_to_vehicle`.`testing_officer_name_and_surname`" => "testing_officer_name_and_surname",
		"`modification_to_vehicle`.`testing_officer_persal_number`" => "testing_officer_persal_number",
		"`modification_to_vehicle`.`testing_officer_rank`" => "testing_officer_rank",
		"`modification_to_vehicle`.`testing_officer_signature`" => "testing_officer_signature",
		"if(`modification_to_vehicle`.`date_received`,date_format(`modification_to_vehicle`.`date_received`,'%d/%m/%Y %H:%i'),'')" => "date_received",
		"`modification_to_vehicle`.`supervisor_for_allocation_name_and_surname`" => "supervisor_for_allocation_name_and_surname",
		"`modification_to_vehicle`.`supervisor_for_allocation_persal_number`" => "supervisor_for_allocation_persal_number",
		"`modification_to_vehicle`.`supervisor_for_allocation_rank`" => "supervisor_for_allocation_rank",
		"`modification_to_vehicle`.`supervisor_for_allocation_signature`" => "supervisor_for_allocation_signature",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`modification_to_vehicle`.`modification_id`',
		2 => '`body_type1`.`type_of_vehicle`',
		3 => 3,
		4 => 4,
		5 => '`districts1`.`district`',
		6 => 6,
		7 => 7,
		8 => '`driver1`.`drivers_persal_number`',
		9 => 9,
		10 => 10,
		11 => 11,
		12 => 12,
		13 => 13,
		14 => 14,
		15 => '`log_sheet1`.`closing_km`',
		16 => 16,
		17 => 17,
		18 => 18,
		19 => 19,
		20 => 20,
		21 => 21,
		22 => 22,
		23 => 23,
		24 => 24,
		25 => 25,
		26 => 26,
		27 => 27,
		28 => 28,
		29 => 29,
		30 => 30,
		31 => 31,
		32 => 32,
		33 => 33,
		34 => 34,
		35 => 35,
		36 => 36,
		37 => 37,
		38 => 38,
		39 => 39,
		40 => 40,
		41 => '`modification_to_vehicle`.`valid_license_disc_date`',
		42 => 42,
		43 => 43,
		44 => '`modification_to_vehicle`.`date_checked_in`',
		45 => 45,
		46 => 46,
		47 => 47,
		48 => 48,
		49 => '`modification_to_vehicle`.`date_received`',
		50 => 50,
		51 => 51,
		52 => 52,
		53 => 53,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`modification_to_vehicle`.`modification_id`" => "modification_id",
		"IF(    CHAR_LENGTH(`body_type1`.`type_of_vehicle`), CONCAT_WS('',   `body_type1`.`type_of_vehicle`), '') /* Type of Vehicle: */" => "type_of_vehicle",
		"`modification_to_vehicle`.`directorate`" => "directorate",
		"`modification_to_vehicle`.`head_office`" => "head_office",
		"IF(    CHAR_LENGTH(`districts1`.`district`), CONCAT_WS('',   `districts1`.`district`), '') /* District: */" => "district",
		"IF(    CHAR_LENGTH(`districts1`.`station`), CONCAT_WS('',   `districts1`.`station`, '   |  and   |   '), '') /* Station: */" => "location",
		"IF(    CHAR_LENGTH(`driver1`.`drivers_name_and_surname`) || CHAR_LENGTH(`driver1`.`drivers_email_address`), CONCAT_WS('',   `driver1`.`drivers_name_and_surname`, '   |  and   |  ', `driver1`.`drivers_email_address`), '') /* Driver\'s Name & Surname: */" => "drivers_name_and_surname",
		"IF(    CHAR_LENGTH(`driver1`.`drivers_persal_number`), CONCAT_WS('',   `driver1`.`drivers_persal_number`), '') /* Driver\'s Persal Number: */" => "drivers_persal_number",
		"IF(    CHAR_LENGTH(`driver1`.`drivers_contact_details`) || CHAR_LENGTH(`driver1`.`drivers_email_address`), CONCAT_WS('',   `driver1`.`drivers_contact_details`, '    |   and    | ', `driver1`.`drivers_email_address`), '') /* Driver\'s Contact Details: */" => "drivers_contact_details",
		"`modification_to_vehicle`.`driver_rank`" => "driver_rank",
		"`modification_to_vehicle`.`driver_signature`" => "driver_signature",
		"IF(    CHAR_LENGTH(`gmt_fleet_register1`.`vehicle_registration_number`) || CHAR_LENGTH(`gmt_fleet_register1`.`chassis_number`), CONCAT_WS('',   `gmt_fleet_register1`.`vehicle_registration_number`, '   |  and  |   ', `gmt_fleet_register1`.`chassis_number`), '') /* Registration Number: */" => "vehicle_registration_number",
		"IF(    CHAR_LENGTH(`dealer1`.`make_of_vehicle`) || CHAR_LENGTH(`gmt_fleet_register1`.`model_of_vehicle`), CONCAT_WS('',   `dealer1`.`make_of_vehicle`, '   ', '   |  and  |   ', `gmt_fleet_register1`.`model_of_vehicle`), '') /* Make of Vehicle: */" => "make_of_vehicle",
		"IF(    CHAR_LENGTH(`gmt_fleet_register1`.`model_of_vehicle`) || CHAR_LENGTH(`gmt_fleet_register1`.`chassis_number`), CONCAT_WS('',   `gmt_fleet_register1`.`model_of_vehicle`, '   |  and  |   ', `gmt_fleet_register1`.`chassis_number`), '') /* Model of Vehicle: */" => "model_of_vehicle",
		"IF(    CHAR_LENGTH(`log_sheet1`.`closing_km`), CONCAT_WS('',   `log_sheet1`.`closing_km`), '') /* Closing KM: */" => "closing_km",
		"IF(    CHAR_LENGTH(`service1`.`job_card_number`), CONCAT_WS('',   `service1`.`job_card_number`), '') /* Job Card Number: */" => "job_card_number",
		"`modification_to_vehicle`.`objective`" => "objective",
		"`modification_to_vehicle`.`fuel_gauge_amount`" => "fuel_gauge_amount",
		"`modification_to_vehicle`.`keys_ignition`" => "keys_ignition",
		"`modification_to_vehicle`.`petrol_cap_with_keys`" => "petrol_cap_with_keys",
		"`modification_to_vehicle`.`padlock_with_keys`" => "padlock_with_keys",
		"`modification_to_vehicle`.`tyre_r_f`" => "tyre_r_f",
		"`modification_to_vehicle`.`tyre_r_f_1`" => "tyre_r_f_1",
		"`modification_to_vehicle`.`tyre_r_r`" => "tyre_r_r",
		"`modification_to_vehicle`.`tyre_r_r_1`" => "tyre_r_r_1",
		"`modification_to_vehicle`.`tyre_l_f`" => "tyre_l_f",
		"`modification_to_vehicle`.`tyre_l_f_1`" => "tyre_l_f_1",
		"`modification_to_vehicle`.`tyer_l_r`" => "tyer_l_r",
		"`modification_to_vehicle`.`tyer_l_r_1`" => "tyer_l_r_1",
		"`modification_to_vehicle`.`tyre_spare`" => "tyre_spare",
		"`modification_to_vehicle`.`tyre_spare_1`" => "tyre_spare_1",
		"`modification_to_vehicle`.`wheel_cups`" => "wheel_cups",
		"`modification_to_vehicle`.`other`" => "other",
		"`modification_to_vehicle`.`battery`" => "battery",
		"`modification_to_vehicle`.`battery_voltage`" => "battery_voltage",
		"`modification_to_vehicle`.`wheel_spanner`" => "wheel_spanner",
		"`modification_to_vehicle`.`jack_with_handle`" => "jack_with_handle",
		"`modification_to_vehicle`.`radio_dvd_combination`" => "radio_dvd_combination",
		"`modification_to_vehicle`.`petrol_card`" => "petrol_card",
		"`modification_to_vehicle`.`valid_license_disc`" => "valid_license_disc",
		"if(`modification_to_vehicle`.`valid_license_disc_date`,date_format(`modification_to_vehicle`.`valid_license_disc_date`,'%d/%m/%Y'),'')" => "valid_license_disc_date",
		"`modification_to_vehicle`.`fire_extinguisher`" => "fire_extinguisher",
		"`modification_to_vehicle`.`warning_signs_traingle`" => "warning_signs_traingle",
		"if(`modification_to_vehicle`.`date_checked_in`,date_format(`modification_to_vehicle`.`date_checked_in`,'%d/%m/%Y %H:%i'),'')" => "date_checked_in",
		"`modification_to_vehicle`.`testing_officer_name_and_surname`" => "testing_officer_name_and_surname",
		"`modification_to_vehicle`.`testing_officer_persal_number`" => "testing_officer_persal_number",
		"`modification_to_vehicle`.`testing_officer_rank`" => "testing_officer_rank",
		"`modification_to_vehicle`.`testing_officer_signature`" => "testing_officer_signature",
		"if(`modification_to_vehicle`.`date_received`,date_format(`modification_to_vehicle`.`date_received`,'%d/%m/%Y %H:%i'),'')" => "date_received",
		"`modification_to_vehicle`.`supervisor_for_allocation_name_and_surname`" => "supervisor_for_allocation_name_and_surname",
		"`modification_to_vehicle`.`supervisor_for_allocation_persal_number`" => "supervisor_for_allocation_persal_number",
		"`modification_to_vehicle`.`supervisor_for_allocation_rank`" => "supervisor_for_allocation_rank",
		"`modification_to_vehicle`.`supervisor_for_allocation_signature`" => "supervisor_for_allocation_signature",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`modification_to_vehicle`.`modification_id`" => "Modification ID:",
		"IF(    CHAR_LENGTH(`body_type1`.`type_of_vehicle`), CONCAT_WS('',   `body_type1`.`type_of_vehicle`), '') /* Type of Vehicle: */" => "Type of Vehicle:",
		"`modification_to_vehicle`.`directorate`" => "Directorate:",
		"`modification_to_vehicle`.`head_office`" => "Head Office:",
		"IF(    CHAR_LENGTH(`districts1`.`district`), CONCAT_WS('',   `districts1`.`district`), '') /* District: */" => "District:",
		"IF(    CHAR_LENGTH(`districts1`.`station`), CONCAT_WS('',   `districts1`.`station`, '   |  and   |   '), '') /* Station: */" => "Station:",
		"IF(    CHAR_LENGTH(`driver1`.`drivers_name_and_surname`) || CHAR_LENGTH(`driver1`.`drivers_email_address`), CONCAT_WS('',   `driver1`.`drivers_name_and_surname`, '   |  and   |  ', `driver1`.`drivers_email_address`), '') /* Driver\'s Name & Surname: */" => "Driver\'s Name & Surname:",
		"IF(    CHAR_LENGTH(`driver1`.`drivers_persal_number`), CONCAT_WS('',   `driver1`.`drivers_persal_number`), '') /* Driver\'s Persal Number: */" => "Driver\'s Persal Number:",
		"IF(    CHAR_LENGTH(`driver1`.`drivers_contact_details`) || CHAR_LENGTH(`driver1`.`drivers_email_address`), CONCAT_WS('',   `driver1`.`drivers_contact_details`, '    |   and    | ', `driver1`.`drivers_email_address`), '') /* Driver\'s Contact Details: */" => "Driver\'s Contact Details:",
		"`modification_to_vehicle`.`driver_rank`" => "Driver Rank/Designation:",
		"IF(    CHAR_LENGTH(`gmt_fleet_register1`.`vehicle_registration_number`) || CHAR_LENGTH(`gmt_fleet_register1`.`chassis_number`), CONCAT_WS('',   `gmt_fleet_register1`.`vehicle_registration_number`, '   |  and  |   ', `gmt_fleet_register1`.`chassis_number`), '') /* Registration Number: */" => "Registration Number:",
		"IF(    CHAR_LENGTH(`dealer1`.`make_of_vehicle`) || CHAR_LENGTH(`gmt_fleet_register1`.`model_of_vehicle`), CONCAT_WS('',   `dealer1`.`make_of_vehicle`, '   ', '   |  and  |   ', `gmt_fleet_register1`.`model_of_vehicle`), '') /* Make of Vehicle: */" => "Make of Vehicle:",
		"IF(    CHAR_LENGTH(`gmt_fleet_register1`.`model_of_vehicle`) || CHAR_LENGTH(`gmt_fleet_register1`.`chassis_number`), CONCAT_WS('',   `gmt_fleet_register1`.`model_of_vehicle`, '   |  and  |   ', `gmt_fleet_register1`.`chassis_number`), '') /* Model of Vehicle: */" => "Model of Vehicle:",
		"IF(    CHAR_LENGTH(`log_sheet1`.`closing_km`), CONCAT_WS('',   `log_sheet1`.`closing_km`), '') /* Closing KM: */" => "Closing KM:",
		"IF(    CHAR_LENGTH(`service1`.`job_card_number`), CONCAT_WS('',   `service1`.`job_card_number`), '') /* Job Card Number: */" => "Job Card Number:",
		"`modification_to_vehicle`.`objective`" => "Objective:",
		"`modification_to_vehicle`.`fuel_gauge_amount`" => "Fuel Gauge Amount:",
		"`modification_to_vehicle`.`keys_ignition`" => "Keys/Ignition:",
		"`modification_to_vehicle`.`petrol_cap_with_keys`" => "Petrol Cap with Keys:",
		"`modification_to_vehicle`.`padlock_with_keys`" => "Padlock with Keys:",
		"`modification_to_vehicle`.`tyre_r_f`" => "Tyre R/F (Available):",
		"`modification_to_vehicle`.`tyre_r_f_1`" => "Tyre R/F (Thread Condition):",
		"`modification_to_vehicle`.`tyre_r_r`" => "Tyre R/R (Available):",
		"`modification_to_vehicle`.`tyre_r_r_1`" => "Tyre R/R (Thread Condition):",
		"`modification_to_vehicle`.`tyre_l_f`" => "Tyre L/F (Available):",
		"`modification_to_vehicle`.`tyre_l_f_1`" => "Tyre L/F (Thread Condition):",
		"`modification_to_vehicle`.`tyer_l_r`" => "Tyre L/R (Available):",
		"`modification_to_vehicle`.`tyer_l_r_1`" => "Tyre L/R (Thread Condition):",
		"`modification_to_vehicle`.`tyre_spare`" => "Tyre Spare (Available):",
		"`modification_to_vehicle`.`tyre_spare_1`" => "Tyre Spare (Thread Condition):",
		"`modification_to_vehicle`.`wheel_cups`" => "Wheel Hub Cups (Available):",
		"`modification_to_vehicle`.`other`" => "Other (specify):",
		"`modification_to_vehicle`.`battery`" => "Battery (Make):",
		"`modification_to_vehicle`.`battery_voltage`" => "Battery (Voltage):",
		"`modification_to_vehicle`.`wheel_spanner`" => "Wheel Spanner:",
		"`modification_to_vehicle`.`jack_with_handle`" => "Jack with Handle:",
		"`modification_to_vehicle`.`radio_dvd_combination`" => "Radio/DVD Combination:",
		"`modification_to_vehicle`.`petrol_card`" => "Petrol Card:",
		"`modification_to_vehicle`.`valid_license_disc`" => "Valid License Disc:",
		"`modification_to_vehicle`.`valid_license_disc_date`" => "Valid License Disc (Expire date):",
		"`modification_to_vehicle`.`fire_extinguisher`" => "Fire Extinguisher:",
		"`modification_to_vehicle`.`warning_signs_traingle`" => "Warning Signs & Traingle:",
		"`modification_to_vehicle`.`date_checked_in`" => "Declaration Date & Time:",
		"`modification_to_vehicle`.`testing_officer_name_and_surname`" => "Testing Officer/Tradesman Aid Details:",
		"`modification_to_vehicle`.`testing_officer_persal_number`" => "Testing Officer/Tradesman Aid Persal Number:",
		"`modification_to_vehicle`.`testing_officer_rank`" => "Testing Officer/Tradesman Aid Rank/Designation:",
		"`modification_to_vehicle`.`date_received`" => "Declaration Date & Time (Vehicle Received):",
		"`modification_to_vehicle`.`supervisor_for_allocation_name_and_surname`" => "Supervisor for Allocation Details:",
		"`modification_to_vehicle`.`supervisor_for_allocation_persal_number`" => "Supervisor for Allocation Persal Number:",
		"`modification_to_vehicle`.`supervisor_for_allocation_rank`" => "Supervisor for Allocation Rank/Designation:",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`modification_to_vehicle`.`modification_id`" => "modification_id",
		"IF(    CHAR_LENGTH(`body_type1`.`type_of_vehicle`), CONCAT_WS('',   `body_type1`.`type_of_vehicle`), '') /* Type of Vehicle: */" => "type_of_vehicle",
		"`modification_to_vehicle`.`directorate`" => "directorate",
		"`modification_to_vehicle`.`head_office`" => "head_office",
		"IF(    CHAR_LENGTH(`districts1`.`district`), CONCAT_WS('',   `districts1`.`district`), '') /* District: */" => "district",
		"IF(    CHAR_LENGTH(`districts1`.`station`), CONCAT_WS('',   `districts1`.`station`, '   |  and   |   '), '') /* Station: */" => "location",
		"IF(    CHAR_LENGTH(`driver1`.`drivers_name_and_surname`) || CHAR_LENGTH(`driver1`.`drivers_email_address`), CONCAT_WS('',   `driver1`.`drivers_name_and_surname`, '   |  and   |  ', `driver1`.`drivers_email_address`), '') /* Driver\'s Name & Surname: */" => "drivers_name_and_surname",
		"IF(    CHAR_LENGTH(`driver1`.`drivers_persal_number`), CONCAT_WS('',   `driver1`.`drivers_persal_number`), '') /* Driver\'s Persal Number: */" => "drivers_persal_number",
		"IF(    CHAR_LENGTH(`driver1`.`drivers_contact_details`) || CHAR_LENGTH(`driver1`.`drivers_email_address`), CONCAT_WS('',   `driver1`.`drivers_contact_details`, '    |   and    | ', `driver1`.`drivers_email_address`), '') /* Driver\'s Contact Details: */" => "drivers_contact_details",
		"`modification_to_vehicle`.`driver_rank`" => "driver_rank",
		"IF(    CHAR_LENGTH(`gmt_fleet_register1`.`vehicle_registration_number`) || CHAR_LENGTH(`gmt_fleet_register1`.`chassis_number`), CONCAT_WS('',   `gmt_fleet_register1`.`vehicle_registration_number`, '   |  and  |   ', `gmt_fleet_register1`.`chassis_number`), '') /* Registration Number: */" => "vehicle_registration_number",
		"IF(    CHAR_LENGTH(`dealer1`.`make_of_vehicle`) || CHAR_LENGTH(`gmt_fleet_register1`.`model_of_vehicle`), CONCAT_WS('',   `dealer1`.`make_of_vehicle`, '   ', '   |  and  |   ', `gmt_fleet_register1`.`model_of_vehicle`), '') /* Make of Vehicle: */" => "make_of_vehicle",
		"IF(    CHAR_LENGTH(`gmt_fleet_register1`.`model_of_vehicle`) || CHAR_LENGTH(`gmt_fleet_register1`.`chassis_number`), CONCAT_WS('',   `gmt_fleet_register1`.`model_of_vehicle`, '   |  and  |   ', `gmt_fleet_register1`.`chassis_number`), '') /* Model of Vehicle: */" => "model_of_vehicle",
		"IF(    CHAR_LENGTH(`log_sheet1`.`closing_km`), CONCAT_WS('',   `log_sheet1`.`closing_km`), '') /* Closing KM: */" => "closing_km",
		"IF(    CHAR_LENGTH(`service1`.`job_card_number`), CONCAT_WS('',   `service1`.`job_card_number`), '') /* Job Card Number: */" => "job_card_number",
		"`modification_to_vehicle`.`objective`" => "objective",
		"`modification_to_vehicle`.`fuel_gauge_amount`" => "fuel_gauge_amount",
		"`modification_to_vehicle`.`keys_ignition`" => "keys_ignition",
		"`modification_to_vehicle`.`petrol_cap_with_keys`" => "petrol_cap_with_keys",
		"`modification_to_vehicle`.`padlock_with_keys`" => "padlock_with_keys",
		"`modification_to_vehicle`.`tyre_r_f`" => "tyre_r_f",
		"`modification_to_vehicle`.`tyre_r_f_1`" => "tyre_r_f_1",
		"`modification_to_vehicle`.`tyre_r_r`" => "tyre_r_r",
		"`modification_to_vehicle`.`tyre_r_r_1`" => "tyre_r_r_1",
		"`modification_to_vehicle`.`tyre_l_f`" => "tyre_l_f",
		"`modification_to_vehicle`.`tyre_l_f_1`" => "tyre_l_f_1",
		"`modification_to_vehicle`.`tyer_l_r`" => "tyer_l_r",
		"`modification_to_vehicle`.`tyer_l_r_1`" => "tyer_l_r_1",
		"`modification_to_vehicle`.`tyre_spare`" => "tyre_spare",
		"`modification_to_vehicle`.`tyre_spare_1`" => "tyre_spare_1",
		"`modification_to_vehicle`.`wheel_cups`" => "wheel_cups",
		"`modification_to_vehicle`.`other`" => "other",
		"`modification_to_vehicle`.`battery`" => "battery",
		"`modification_to_vehicle`.`battery_voltage`" => "battery_voltage",
		"`modification_to_vehicle`.`wheel_spanner`" => "wheel_spanner",
		"`modification_to_vehicle`.`jack_with_handle`" => "jack_with_handle",
		"`modification_to_vehicle`.`radio_dvd_combination`" => "radio_dvd_combination",
		"`modification_to_vehicle`.`petrol_card`" => "petrol_card",
		"`modification_to_vehicle`.`valid_license_disc`" => "valid_license_disc",
		"if(`modification_to_vehicle`.`valid_license_disc_date`,date_format(`modification_to_vehicle`.`valid_license_disc_date`,'%d/%m/%Y'),'')" => "valid_license_disc_date",
		"`modification_to_vehicle`.`fire_extinguisher`" => "fire_extinguisher",
		"`modification_to_vehicle`.`warning_signs_traingle`" => "warning_signs_traingle",
		"if(`modification_to_vehicle`.`date_checked_in`,date_format(`modification_to_vehicle`.`date_checked_in`,'%d/%m/%Y %H:%i'),'')" => "date_checked_in",
		"`modification_to_vehicle`.`testing_officer_name_and_surname`" => "testing_officer_name_and_surname",
		"`modification_to_vehicle`.`testing_officer_persal_number`" => "testing_officer_persal_number",
		"`modification_to_vehicle`.`testing_officer_rank`" => "testing_officer_rank",
		"if(`modification_to_vehicle`.`date_received`,date_format(`modification_to_vehicle`.`date_received`,'%d/%m/%Y %H:%i'),'')" => "date_received",
		"`modification_to_vehicle`.`supervisor_for_allocation_name_and_surname`" => "supervisor_for_allocation_name_and_surname",
		"`modification_to_vehicle`.`supervisor_for_allocation_persal_number`" => "supervisor_for_allocation_persal_number",
		"`modification_to_vehicle`.`supervisor_for_allocation_rank`" => "supervisor_for_allocation_rank",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = ['type_of_vehicle' => 'Type of Vehicle:', 'district' => 'District:', 'drivers_name_and_surname' => 'Driver\'s Name & Surname:', 'vehicle_registration_number' => 'Registration Number:', 'closing_km' => 'Closing KM:', 'job_card_number' => 'Job Card Number:', ];

	$x->QueryFrom = "`modification_to_vehicle` LEFT JOIN `body_type` as body_type1 ON `body_type1`.`body_type_id`=`modification_to_vehicle`.`type_of_vehicle` LEFT JOIN `districts` as districts1 ON `districts1`.`district_id`=`modification_to_vehicle`.`district` LEFT JOIN `driver` as driver1 ON `driver1`.`driver_id`=`modification_to_vehicle`.`drivers_name_and_surname` LEFT JOIN `gmt_fleet_register` as gmt_fleet_register1 ON `gmt_fleet_register1`.`fleet_asset_id`=`modification_to_vehicle`.`vehicle_registration_number` LEFT JOIN `log_sheet` as log_sheet1 ON `log_sheet1`.`fuel_log_sheet_id`=`modification_to_vehicle`.`closing_km` LEFT JOIN `service` as service1 ON `service1`.`service_id`=`modification_to_vehicle`.`job_card_number` LEFT JOIN `dealer` as dealer1 ON `dealer1`.`dealer_id`=`gmt_fleet_register1`.`make_of_vehicle` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 25;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'modification_to_vehicle_view.php';
	$x->RedirectAfterInsert = 'modification_to_vehicle_view.php?SelectedID=#ID#';
	$x->TableTitle = 'Modification to Vehicle:';
	$x->TableIcon = 'resources/table_icons/dimensions.png';
	$x->PrimaryKey = '`modification_to_vehicle`.`modification_id`';

	$x->ColWidth = [150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, ];
	$x->ColCaption = ['Modification ID:', 'Type of Vehicle:', 'Directorate:', 'Head Office:', 'District:', 'Station:', 'Driver\'s Name & Surname:', 'Driver\'s Persal Number:', 'Driver\'s Contact Details:', 'Driver Rank/Designation:', 'Driver Signature:', 'Registration Number:', 'Make of Vehicle:', 'Model of Vehicle:', 'Closing KM:', 'Job Card Number:', 'Objective:', 'Fuel Gauge Amount:', 'Keys/Ignition:', 'Petrol Cap with Keys:', 'Padlock with Keys:', 'Tyre R/F (Available):', 'Tyre R/F (Thread Condition):', 'Tyre R/R (Available):', 'Tyre R/R (Thread Condition):', 'Tyre L/F (Available):', 'Tyre L/F (Thread Condition):', 'Tyre L/R (Available):', 'Tyre L/R (Thread Condition):', 'Tyre Spare (Available):', 'Tyre Spare (Thread Condition):', 'Wheel Hub Cups (Available):', 'Other (specify):', 'Battery (Make):', 'Battery (Voltage):', 'Wheel Spanner:', 'Jack with Handle:', 'Radio/DVD Combination:', 'Petrol Card:', 'Valid License Disc:', 'Valid License Disc (Expire date):', 'Fire Extinguisher:', 'Warning Signs & Traingle:', 'Declaration Date & Time:', 'Testing Officer/Tradesman Aid Details:', 'Testing Officer/Tradesman Aid Persal Number:', 'Testing Officer/Tradesman Aid Rank/Designation:', 'Testing Officer/Tradesman Aid Signature:', 'Declaration Date & Time (Vehicle Received):', 'Supervisor for Allocation Details:', 'Supervisor for Allocation Persal Number:', 'Supervisor for Allocation Rank/Designation:', 'Supervisor for Allocation Signature:', ];
	$x->ColFieldName = ['modification_id', 'type_of_vehicle', 'directorate', 'head_office', 'district', 'location', 'drivers_name_and_surname', 'drivers_persal_number', 'drivers_contact_details', 'driver_rank', 'driver_signature', 'vehicle_registration_number', 'make_of_vehicle', 'model_of_vehicle', 'closing_km', 'job_card_number', 'objective', 'fuel_gauge_amount', 'keys_ignition', 'petrol_cap_with_keys', 'padlock_with_keys', 'tyre_r_f', 'tyre_r_f_1', 'tyre_r_r', 'tyre_r_r_1', 'tyre_l_f', 'tyre_l_f_1', 'tyer_l_r', 'tyer_l_r_1', 'tyre_spare', 'tyre_spare_1', 'wheel_cups', 'other', 'battery', 'battery_voltage', 'wheel_spanner', 'jack_with_handle', 'radio_dvd_combination', 'petrol_card', 'valid_license_disc', 'valid_license_disc_date', 'fire_extinguisher', 'warning_signs_traingle', 'date_checked_in', 'testing_officer_name_and_surname', 'testing_officer_persal_number', 'testing_officer_rank', 'testing_officer_signature', 'date_received', 'supervisor_for_allocation_name_and_surname', 'supervisor_for_allocation_persal_number', 'supervisor_for_allocation_rank', 'supervisor_for_allocation_signature', ];
	$x->ColNumber  = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/modification_to_vehicle_templateTV.html';
	$x->SelectedTemplate = 'templates/modification_to_vehicle_templateTVS.html';
	$x->TemplateDV = 'templates/modification_to_vehicle_templateDV.html';
	$x->TemplateDVP = 'templates/modification_to_vehicle_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: modification_to_vehicle_init
	$render = true;
	if(function_exists('modification_to_vehicle_init')) {
		$args = [];
		$render = modification_to_vehicle_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: modification_to_vehicle_header
	$headerCode = '';
	if(function_exists('modification_to_vehicle_header')) {
		$args = [];
		$headerCode = modification_to_vehicle_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: modification_to_vehicle_footer
	$footerCode = '';
	if(function_exists('modification_to_vehicle_footer')) {
		$args = [];
		$footerCode = modification_to_vehicle_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
