<?php
// This script and data application were generated by AppGini 22.13
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/service.php');
	include_once(__DIR__ . '/service_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('service');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'service';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`service`.`service_id`" => "service_id",
		"`service`.`breakdown_of_vehicle`" => "breakdown_of_vehicle",
		"`service`.`service_title`" => "service_title",
		"IF(    CHAR_LENGTH(`service_item_type1`.`service_item_type`), CONCAT_WS('',   `service_item_type1`.`service_item_type`), '') /* Service Item Type: */" => "service_item_type",
		"IF(    CHAR_LENGTH(`service_categories1`.`service_category`), CONCAT_WS('',   `service_categories1`.`service_category`), '') /* Service Category: */" => "service_category",
		"IF(    CHAR_LENGTH(`merchant1`.`merchant_name`) || CHAR_LENGTH(`merchant_type1`.`merchant_type`), CONCAT_WS('',   `merchant1`.`merchant_name`, '    |   and   |    ', `merchant_type1`.`merchant_type`), '') /* Merchant Name: */" => "merchant_name",
		"IF(    CHAR_LENGTH(`gmt_fleet_register1`.`vehicle_registration_number`), CONCAT_WS('',   `gmt_fleet_register1`.`vehicle_registration_number`), '') /* Registration Number: */" => "vehicle_registration_number",
		"IF(    CHAR_LENGTH(`gmt_fleet_register1`.`engine_number`), CONCAT_WS('',   `gmt_fleet_register1`.`engine_number`), '') /* Engine Number: */" => "engine_number",
		"IF(    CHAR_LENGTH(`gmt_fleet_register1`.`chassis_number`) || CHAR_LENGTH(`gmt_fleet_register1`.`vehicle_registration_number`), CONCAT_WS('',   `gmt_fleet_register1`.`chassis_number`, ' |  and  |     ', `gmt_fleet_register1`.`vehicle_registration_number`), '') /* Chassis Number: */" => "chassis_number",
		"IF(    CHAR_LENGTH(`dealer1`.`dealer_name`), CONCAT_WS('',   `dealer1`.`dealer_name`), '') /* Make of Vehicle/Dealer Name: */" => "dealer_name",
		"IF(    CHAR_LENGTH(`dealer1`.`make_of_vehicle`), CONCAT_WS('',   `dealer1`.`make_of_vehicle`, '   '), '') /* Make of Vehicle: */" => "make_of_vehicle",
		"IF(    CHAR_LENGTH(`gmt_fleet_register1`.`model_of_vehicle`), CONCAT_WS('',   `gmt_fleet_register1`.`model_of_vehicle`), '') /* Model of Vehicle: */" => "model_of_vehicle",
		"IF(    CHAR_LENGTH(`year_model1`.`year_model_specification`), CONCAT_WS('',   `year_model1`.`year_model_specification`), '') /* Year Model of Vehicle: */" => "year_model_of_vehicle",
		"IF(    CHAR_LENGTH(`body_type1`.`type_of_vehicle`), CONCAT_WS('',   `body_type1`.`type_of_vehicle`), '') /* Type of Vehicle: */" => "type_of_vehicle",
		"IF(    CHAR_LENGTH(`log_sheet1`.`closing_km`), CONCAT_WS('',   `log_sheet1`.`closing_km`, ' '), '') /* Odometer Reading (km): */" => "closing_km",
		"IF(    CHAR_LENGTH(`application_status1`.`application_status`), CONCAT_WS('',   `application_status1`.`application_status`), '') /* Application Status: */" => "application_status",
		"IF(    CHAR_LENGTH(`work_allocation1`.`work_allocation_reference_number`), CONCAT_WS('',   `work_allocation1`.`work_allocation_reference_number`), '') /* Work Allocation Reference Number: */" => "work_allocation_reference_number",
		"IF(    CHAR_LENGTH(`gmt_fleet_register1`.`barcode_number`), CONCAT_WS('',   `gmt_fleet_register1`.`barcode_number`), '') /* Barcode Number: */" => "barcode_number",
		"IF(    CHAR_LENGTH(`departments1`.`department_name`), CONCAT_WS('',   `departments1`.`department_name`), '') /* Department: */" => "department",
		"`service`.`service_item`" => "service_item",
		"IF(    CHAR_LENGTH(if(`schedule1`.`date`,date_format(`schedule1`.`date`,'%d/%m/%Y'),'')), CONCAT_WS('',   if(`schedule1`.`date`,date_format(`schedule1`.`date`,'%d/%m/%Y'),'')), '') /* Date of Service: */" => "date_of_service",
		"IF(    CHAR_LENGTH(`schedule1`.`time`), CONCAT_WS('',   `schedule1`.`time`), '') /* Time: */" => "time",
		"`service`.`upload_quotation`" => "upload_quotation",
		"DATE_FORMAT(`service`.`date_of_next_service`, '%D %b %Y %l:%i%p')" => "date_of_next_service",
		"`service`.`repeat_service_schedule_every_km`" => "repeat_service_schedule_every_km",
		"`service`.`comments`" => "comments",
		"`service`.`upload_invoice`" => "upload_invoice",
		"IF(    CHAR_LENGTH(`reception1`.`reception_name_and_surname`) || CHAR_LENGTH(`reception1`.`reception_persal_number`), CONCAT_WS('',   `reception1`.`reception_name_and_surname`, '     |    and     |     ', `reception1`.`reception_persal_number`), '') /* Information Capture By Receptionist (Name & Surname): */" => "receptionist",
		"IF(    CHAR_LENGTH(`reception1`.`reception_email_address`) || CHAR_LENGTH(`reception1`.`reception_contact_details`), CONCAT_WS('',   `reception1`.`reception_email_address`, '     |     and      |    ', `reception1`.`reception_contact_details`), '') /* Receptionist Contact e-Mail: */" => "receptionist_contact_email",
		"IF(    CHAR_LENGTH(`districts1`.`district`), CONCAT_WS('',   `districts1`.`district`), '') /* Workshop Name: */" => "workshop_name",
		"`service`.`workshop_address`" => "workshop_address",
		"`service`.`technician`" => "technician",
		"`service`.`work_order_status`" => "work_order_status",
		"IF(    CHAR_LENGTH(`reception1`.`job_card_number`) || CHAR_LENGTH(`gmt_fleet_register10`.`vehicle_registration_number`), CONCAT_WS('',   `reception1`.`job_card_number`, `gmt_fleet_register10`.`vehicle_registration_number`), '') /* Job Card Number: */" => "job_card_number",
		"if(`service`.`completion_date`,date_format(`service`.`completion_date`,'%d/%m/%Y'),'')" => "completion_date",
		"if(`service`.`due_date`,date_format(`service`.`due_date`,'%d/%m/%Y'),'')" => "due_date",
		"DATE_FORMAT(`service`.`filed`, '%c/%e/%Y %l:%i%p')" => "filed",
		"DATE_FORMAT(`service`.`last_modified`, '%c/%e/%Y %l:%i%p')" => "last_modified",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`service`.`service_id`',
		2 => 2,
		3 => 3,
		4 => '`service_item_type1`.`service_item_type`',
		5 => '`service_categories1`.`service_category`',
		6 => 6,
		7 => '`gmt_fleet_register1`.`vehicle_registration_number`',
		8 => '`gmt_fleet_register1`.`engine_number`',
		9 => 9,
		10 => '`dealer1`.`dealer_name`',
		11 => 11,
		12 => '`gmt_fleet_register1`.`model_of_vehicle`',
		13 => 13,
		14 => 14,
		15 => 15,
		16 => 16,
		17 => '`work_allocation1`.`work_allocation_reference_number`',
		18 => '`gmt_fleet_register1`.`barcode_number`',
		19 => 19,
		20 => 20,
		21 => 'date_format(`schedule1`.`date`,\'%d/%m/%Y\')',
		22 => '`schedule1`.`time`',
		23 => 23,
		24 => '`service`.`date_of_next_service`',
		25 => 25,
		26 => 26,
		27 => 27,
		28 => 28,
		29 => 29,
		30 => 30,
		31 => 31,
		32 => 32,
		33 => 33,
		34 => 34,
		35 => '`service`.`completion_date`',
		36 => '`service`.`due_date`',
		37 => '`service`.`filed`',
		38 => '`service`.`last_modified`',
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`service`.`service_id`" => "service_id",
		"`service`.`breakdown_of_vehicle`" => "breakdown_of_vehicle",
		"`service`.`service_title`" => "service_title",
		"IF(    CHAR_LENGTH(`service_item_type1`.`service_item_type`), CONCAT_WS('',   `service_item_type1`.`service_item_type`), '') /* Service Item Type: */" => "service_item_type",
		"IF(    CHAR_LENGTH(`service_categories1`.`service_category`), CONCAT_WS('',   `service_categories1`.`service_category`), '') /* Service Category: */" => "service_category",
		"IF(    CHAR_LENGTH(`merchant1`.`merchant_name`) || CHAR_LENGTH(`merchant_type1`.`merchant_type`), CONCAT_WS('',   `merchant1`.`merchant_name`, '    |   and   |    ', `merchant_type1`.`merchant_type`), '') /* Merchant Name: */" => "merchant_name",
		"IF(    CHAR_LENGTH(`gmt_fleet_register1`.`vehicle_registration_number`), CONCAT_WS('',   `gmt_fleet_register1`.`vehicle_registration_number`), '') /* Registration Number: */" => "vehicle_registration_number",
		"IF(    CHAR_LENGTH(`gmt_fleet_register1`.`engine_number`), CONCAT_WS('',   `gmt_fleet_register1`.`engine_number`), '') /* Engine Number: */" => "engine_number",
		"IF(    CHAR_LENGTH(`gmt_fleet_register1`.`chassis_number`) || CHAR_LENGTH(`gmt_fleet_register1`.`vehicle_registration_number`), CONCAT_WS('',   `gmt_fleet_register1`.`chassis_number`, ' |  and  |     ', `gmt_fleet_register1`.`vehicle_registration_number`), '') /* Chassis Number: */" => "chassis_number",
		"IF(    CHAR_LENGTH(`dealer1`.`dealer_name`), CONCAT_WS('',   `dealer1`.`dealer_name`), '') /* Make of Vehicle/Dealer Name: */" => "dealer_name",
		"IF(    CHAR_LENGTH(`dealer1`.`make_of_vehicle`), CONCAT_WS('',   `dealer1`.`make_of_vehicle`, '   '), '') /* Make of Vehicle: */" => "make_of_vehicle",
		"IF(    CHAR_LENGTH(`gmt_fleet_register1`.`model_of_vehicle`), CONCAT_WS('',   `gmt_fleet_register1`.`model_of_vehicle`), '') /* Model of Vehicle: */" => "model_of_vehicle",
		"IF(    CHAR_LENGTH(`year_model1`.`year_model_specification`), CONCAT_WS('',   `year_model1`.`year_model_specification`), '') /* Year Model of Vehicle: */" => "year_model_of_vehicle",
		"IF(    CHAR_LENGTH(`body_type1`.`type_of_vehicle`), CONCAT_WS('',   `body_type1`.`type_of_vehicle`), '') /* Type of Vehicle: */" => "type_of_vehicle",
		"IF(    CHAR_LENGTH(`log_sheet1`.`closing_km`), CONCAT_WS('',   `log_sheet1`.`closing_km`, ' '), '') /* Odometer Reading (km): */" => "closing_km",
		"IF(    CHAR_LENGTH(`application_status1`.`application_status`), CONCAT_WS('',   `application_status1`.`application_status`), '') /* Application Status: */" => "application_status",
		"IF(    CHAR_LENGTH(`work_allocation1`.`work_allocation_reference_number`), CONCAT_WS('',   `work_allocation1`.`work_allocation_reference_number`), '') /* Work Allocation Reference Number: */" => "work_allocation_reference_number",
		"IF(    CHAR_LENGTH(`gmt_fleet_register1`.`barcode_number`), CONCAT_WS('',   `gmt_fleet_register1`.`barcode_number`), '') /* Barcode Number: */" => "barcode_number",
		"IF(    CHAR_LENGTH(`departments1`.`department_name`), CONCAT_WS('',   `departments1`.`department_name`), '') /* Department: */" => "department",
		"`service`.`service_item`" => "service_item",
		"IF(    CHAR_LENGTH(if(`schedule1`.`date`,date_format(`schedule1`.`date`,'%d/%m/%Y'),'')), CONCAT_WS('',   if(`schedule1`.`date`,date_format(`schedule1`.`date`,'%d/%m/%Y'),'')), '') /* Date of Service: */" => "date_of_service",
		"IF(    CHAR_LENGTH(`schedule1`.`time`), CONCAT_WS('',   `schedule1`.`time`), '') /* Time: */" => "time",
		"`service`.`upload_quotation`" => "upload_quotation",
		"DATE_FORMAT(`service`.`date_of_next_service`, '%D %b %Y %l:%i%p')" => "date_of_next_service",
		"`service`.`repeat_service_schedule_every_km`" => "repeat_service_schedule_every_km",
		"`service`.`comments`" => "comments",
		"`service`.`upload_invoice`" => "upload_invoice",
		"IF(    CHAR_LENGTH(`reception1`.`reception_name_and_surname`) || CHAR_LENGTH(`reception1`.`reception_persal_number`), CONCAT_WS('',   `reception1`.`reception_name_and_surname`, '     |    and     |     ', `reception1`.`reception_persal_number`), '') /* Information Capture By Receptionist (Name & Surname): */" => "receptionist",
		"IF(    CHAR_LENGTH(`reception1`.`reception_email_address`) || CHAR_LENGTH(`reception1`.`reception_contact_details`), CONCAT_WS('',   `reception1`.`reception_email_address`, '     |     and      |    ', `reception1`.`reception_contact_details`), '') /* Receptionist Contact e-Mail: */" => "receptionist_contact_email",
		"IF(    CHAR_LENGTH(`districts1`.`district`), CONCAT_WS('',   `districts1`.`district`), '') /* Workshop Name: */" => "workshop_name",
		"`service`.`workshop_address`" => "workshop_address",
		"`service`.`technician`" => "technician",
		"`service`.`work_order_status`" => "work_order_status",
		"IF(    CHAR_LENGTH(`reception1`.`job_card_number`) || CHAR_LENGTH(`gmt_fleet_register10`.`vehicle_registration_number`), CONCAT_WS('',   `reception1`.`job_card_number`, `gmt_fleet_register10`.`vehicle_registration_number`), '') /* Job Card Number: */" => "job_card_number",
		"if(`service`.`completion_date`,date_format(`service`.`completion_date`,'%d/%m/%Y'),'')" => "completion_date",
		"if(`service`.`due_date`,date_format(`service`.`due_date`,'%d/%m/%Y'),'')" => "due_date",
		"DATE_FORMAT(`service`.`filed`, '%c/%e/%Y %l:%i%p')" => "filed",
		"DATE_FORMAT(`service`.`last_modified`, '%c/%e/%Y %l:%i%p')" => "last_modified",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`service`.`service_id`" => "Service ID:",
		"`service`.`breakdown_of_vehicle`" => "Breakdown of Vehicle?:",
		"`service`.`service_title`" => "Service Title:",
		"IF(    CHAR_LENGTH(`service_item_type1`.`service_item_type`), CONCAT_WS('',   `service_item_type1`.`service_item_type`), '') /* Service Item Type: */" => "Service Item Type:",
		"IF(    CHAR_LENGTH(`service_categories1`.`service_category`), CONCAT_WS('',   `service_categories1`.`service_category`), '') /* Service Category: */" => "Service Category:",
		"IF(    CHAR_LENGTH(`merchant1`.`merchant_name`) || CHAR_LENGTH(`merchant_type1`.`merchant_type`), CONCAT_WS('',   `merchant1`.`merchant_name`, '    |   and   |    ', `merchant_type1`.`merchant_type`), '') /* Merchant Name: */" => "Merchant Name:",
		"IF(    CHAR_LENGTH(`gmt_fleet_register1`.`vehicle_registration_number`), CONCAT_WS('',   `gmt_fleet_register1`.`vehicle_registration_number`), '') /* Registration Number: */" => "Registration Number:",
		"IF(    CHAR_LENGTH(`gmt_fleet_register1`.`engine_number`), CONCAT_WS('',   `gmt_fleet_register1`.`engine_number`), '') /* Engine Number: */" => "Engine Number:",
		"IF(    CHAR_LENGTH(`gmt_fleet_register1`.`chassis_number`) || CHAR_LENGTH(`gmt_fleet_register1`.`vehicle_registration_number`), CONCAT_WS('',   `gmt_fleet_register1`.`chassis_number`, ' |  and  |     ', `gmt_fleet_register1`.`vehicle_registration_number`), '') /* Chassis Number: */" => "Chassis Number:",
		"IF(    CHAR_LENGTH(`dealer1`.`dealer_name`), CONCAT_WS('',   `dealer1`.`dealer_name`), '') /* Make of Vehicle/Dealer Name: */" => "Make of Vehicle/Dealer Name:",
		"IF(    CHAR_LENGTH(`dealer1`.`make_of_vehicle`), CONCAT_WS('',   `dealer1`.`make_of_vehicle`, '   '), '') /* Make of Vehicle: */" => "Make of Vehicle:",
		"IF(    CHAR_LENGTH(`gmt_fleet_register1`.`model_of_vehicle`), CONCAT_WS('',   `gmt_fleet_register1`.`model_of_vehicle`), '') /* Model of Vehicle: */" => "Model of Vehicle:",
		"IF(    CHAR_LENGTH(`year_model1`.`year_model_specification`), CONCAT_WS('',   `year_model1`.`year_model_specification`), '') /* Year Model of Vehicle: */" => "Year Model of Vehicle:",
		"IF(    CHAR_LENGTH(`body_type1`.`type_of_vehicle`), CONCAT_WS('',   `body_type1`.`type_of_vehicle`), '') /* Type of Vehicle: */" => "Type of Vehicle:",
		"IF(    CHAR_LENGTH(`log_sheet1`.`closing_km`), CONCAT_WS('',   `log_sheet1`.`closing_km`, ' '), '') /* Odometer Reading (km): */" => "Odometer Reading (km):",
		"IF(    CHAR_LENGTH(`application_status1`.`application_status`), CONCAT_WS('',   `application_status1`.`application_status`), '') /* Application Status: */" => "Application Status:",
		"IF(    CHAR_LENGTH(`work_allocation1`.`work_allocation_reference_number`), CONCAT_WS('',   `work_allocation1`.`work_allocation_reference_number`), '') /* Work Allocation Reference Number: */" => "Work Allocation Reference Number:",
		"IF(    CHAR_LENGTH(`gmt_fleet_register1`.`barcode_number`), CONCAT_WS('',   `gmt_fleet_register1`.`barcode_number`), '') /* Barcode Number: */" => "Barcode Number:",
		"IF(    CHAR_LENGTH(`departments1`.`department_name`), CONCAT_WS('',   `departments1`.`department_name`), '') /* Department: */" => "Department:",
		"`service`.`service_item`" => "Service Item:",
		"IF(    CHAR_LENGTH(if(`schedule1`.`date`,date_format(`schedule1`.`date`,'%d/%m/%Y'),'')), CONCAT_WS('',   if(`schedule1`.`date`,date_format(`schedule1`.`date`,'%d/%m/%Y'),'')), '') /* Date of Service: */" => "Date of Service:",
		"IF(    CHAR_LENGTH(`schedule1`.`time`), CONCAT_WS('',   `schedule1`.`time`), '') /* Time: */" => "Time:",
		"`service`.`upload_quotation`" => "Documents (Upload Quotation):",
		"`service`.`date_of_next_service`" => "Date of Next Service:",
		"`service`.`repeat_service_schedule_every_km`" => "Repeat Service Schedule Every (km):",
		"`service`.`comments`" => "Comments:",
		"`service`.`upload_invoice`" => "Documents (Upload Invoice):",
		"IF(    CHAR_LENGTH(`reception1`.`reception_name_and_surname`) || CHAR_LENGTH(`reception1`.`reception_persal_number`), CONCAT_WS('',   `reception1`.`reception_name_and_surname`, '     |    and     |     ', `reception1`.`reception_persal_number`), '') /* Information Capture By Receptionist (Name & Surname): */" => "Information Capture By Receptionist (Name & Surname):",
		"IF(    CHAR_LENGTH(`reception1`.`reception_email_address`) || CHAR_LENGTH(`reception1`.`reception_contact_details`), CONCAT_WS('',   `reception1`.`reception_email_address`, '     |     and      |    ', `reception1`.`reception_contact_details`), '') /* Receptionist Contact e-Mail: */" => "Receptionist Contact e-Mail:",
		"IF(    CHAR_LENGTH(`districts1`.`district`), CONCAT_WS('',   `districts1`.`district`), '') /* Workshop Name: */" => "Workshop Name:",
		"`service`.`workshop_address`" => "Workshop Address:",
		"`service`.`technician`" => "Technician:",
		"`service`.`work_order_status`" => "Work Order Status:",
		"IF(    CHAR_LENGTH(`reception1`.`job_card_number`) || CHAR_LENGTH(`gmt_fleet_register10`.`vehicle_registration_number`), CONCAT_WS('',   `reception1`.`job_card_number`, `gmt_fleet_register10`.`vehicle_registration_number`), '') /* Job Card Number: */" => "Job Card Number:",
		"`service`.`completion_date`" => "Actual Completion Date:",
		"`service`.`due_date`" => "Due Date:",
		"`service`.`filed`" => "Filed",
		"`service`.`last_modified`" => "Last modified",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`service`.`service_id`" => "service_id",
		"`service`.`breakdown_of_vehicle`" => "breakdown_of_vehicle",
		"`service`.`service_title`" => "service_title",
		"IF(    CHAR_LENGTH(`service_item_type1`.`service_item_type`), CONCAT_WS('',   `service_item_type1`.`service_item_type`), '') /* Service Item Type: */" => "service_item_type",
		"IF(    CHAR_LENGTH(`service_categories1`.`service_category`), CONCAT_WS('',   `service_categories1`.`service_category`), '') /* Service Category: */" => "service_category",
		"IF(    CHAR_LENGTH(`merchant1`.`merchant_name`) || CHAR_LENGTH(`merchant_type1`.`merchant_type`), CONCAT_WS('',   `merchant1`.`merchant_name`, '    |   and   |    ', `merchant_type1`.`merchant_type`), '') /* Merchant Name: */" => "merchant_name",
		"IF(    CHAR_LENGTH(`gmt_fleet_register1`.`vehicle_registration_number`), CONCAT_WS('',   `gmt_fleet_register1`.`vehicle_registration_number`), '') /* Registration Number: */" => "vehicle_registration_number",
		"IF(    CHAR_LENGTH(`gmt_fleet_register1`.`engine_number`), CONCAT_WS('',   `gmt_fleet_register1`.`engine_number`), '') /* Engine Number: */" => "engine_number",
		"IF(    CHAR_LENGTH(`gmt_fleet_register1`.`chassis_number`) || CHAR_LENGTH(`gmt_fleet_register1`.`vehicle_registration_number`), CONCAT_WS('',   `gmt_fleet_register1`.`chassis_number`, ' |  and  |     ', `gmt_fleet_register1`.`vehicle_registration_number`), '') /* Chassis Number: */" => "chassis_number",
		"IF(    CHAR_LENGTH(`dealer1`.`dealer_name`), CONCAT_WS('',   `dealer1`.`dealer_name`), '') /* Make of Vehicle/Dealer Name: */" => "dealer_name",
		"IF(    CHAR_LENGTH(`dealer1`.`make_of_vehicle`), CONCAT_WS('',   `dealer1`.`make_of_vehicle`, '   '), '') /* Make of Vehicle: */" => "make_of_vehicle",
		"IF(    CHAR_LENGTH(`gmt_fleet_register1`.`model_of_vehicle`), CONCAT_WS('',   `gmt_fleet_register1`.`model_of_vehicle`), '') /* Model of Vehicle: */" => "model_of_vehicle",
		"IF(    CHAR_LENGTH(`year_model1`.`year_model_specification`), CONCAT_WS('',   `year_model1`.`year_model_specification`), '') /* Year Model of Vehicle: */" => "year_model_of_vehicle",
		"IF(    CHAR_LENGTH(`body_type1`.`type_of_vehicle`), CONCAT_WS('',   `body_type1`.`type_of_vehicle`), '') /* Type of Vehicle: */" => "type_of_vehicle",
		"IF(    CHAR_LENGTH(`log_sheet1`.`closing_km`), CONCAT_WS('',   `log_sheet1`.`closing_km`, ' '), '') /* Odometer Reading (km): */" => "closing_km",
		"IF(    CHAR_LENGTH(`application_status1`.`application_status`), CONCAT_WS('',   `application_status1`.`application_status`), '') /* Application Status: */" => "application_status",
		"IF(    CHAR_LENGTH(`work_allocation1`.`work_allocation_reference_number`), CONCAT_WS('',   `work_allocation1`.`work_allocation_reference_number`), '') /* Work Allocation Reference Number: */" => "work_allocation_reference_number",
		"IF(    CHAR_LENGTH(`gmt_fleet_register1`.`barcode_number`), CONCAT_WS('',   `gmt_fleet_register1`.`barcode_number`), '') /* Barcode Number: */" => "barcode_number",
		"IF(    CHAR_LENGTH(`departments1`.`department_name`), CONCAT_WS('',   `departments1`.`department_name`), '') /* Department: */" => "department",
		"`service`.`service_item`" => "service_item",
		"IF(    CHAR_LENGTH(if(`schedule1`.`date`,date_format(`schedule1`.`date`,'%d/%m/%Y'),'')), CONCAT_WS('',   if(`schedule1`.`date`,date_format(`schedule1`.`date`,'%d/%m/%Y'),'')), '') /* Date of Service: */" => "date_of_service",
		"IF(    CHAR_LENGTH(`schedule1`.`time`), CONCAT_WS('',   `schedule1`.`time`), '') /* Time: */" => "time",
		"`service`.`upload_quotation`" => "upload_quotation",
		"DATE_FORMAT(`service`.`date_of_next_service`, '%D %b %Y %l:%i%p')" => "date_of_next_service",
		"`service`.`repeat_service_schedule_every_km`" => "repeat_service_schedule_every_km",
		"`service`.`comments`" => "comments",
		"`service`.`upload_invoice`" => "upload_invoice",
		"IF(    CHAR_LENGTH(`reception1`.`reception_name_and_surname`) || CHAR_LENGTH(`reception1`.`reception_persal_number`), CONCAT_WS('',   `reception1`.`reception_name_and_surname`, '     |    and     |     ', `reception1`.`reception_persal_number`), '') /* Information Capture By Receptionist (Name & Surname): */" => "receptionist",
		"IF(    CHAR_LENGTH(`reception1`.`reception_email_address`) || CHAR_LENGTH(`reception1`.`reception_contact_details`), CONCAT_WS('',   `reception1`.`reception_email_address`, '     |     and      |    ', `reception1`.`reception_contact_details`), '') /* Receptionist Contact e-Mail: */" => "receptionist_contact_email",
		"IF(    CHAR_LENGTH(`districts1`.`district`), CONCAT_WS('',   `districts1`.`district`), '') /* Workshop Name: */" => "workshop_name",
		"`service`.`workshop_address`" => "workshop_address",
		"`service`.`technician`" => "technician",
		"`service`.`work_order_status`" => "work_order_status",
		"IF(    CHAR_LENGTH(`reception1`.`job_card_number`) || CHAR_LENGTH(`gmt_fleet_register10`.`vehicle_registration_number`), CONCAT_WS('',   `reception1`.`job_card_number`, `gmt_fleet_register10`.`vehicle_registration_number`), '') /* Job Card Number: */" => "job_card_number",
		"if(`service`.`completion_date`,date_format(`service`.`completion_date`,'%d/%m/%Y'),'')" => "completion_date",
		"if(`service`.`due_date`,date_format(`service`.`due_date`,'%d/%m/%Y'),'')" => "due_date",
		"DATE_FORMAT(`service`.`filed`, '%c/%e/%Y %l:%i%p')" => "filed",
		"DATE_FORMAT(`service`.`last_modified`, '%c/%e/%Y %l:%i%p')" => "last_modified",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = ['service_item_type' => 'Service Item Type:', 'service_category' => 'Service Category:', 'merchant_name' => 'Merchant Name:', 'vehicle_registration_number' => 'Registration Number:', 'dealer_name' => 'Make of Vehicle/Dealer Name:', 'closing_km' => 'Odometer Reading (km):', 'work_allocation_reference_number' => 'Work Allocation Reference Number:', 'date_of_service' => 'Date of Service:', 'receptionist' => 'Information Capture By Receptionist (Name & Surname):', ];

	$x->QueryFrom = "`service` LEFT JOIN `service_item_type` as service_item_type1 ON `service_item_type1`.`service_item_type_id`=`service`.`service_item_type` LEFT JOIN `service_categories` as service_categories1 ON `service_categories1`.`service_categories_id`=`service`.`service_category` LEFT JOIN `merchant` as merchant1 ON `merchant1`.`merchant_id`=`service`.`merchant_name` LEFT JOIN `merchant_type` as merchant_type1 ON `merchant_type1`.`merchant_type_id`=`merchant1`.`merchant_type` LEFT JOIN `gmt_fleet_register` as gmt_fleet_register1 ON `gmt_fleet_register1`.`fleet_asset_id`=`service`.`vehicle_registration_number` LEFT JOIN `dealer` as dealer1 ON `dealer1`.`dealer_id`=`service`.`dealer_name` LEFT JOIN `log_sheet` as log_sheet1 ON `log_sheet1`.`fuel_log_sheet_id`=`service`.`closing_km` LEFT JOIN `work_allocation` as work_allocation1 ON `work_allocation1`.`work_allocation_id`=`service`.`work_allocation_reference_number` LEFT JOIN `schedule` as schedule1 ON `schedule1`.`schedule_id`=`service`.`date_of_service` LEFT JOIN `reception` as reception1 ON `reception1`.`reception_user_id`=`service`.`receptionist` LEFT JOIN `year_model` as year_model1 ON `year_model1`.`year_model_id`=`gmt_fleet_register1`.`year_model_specification` LEFT JOIN `body_type` as body_type1 ON `body_type1`.`body_type_id`=`gmt_fleet_register1`.`type_of_vehicle` LEFT JOIN `application_status` as application_status1 ON `application_status1`.`application_id`=`gmt_fleet_register1`.`application_status` LEFT JOIN `departments` as departments1 ON `departments1`.`department_id`=`gmt_fleet_register1`.`department_name` LEFT JOIN `districts` as districts1 ON `districts1`.`district_id`=`reception1`.`district` LEFT JOIN `gmt_fleet_register` as gmt_fleet_register10 ON `gmt_fleet_register10`.`fleet_asset_id`=`reception1`.`vehicle_registration_number` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 25;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'service_view.php';
	$x->RedirectAfterInsert = 'service_view.php?SelectedID=#ID#';
	$x->TableTitle = 'Service:';
	$x->TableIcon = 'resources/table_icons/autorepair2.png';
	$x->PrimaryKey = '`service`.`service_id`';

	$x->ColWidth = [150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, ];
	$x->ColCaption = ['Service ID:', 'Breakdown of Vehicle?:', 'Service Title:', 'Service Item Type:', 'Service Category:', 'Merchant Name:', 'Registration Number:', 'Engine Number:', 'Chassis Number:', 'Make of Vehicle/Dealer Name:', 'Make of Vehicle:', 'Model of Vehicle:', 'Year Model of Vehicle:', 'Type of Vehicle:', 'Odometer Reading (km):', 'Application Status:', 'Work Allocation Reference Number:', 'Barcode Number:', 'Department:', 'Service Item:', 'Date of Service:', 'Time:', 'Documents (Upload Quotation):', 'Date of Next Service:', 'Repeat Service Schedule Every (km):', 'Comments:', 'Documents (Upload Invoice):', 'Information Capture By Receptionist (Name & Surname):', 'Receptionist Contact e-Mail:', 'Workshop Name:', 'Workshop Address:', 'Technician:', 'Work Order Status:', 'Job Card Number:', 'Actual Completion Date:', 'Due Date:', ];
	$x->ColFieldName = ['service_id', 'breakdown_of_vehicle', 'service_title', 'service_item_type', 'service_category', 'merchant_name', 'vehicle_registration_number', 'engine_number', 'chassis_number', 'dealer_name', 'make_of_vehicle', 'model_of_vehicle', 'year_model_of_vehicle', 'type_of_vehicle', 'closing_km', 'application_status', 'work_allocation_reference_number', 'barcode_number', 'department', 'service_item', 'date_of_service', 'time', 'upload_quotation', 'date_of_next_service', 'repeat_service_schedule_every_km', 'comments', 'upload_invoice', 'receptionist', 'receptionist_contact_email', 'workshop_name', 'workshop_address', 'technician', 'work_order_status', 'job_card_number', 'completion_date', 'due_date', ];
	$x->ColNumber  = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/service_templateTV.html';
	$x->SelectedTemplate = 'templates/service_templateTVS.html';
	$x->TemplateDV = 'templates/service_templateDV.html';
	$x->TemplateDVP = 'templates/service_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: service_init
	$render = true;
	if(function_exists('service_init')) {
		$args = [];
		$render = service_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: service_header
	$headerCode = '';
	if(function_exists('service_header')) {
		$args = [];
		$headerCode = service_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: service_footer
	$footerCode = '';
	if(function_exists('service_footer')) {
		$args = [];
		$footerCode = service_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
