<?php
// This script and data application were generated by AppGini 22.13
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/transmission.php');
	include_once(__DIR__ . '/transmission_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('transmission');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'transmission';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`transmission`.`transmission_id`" => "transmission_id",
		"`transmission`.`transmission`" => "transmission",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`transmission`.`transmission_id`',
		2 => 2,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`transmission`.`transmission_id`" => "transmission_id",
		"`transmission`.`transmission`" => "transmission",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`transmission`.`transmission_id`" => "Transmission ID:",
		"`transmission`.`transmission`" => "Transmission:",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`transmission`.`transmission_id`" => "transmission_id",
		"`transmission`.`transmission`" => "transmission",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`transmission` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'transmission_view.php';
	$x->RedirectAfterInsert = 'transmission_view.php?SelectedID=#ID#';
	$x->TableTitle = 'Transmission:';
	$x->TableIcon = 'resources/table_icons/cargear.png';
	$x->PrimaryKey = '`transmission`.`transmission_id`';

	$x->ColWidth = [150, 150, ];
	$x->ColCaption = ['Transmission ID:', 'Transmission:', ];
	$x->ColFieldName = ['transmission_id', 'transmission', ];
	$x->ColNumber  = [1, 2, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/transmission_templateTV.html';
	$x->SelectedTemplate = 'templates/transmission_templateTVS.html';
	$x->TemplateDV = 'templates/transmission_templateDV.html';
	$x->TemplateDVP = 'templates/transmission_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: transmission_init
	$render = true;
	if(function_exists('transmission_init')) {
		$args = [];
		$render = transmission_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: transmission_header
	$headerCode = '';
	if(function_exists('transmission_header')) {
		$args = [];
		$headerCode = transmission_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: transmission_footer
	$footerCode = '';
	if(function_exists('transmission_footer')) {
		$args = [];
		$footerCode = transmission_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
