<?php
// This script and data application were generated by AppGini 22.13
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/tyre_log_sheet.php');
	include_once(__DIR__ . '/tyre_log_sheet_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('tyre_log_sheet');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'tyre_log_sheet';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`tyre_log_sheet`.`tyre_log_id`" => "tyre_log_id",
		"IF(    CHAR_LENGTH(`gmt_fleet_register1`.`vehicle_registration_number`) || CHAR_LENGTH(`gmt_fleet_register1`.`engine_number`), CONCAT_WS('',   `gmt_fleet_register1`.`vehicle_registration_number`, '    |    and    |      ', `gmt_fleet_register1`.`engine_number`), '') /* Registration Number: */" => "vehicle_registration_number",
		"`tyre_log_sheet`.`tyre_position`" => "tyre_position",
		"`tyre_log_sheet`.`tyre_tread_condition`" => "tyre_tread_condition",
		"`tyre_log_sheet`.`tyre_brand`" => "tyre_brand",
		"`tyre_log_sheet`.`tyre_model`" => "tyre_model",
		"`tyre_log_sheet`.`tyre_size`" => "tyre_size",
		"`tyre_log_sheet`.`tyre_pressure`" => "tyre_pressure",
		"`tyre_log_sheet`.`action`" => "action",
		"`tyre_log_sheet`.`warranty`" => "warranty",
		"`tyre_log_sheet`.`documents`" => "documents",
		"`tyre_log_sheet`.`tyre_tread`" => "tyre_tread",
		"`tyre_log_sheet`.`tyre_maximum_wear`" => "tyre_maximum_wear",
		"DATE_FORMAT(`tyre_log_sheet`.`inspection_date`, '%D %b %Y %l:%i%p')" => "inspection_date",
		"`tyre_log_sheet`.`tyre_inspection_done_by`" => "tyre_inspection_done_by",
		"`tyre_log_sheet`.`tyre_inspection_report`" => "tyre_inspection_report",
		"`tyre_log_sheet`.`status`" => "status",
		"`tyre_log_sheet`.`opening_km`" => "opening_km",
		"`tyre_log_sheet`.`closing_km`" => "closing_km",
		"`tyre_log_sheet`.`total_km`" => "total_km",
		"`tyre_log_sheet`.`comments`" => "comments",
		"`tyre_log_sheet`.`tyres_cause_of_accident`" => "tyres_cause_of_accident",
		"`tyre_log_sheet`.`accident_report`" => "accident_report",
		"`tyre_log_sheet`.`claims_report`" => "claims_report",
		"`tyre_log_sheet`.`insurance_claims_report`" => "insurance_claims_report",
		"`tyre_log_sheet`.`reminder_maximum_wear`" => "reminder_maximum_wear",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`tyre_log_sheet`.`tyre_log_id`',
		2 => 2,
		3 => 3,
		4 => 4,
		5 => 5,
		6 => 6,
		7 => 7,
		8 => 8,
		9 => 9,
		10 => 10,
		11 => 11,
		12 => 12,
		13 => 13,
		14 => '`tyre_log_sheet`.`inspection_date`',
		15 => 15,
		16 => 16,
		17 => 17,
		18 => 18,
		19 => 19,
		20 => 20,
		21 => 21,
		22 => 22,
		23 => 23,
		24 => 24,
		25 => 25,
		26 => 26,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`tyre_log_sheet`.`tyre_log_id`" => "tyre_log_id",
		"IF(    CHAR_LENGTH(`gmt_fleet_register1`.`vehicle_registration_number`) || CHAR_LENGTH(`gmt_fleet_register1`.`engine_number`), CONCAT_WS('',   `gmt_fleet_register1`.`vehicle_registration_number`, '    |    and    |      ', `gmt_fleet_register1`.`engine_number`), '') /* Registration Number: */" => "vehicle_registration_number",
		"`tyre_log_sheet`.`tyre_position`" => "tyre_position",
		"`tyre_log_sheet`.`tyre_tread_condition`" => "tyre_tread_condition",
		"`tyre_log_sheet`.`tyre_brand`" => "tyre_brand",
		"`tyre_log_sheet`.`tyre_model`" => "tyre_model",
		"`tyre_log_sheet`.`tyre_size`" => "tyre_size",
		"`tyre_log_sheet`.`tyre_pressure`" => "tyre_pressure",
		"`tyre_log_sheet`.`action`" => "action",
		"`tyre_log_sheet`.`warranty`" => "warranty",
		"`tyre_log_sheet`.`documents`" => "documents",
		"`tyre_log_sheet`.`tyre_tread`" => "tyre_tread",
		"`tyre_log_sheet`.`tyre_maximum_wear`" => "tyre_maximum_wear",
		"DATE_FORMAT(`tyre_log_sheet`.`inspection_date`, '%D %b %Y %l:%i%p')" => "inspection_date",
		"`tyre_log_sheet`.`tyre_inspection_done_by`" => "tyre_inspection_done_by",
		"`tyre_log_sheet`.`tyre_inspection_report`" => "tyre_inspection_report",
		"`tyre_log_sheet`.`status`" => "status",
		"`tyre_log_sheet`.`opening_km`" => "opening_km",
		"`tyre_log_sheet`.`closing_km`" => "closing_km",
		"`tyre_log_sheet`.`total_km`" => "total_km",
		"`tyre_log_sheet`.`comments`" => "comments",
		"`tyre_log_sheet`.`tyres_cause_of_accident`" => "tyres_cause_of_accident",
		"`tyre_log_sheet`.`accident_report`" => "accident_report",
		"`tyre_log_sheet`.`claims_report`" => "claims_report",
		"`tyre_log_sheet`.`insurance_claims_report`" => "insurance_claims_report",
		"`tyre_log_sheet`.`reminder_maximum_wear`" => "reminder_maximum_wear",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`tyre_log_sheet`.`tyre_log_id`" => "Tyre Log ID:",
		"IF(    CHAR_LENGTH(`gmt_fleet_register1`.`vehicle_registration_number`) || CHAR_LENGTH(`gmt_fleet_register1`.`engine_number`), CONCAT_WS('',   `gmt_fleet_register1`.`vehicle_registration_number`, '    |    and    |      ', `gmt_fleet_register1`.`engine_number`), '') /* Registration Number: */" => "Registration Number:",
		"`tyre_log_sheet`.`tyre_position`" => "Tyre Position:",
		"`tyre_log_sheet`.`tyre_tread_condition`" => "Tyre Tread Condition:",
		"`tyre_log_sheet`.`tyre_brand`" => "Tyre Brand:",
		"`tyre_log_sheet`.`tyre_model`" => "Tyre Model:",
		"`tyre_log_sheet`.`tyre_size`" => "Tyre Size (Radial):",
		"`tyre_log_sheet`.`tyre_pressure`" => "Tyre Pressure (Kpa):",
		"`tyre_log_sheet`.`action`" => "Action:",
		"`tyre_log_sheet`.`warranty`" => "Warranty:",
		"`tyre_log_sheet`.`documents`" => "Document:",
		"`tyre_log_sheet`.`tyre_tread`" => "Tyre Tread (mm):",
		"`tyre_log_sheet`.`tyre_maximum_wear`" => "Tyre Maximum Wear:",
		"`tyre_log_sheet`.`inspection_date`" => "Inspection Date:",
		"`tyre_log_sheet`.`tyre_inspection_done_by`" => "Tyre Inspection Done By:",
		"`tyre_log_sheet`.`tyre_inspection_report`" => "Tyre Inspection Report:",
		"`tyre_log_sheet`.`status`" => "Status",
		"`tyre_log_sheet`.`opening_km`" => "Opening KM:",
		"`tyre_log_sheet`.`closing_km`" => "Closing KM:",
		"`tyre_log_sheet`.`total_km`" => "Trip Distance (Total KM Covered with Tyre):",
		"`tyre_log_sheet`.`comments`" => "Comments:",
		"`tyre_log_sheet`.`tyres_cause_of_accident`" => "Tyres Cause Of Accident:",
		"`tyre_log_sheet`.`accident_report`" => "Accident Report:",
		"`tyre_log_sheet`.`claims_report`" => "Claims Report:",
		"`tyre_log_sheet`.`insurance_claims_report`" => "Insurance Claims Report:",
		"`tyre_log_sheet`.`reminder_maximum_wear`" => "Reminder if Maximum Wear is reached?:",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`tyre_log_sheet`.`tyre_log_id`" => "tyre_log_id",
		"IF(    CHAR_LENGTH(`gmt_fleet_register1`.`vehicle_registration_number`) || CHAR_LENGTH(`gmt_fleet_register1`.`engine_number`), CONCAT_WS('',   `gmt_fleet_register1`.`vehicle_registration_number`, '    |    and    |      ', `gmt_fleet_register1`.`engine_number`), '') /* Registration Number: */" => "vehicle_registration_number",
		"`tyre_log_sheet`.`tyre_position`" => "tyre_position",
		"`tyre_log_sheet`.`tyre_tread_condition`" => "tyre_tread_condition",
		"`tyre_log_sheet`.`tyre_brand`" => "tyre_brand",
		"`tyre_log_sheet`.`tyre_model`" => "tyre_model",
		"`tyre_log_sheet`.`tyre_size`" => "tyre_size",
		"`tyre_log_sheet`.`tyre_pressure`" => "tyre_pressure",
		"`tyre_log_sheet`.`action`" => "action",
		"`tyre_log_sheet`.`warranty`" => "warranty",
		"`tyre_log_sheet`.`documents`" => "documents",
		"`tyre_log_sheet`.`tyre_tread`" => "tyre_tread",
		"`tyre_log_sheet`.`tyre_maximum_wear`" => "tyre_maximum_wear",
		"DATE_FORMAT(`tyre_log_sheet`.`inspection_date`, '%D %b %Y %l:%i%p')" => "inspection_date",
		"`tyre_log_sheet`.`tyre_inspection_done_by`" => "tyre_inspection_done_by",
		"`tyre_log_sheet`.`tyre_inspection_report`" => "tyre_inspection_report",
		"`tyre_log_sheet`.`status`" => "status",
		"`tyre_log_sheet`.`opening_km`" => "opening_km",
		"`tyre_log_sheet`.`closing_km`" => "closing_km",
		"`tyre_log_sheet`.`total_km`" => "total_km",
		"`tyre_log_sheet`.`comments`" => "comments",
		"`tyre_log_sheet`.`tyres_cause_of_accident`" => "tyres_cause_of_accident",
		"`tyre_log_sheet`.`accident_report`" => "accident_report",
		"`tyre_log_sheet`.`claims_report`" => "claims_report",
		"`tyre_log_sheet`.`insurance_claims_report`" => "insurance_claims_report",
		"`tyre_log_sheet`.`reminder_maximum_wear`" => "reminder_maximum_wear",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = ['vehicle_registration_number' => 'Registration Number:', ];

	$x->QueryFrom = "`tyre_log_sheet` LEFT JOIN `gmt_fleet_register` as gmt_fleet_register1 ON `gmt_fleet_register1`.`fleet_asset_id`=`tyre_log_sheet`.`vehicle_registration_number` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 25;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'tyre_log_sheet_view.php';
	$x->RedirectAfterInsert = 'tyre_log_sheet_view.php?SelectedID=#ID#';
	$x->TableTitle = 'Tyre Data:';
	$x->TableIcon = 'resources/table_icons/1350385545_wheel.png';
	$x->PrimaryKey = '`tyre_log_sheet`.`tyre_log_id`';

	$x->ColWidth = [150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, ];
	$x->ColCaption = ['Tyre Log ID:', 'Registration Number:', 'Tyre Position:', 'Tyre Tread Condition:', 'Tyre Brand:', 'Tyre Model:', 'Tyre Size (Radial):', 'Tyre Pressure (Kpa):', 'Action:', 'Warranty:', 'Document:', 'Tyre Tread (mm):', 'Tyre Maximum Wear:', 'Inspection Date:', 'Tyre Inspection Done By:', 'Tyre Inspection Report:', 'Status', 'Opening KM:', 'Closing KM:', 'Trip Distance (Total KM Covered with Tyre):', 'Comments:', 'Tyres Cause Of Accident:', 'Accident Report:', 'Claims Report:', 'Insurance Claims Report:', 'Reminder if Maximum Wear is reached?:', ];
	$x->ColFieldName = ['tyre_log_id', 'vehicle_registration_number', 'tyre_position', 'tyre_tread_condition', 'tyre_brand', 'tyre_model', 'tyre_size', 'tyre_pressure', 'action', 'warranty', 'documents', 'tyre_tread', 'tyre_maximum_wear', 'inspection_date', 'tyre_inspection_done_by', 'tyre_inspection_report', 'status', 'opening_km', 'closing_km', 'total_km', 'comments', 'tyres_cause_of_accident', 'accident_report', 'claims_report', 'insurance_claims_report', 'reminder_maximum_wear', ];
	$x->ColNumber  = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/tyre_log_sheet_templateTV.html';
	$x->SelectedTemplate = 'templates/tyre_log_sheet_templateTVS.html';
	$x->TemplateDV = 'templates/tyre_log_sheet_templateDV.html';
	$x->TemplateDVP = 'templates/tyre_log_sheet_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: tyre_log_sheet_init
	$render = true;
	if(function_exists('tyre_log_sheet_init')) {
		$args = [];
		$render = tyre_log_sheet_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: tyre_log_sheet_header
	$headerCode = '';
	if(function_exists('tyre_log_sheet_header')) {
		$args = [];
		$headerCode = tyre_log_sheet_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: tyre_log_sheet_footer
	$footerCode = '';
	if(function_exists('tyre_log_sheet_footer')) {
		$args = [];
		$footerCode = tyre_log_sheet_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
