<?php
// This script and data application were generated by AppGini 22.13
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/vehicle_colour.php');
	include_once(__DIR__ . '/vehicle_colour_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('vehicle_colour');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'vehicle_colour';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`vehicle_colour`.`vehicle_colour_id`" => "vehicle_colour_id",
		"`vehicle_colour`.`colour_of_vehicle`" => "colour_of_vehicle",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`vehicle_colour`.`vehicle_colour_id`',
		2 => 2,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`vehicle_colour`.`vehicle_colour_id`" => "vehicle_colour_id",
		"`vehicle_colour`.`colour_of_vehicle`" => "colour_of_vehicle",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`vehicle_colour`.`vehicle_colour_id`" => "Vehicle Colour ID:",
		"`vehicle_colour`.`colour_of_vehicle`" => "Colour of Vehicle:",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`vehicle_colour`.`vehicle_colour_id`" => "vehicle_colour_id",
		"`vehicle_colour`.`colour_of_vehicle`" => "colour_of_vehicle",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`vehicle_colour` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = true;
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 25;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'vehicle_colour_view.php';
	$x->RedirectAfterInsert = 'vehicle_colour_view.php?SelectedID=#ID#';
	$x->TableTitle = 'Vehicle Colour:';
	$x->TableIcon = 'resources/table_icons/Colorpencils128.png';
	$x->PrimaryKey = '`vehicle_colour`.`vehicle_colour_id`';

	$x->ColWidth = [150, 150, ];
	$x->ColCaption = ['Vehicle Colour ID:', 'Colour of Vehicle:', ];
	$x->ColFieldName = ['vehicle_colour_id', 'colour_of_vehicle', ];
	$x->ColNumber  = [1, 2, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/vehicle_colour_templateTV.html';
	$x->SelectedTemplate = 'templates/vehicle_colour_templateTVS.html';
	$x->TemplateDV = 'templates/vehicle_colour_templateDV.html';
	$x->TemplateDVP = 'templates/vehicle_colour_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: vehicle_colour_init
	$render = true;
	if(function_exists('vehicle_colour_init')) {
		$args = [];
		$render = vehicle_colour_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: vehicle_colour_header
	$headerCode = '';
	if(function_exists('vehicle_colour_header')) {
		$args = [];
		$headerCode = vehicle_colour_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: vehicle_colour_footer
	$footerCode = '';
	if(function_exists('vehicle_colour_footer')) {
		$args = [];
		$footerCode = vehicle_colour_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
